### ISSUE TITLE
[BUG] extension does not support x64 version of dotnet on mac with M1 chip

### ISSUE THREAD

**Issue by johnib** [microsoft/vscode-dotnettools#1011]
### Describe the Issue

I have a mac with M1 chip.
For reasons I cannot go into, I must use the x64 version of dotnet in my mac.

The vscode extension expects the dotnet to be in arm64 arch.

This create the following conflict:

```bash
Failed to find dotnet info from path, falling back to acquire runtime via ms-dotnettools.vscode-dotnet-runtime
The architecture of the .NET runtime (x64) does not match the architecture of the extension (arm64).
Dotnet path: /Users/jbarazany/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/8.0.3~arm64/dotnet
Activating C# standalone...
waiting for named pipe information from server...
[stdout] {"pipeName":"/var/folders/lx/ry_k5jmx3p7_0yp_prrpfj040000gn/T/2f3f247e.sock"}
received named pipe information from server
attempting to connect client to server...
client has connected to server
[Info  - 12:45:50 PM] [Program] Language server initialized
[Error - 12:45:51 PM] [LanguageServerProjectSystem] Failure while loading /Users/jbarazany/repos/prom-grafana/src/Simulator/Simulator.csproj: Exception thrown: Microsoft.CodeAnalysis.MSBuild.Rpc.RemoteInvocationException: An exception of type System.BadImageFormatException was thrown: Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. An attempt was made to load a program with an incorrect format.

   at Microsoft.CodeAnalysis.MSBuild.Rpc.RpcClient.InvokeCoreAsync(Int32 targetObject, String methodName, List`1 parameters, Type expectedReturnType, CancellationToken cancellationToken) in /_/src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs:line 163
   at Microsoft.CodeAnalysis.MSBuild.Rpc.RpcClient.InvokeAsync[T](Int32 targetObject, String methodName, List`1 parameters, CancellationToken cancellationToken) in /_/src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs:line 114
   at Microsoft.CodeAnalysis.MSBuild.Rpc.RemoteBuildHost.LoadProjectFileAsync(String projectFilePath, String languageName, CancellationToken cancellationToken) in /_/src/Workspaces/Core/MSBuild/Rpc/RemoteBuildHost.cs:line 33
   at Microsoft.CodeAnalysis.LanguageServer.HostWorkspace.LanguageServerProjectSystem.LoadOrReloadProjectAsync(ProjectToLoad projectToLoad, ToastErrorReporter toastErrorReporter, BuildHostProcessManager buildHostProcessManager, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs:line 226
[Info  - 12:45:51 PM] [LanguageServerProjectSystem] Completed (re)load of all projects in 00:00:00.7564447

```

### Steps To Reproduce

1. Install dotnet x64 on your mac M1
2. Install the vscode with this extension
3. Try to use the "Docker: add docker files to workspace" from the command-platte

### Environment Information

- OS: macOS
- dotnet:
```
.NET SDK:
 Version:           8.0.201
 Commit:            4c2d78f037
 Workload version:  8.0.200-manifests.3097af8b

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.4
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /Users/jbarazany/.dotnet/sdk/8.0.201/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.2
  Architecture: x64
  Commit:       1381d5ebd2

.NET SDKs installed:
  6.0.417 [/Users/jbarazany/.dotnet/sdk]
  8.0.100 [/Users/jbarazany/.dotnet/sdk]
  8.0.201 [/Users/jbarazany/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.25 [/Users/user/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [/Users/user/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.2 [/Users/user/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.25 [/Users/user/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [/Users/user/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.2 [/Users/user/.dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```
- Extension: 
Name: C# Dev Kit
Id: ms-dotnettools.csdevkit
Description: Official C# extension from Microsoft
Version: 1.4.29
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csdevkit

**Comment by Michael-Eng** [comment]
_The architecture of the .NET runtime (x64) does not match the architecture of the extension (arm64)._

When you install the extension from the marketplace, VS Code will install the ARM64 version of the extension (not within our control). The SDK you have installed is the x64 version of the SDK and we try to find the matching architecture of the extension and can't find it.

I *think* you can go to marketplace.visualstudio.com in the browser and choose to download the MacOS Intel vsix, and from there the extension should work with the x64 version of the SDK.

**Comment by webreidi** [comment]
@johnib If you are still experiencing this, please reopen the issue and provide more details.

**Comment by LeonSolisPedro** [comment]
@webreidi @Michael-Eng @johnib 

No longer works, it used to work by downloading the Intel vsix. but the website no longer shows download option.

Can someone help me with this?

Is there a way to compile the vsix C# dev kit?
