### ISSUE TITLE
can't attach unity debugger

### ISSUE THREAD

**Issue by Cxibo** [microsoft/vscode-dotnettools#1039]
Type: <b>Bug</b>

just nothing happen when i enter the command.
unity 2022 is running in debug mode.

Extension version: 1.0.0
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by sailro** [comment]
Hi @Cxibo , could you show us your `.vscode/launch.json` please? 

> When I enter the command

Which one? does it make a difference when using `F5` or when using `Attach Unity Debugger` fron the command palette?

Thanks!

**Comment by jbevain** [comment]
@Cxibo also, please make sure to update to 1.0.1, and turn the logging on from your launch.json:

![](https://private-user-images.githubusercontent.com/82753877/316734261-8deb267a-9c16-4eed-9258-ec30be31ddc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwODAwNjYsIm5iZiI6MTcxMjA3OTc2NiwicGF0aCI6Ii84Mjc1Mzg3Ny8zMTY3MzQyNjEtOGRlYjI2N2EtOWMxNi00ZWVkLTkyNTgtZWMzMGJlMzFkZGM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDE3NDI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiM2FhYTM2MGYyZTdiZjY0NzlhNzlkMTFiZmUzOGZjZGY0YWVmODg0NTA4OWIzMjMwM2E2MWMwM2Q3MDc0NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._2yJOqpAQKa00SBaDH6etkbBzAT7W1OVMI9y4Y_IdJY)

And let us know if there's any error in the log file?

**Comment by isiki0710** [comment]
--> R (attach-2): {"type":"response","request_seq":2,"success":false,"command":"attach","message":"Failed to attach debugger to 127.0.0.1:56968","body":{},"seq":2}
<--   C (disconnect-3): {"command":"disconnect","arguments":{"restart":false},"type":"request","seq":3}
Stopping due to fatal error: NullReferenceException: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at SyntaxTree.VisualStudio.Unity.Debugger.UnityEngine.Detach()
   at Microsoft.VisualStudio.Unity.AD7DebugAdapter.HandleDisconnectRequest(DisconnectArguments arguments)
   at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.DebugAdapterBase.HandleProtocolRequest(String requestType, Object requestArgs)
   at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.DebugAdapterBase.OnProtocolRequestReceived(Object sender, RequestReceivedEventArgs e)
   at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.DebugProtocol.OnRequestReceived(String command, IRequestResponder responder)
   at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.DebugAdapterBase.HandleDisconnectRequestAsync(IRequestResponder`1 responder)
   at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.DebugAdapterBase.<InitializeProtocolClient>b__5_12(IRequestResponder`1 r)
   at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.RequestInfo`1.Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.IRequestInfo.InvokeHandler(DebugProtocol protocol, ProtocolRequest request, Object args)
   at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.DebugProtocol.HandleIncomingRequest(String msg)
   at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.DebugProtocol.HandleIncomingMessage(String msg)
   at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.DebugProtocol.ProcessMessageBody()
   at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.DebugProtocol.ReaderThreadProc()

**Comment by sailro** [comment]
@isiki0710 I just fixed the issue related to the exception you are showing in your log. But this is just a side effect. It shows us that the debugger is unable to connect to the 127.0.0.1:56968 endpoint. So very probably a firewall issue or something preventing us from connecting.

**Comment by jbevain** [comment]
Closing as we haven't heard back. Feel free to re-open if you have more information. Thanks!
