### ISSUE TITLE
 Vs Code C# extensions fail to open with error Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

### ISSUE THREAD

**Issue by Supcar27** [microsoft/vscode-dotnettools#1044]
### Describe the Issue

on opening vs code in the output window i can see that the c# extensions are starting up, but then they crash and fail to start
here's the output logs on startup

> Using dotnet configured on PATH
Dotnet path: C:\Program Files\dotnet\dotnet.exe
Activating C# + C# Dev Kit + C# IntelliCode...
waiting for named pipe information from server...
[stdout] {"pipeName":"\\\\.\\pipe\\c4c6973a"}
received named pipe information from server
attempting to connect client to server...
client has connected to server
[Info  - 2:52:05 PM] [Program] Language server initialized
[stderr] Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

let me know if the full logs would be helpfull

### Steps To Reproduce

i'm not sure how to reproduce this as im not sure whats happening

### Environment Information

- OS: windows
- Vs Code version: 1.87.2

my vs code c# extension versions are

1. C# v2.23.15
2. C# Dev Kit v1.4.29
3. .Net install Tool v2.0.3

**Comment by Supcar27** [comment]
After 2 days with countless times restarting vs code and computer it just stopped happening today. no idea why this happend and why it not wtopped happening

**Comment by arkalyanms** [comment]
@Supcar27 when the issue happened, would you confirm if you had the same project open in another instance or in VS?

Also, the extension logs if you could share it would be helpful.

**Comment by arkalyanms** [comment]
Closing due to inactivity.

**Comment by gabynevada** [comment]
Getting the same error recently on a linux codespace, here is the error log. Also do not have other instances open.

<details close>
  <summary>Error Log</summary>

  ```
  Installing Razor Telemetry Version = 7.0.0-preview.24178.4...
  Platform: linux, x86_64, name=debian, version=12
  
  Downloading package 'Razor Language Server Telemetry (Linux / x64)' (9370 KB).................... Done!
  Validating download...
  Integrity Check succeeded.
  Installing package 'Razor Language Server Telemetry (Linux / x64)'
  
  Finished
  
  Using dotnet configured on PATH
  Dotnet path: /usr/share/dotnet/dotnet
  Activating C# + C# Dev Kit + C# IntelliCode...
  waiting for named pipe information from server...
  [stdout] {"pipeName":"/tmp/8895d31d.sock"}
  received named pipe information from server
  attempting to connect client to server...
  client has connected to server
  [Info  - 11:21:57 PM] [Program] Language server initialized
  [Info  - 11:22:06 PM] [WorkspaceProjectFactoryService] Project /workspaces/Bioportal/src/Bioportal.Helpers/Bioportal.Helpers.csproj loaded by C# Dev Kit
  [Info  - 11:22:06 PM] [WorkspaceProjectFactoryService] Project /workspaces/Bioportal/src/Bioportal.API/Bioportal.API.csproj loaded by C# Dev Kit
  [Info  - 11:22:07 PM] [WorkspaceProjectFactoryService] Project /workspaces/Bioportal/tests/Bioportal.Helpers.Tests.Unit/Bioportal.Helpers.Tests.Unit.csproj loaded by C# Dev Kit
  [Info  - 11:22:07 PM] [WorkspaceProjectFactoryService] Project /workspaces/Bioportal/src/Bioportal.Domain/Bioportal.Domain.csproj loaded by C# Dev Kit
  [Info  - 11:22:07 PM] [WorkspaceProjectFactoryService] Project /workspaces/Bioportal/src/Bioportal.Infrastructure/Bioportal.Infrastructure.csproj loaded by C# Dev Kit
  [Info  - 11:22:08 PM] [WorkspaceProjectFactoryService] Project /workspaces/Bioportal/src/Bioportal.Seeder/Bioportal.Seeder.csproj loaded by C# Dev Kit
  [Info  - 11:22:08 PM] [WorkspaceProjectFactoryService] Project /workspaces/Bioportal/src/Bioportal.Notifications/Bioportal.Notifications.csproj loaded by C# Dev Kit
  [Info  - 11:22:08 PM] [WorkspaceProjectFactoryService] Project /workspaces/Bioportal/src/Bioportal.CasesWorker/Bioportal.CasesWorker.csproj loaded by C# Dev Kit
  [Info  - 11:22:08 PM] [WorkspaceProjectFactoryService] Project /workspaces/Bioportal/src/Bioportal.Contracts/Bioportal.Contracts.csproj loaded by C# Dev Kit
  [Info  - 11:22:08 PM] [WorkspaceProjectFactoryService] Project /workspaces/Bioportal/src/Bioportal.InvestigationsWorker/Bioportal.InvestigationsWorker.csproj loaded by C# Dev Kit
  [Info  - 11:22:08 PM] [WorkspaceProjectFactoryService] Project /workspaces/Bioportal/src/Bioportal.Exports/Bioportal.Exports.csproj loaded by C# Dev Kit
  [Info  - 11:22:08 PM] [WorkspaceProjectFactoryService] Project /workspaces/Bioportal/src/Bioportal.OrdersWorker/Bioportal.OrdersWorker.csproj loaded by C# Dev Kit
  [Info  - 11:22:08 PM] [WorkspaceProjectFactoryService] Project /workspaces/Bioportal/src/Bioportal.BackgroundTasks/Bioportal.BackgroundTasks.csproj loaded by C# Dev Kit
  [stderr] Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  [stderr]    at System.Buffer.Memmove(Byte ByRef, Byte ByRef, UIntPtr)
     at System.IO.UnmanagedMemoryStream.WriteCore(System.ReadOnlySpan`1<Byte>)
     at System.IO.UnmanagedMemoryStream.Write(Byte[], Int32, Int32)
     at System.IO.Stream.Write(System.ReadOnlySpan`1<Byte>)
     at System.IO.StreamWriter.Flush(Boolean, Boolean)
     at System.IO.StreamWriter.Write(Char[], Int32, Int32)
     at Microsoft.CodeAnalysis.Text.LargeText.Write(System.IO.TextWriter, Microsoft.CodeAnalysis.Text.TextSpan, System.Threading.CancellationToken)
     at Microsoft.CodeAnalysis.Text.SourceText.Write(System.IO.TextWriter, System.Threading.CancellationToken)
     at Microsoft.CodeAnalysis.Host.TemporaryStorageService.<WriteToTemporaryStorage>g__WriteToMemoryMappedFile|12_0(<>c__DisplayClass12_0 ByRef)
     at Microsoft.CodeAnalysis.Host.TemporaryStorageService.WriteToTemporaryStorage(Microsoft.CodeAnalysis.Text.SourceText, System.Threading.CancellationToken)
     at Microsoft.CodeAnalysis.Host.TemporaryStorageService+<WriteToTemporaryStorageAsync>d__13.MoveNext()
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.CodeAnalysis.Host.TemporaryStorageService+<WriteToTemporaryStorageAsync>d__13, Microsoft.CodeAnalysis.Workspaces, Version=4.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<WriteToTemporaryStorageAsync>d__13 ByRef)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Microsoft.CodeAnalysis.Host.TemporaryStorageService+<WriteToTemporaryStorageAsync>d__13, Microsoft.CodeAnalysis.Workspaces, Version=4.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<WriteToTemporaryStorageAsync>d__13 ByRef)
     at Microsoft.CodeAnalysis.Host.TemporaryStorageService.WriteToTemporaryStorageAsync(Microsoft.CodeAnalysis.Text.SourceText, System.Threading.CancellationToken)
     at Microsoft.CodeAnalysis.Host.TemporaryStorageService+<Microsoft-CodeAnalysis-Host-ITemporaryStorageServiceInternal-WriteToTemporaryStorageAsync>d__11.MoveNext()
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.CodeAnalysis.Host.TemporaryStorageService+<Microsoft-CodeAnalysis-Host-ITemporaryStorageServiceInternal-WriteToTemporaryStorageAsync>d__11, Microsoft.CodeAnalysis.Workspaces, Version=4.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<Microsoft-CodeAnalysis-Host-ITemporaryStorageServiceInternal-WriteToTemporaryStorageAsync>d__11 ByRef)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Microsoft.CodeAnalysis.Host.TemporaryStorageService+<Microsoft-CodeAnalysis-Host-ITemporaryStorageServiceInternal-WriteToTemporaryStorageAsync>d__11, Microsoft.CodeAnalysis.Workspaces, Version=4.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<Microsoft-CodeAnalysis-Host-ITemporaryStorageServiceInternal-WriteToTemporaryStorageAsync>d__11 ByRef)
     at Microsoft.CodeAnalysis.Host.TemporaryStorageService.Microsoft.CodeAnalysis.Host.ITemporaryStorageServiceInternal.WriteToTemporaryStorageAsync(Microsoft.CodeAnalysis.Text.SourceText, System.Threading.CancellationToken)
     at Microsoft.CodeAnalysis.RecoverableTextAndVersion+RecoverableText+<SaveAsync>d__12.MoveNext()
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.CodeAnalysis.RecoverableTextAndVersion+RecoverableText+<SaveAsync>d__12, Microsoft.CodeAnalysis.Workspaces, Version=4.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<SaveAsync>d__12 ByRef)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.CodeAnalysis.RecoverableTextAndVersion+RecoverableText+<SaveAsync>d__12, Microsoft.CodeAnalysis.Workspaces, Version=4.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<SaveAsync>d__12 ByRef)
     at Microsoft.CodeAnalysis.RecoverableTextAndVersion+RecoverableText.SaveAsync(Microsoft.CodeAnalysis.Text.SourceText, System.Threading.CancellationToken)
     at Microsoft.CodeAnalysis.RecoverableTextAndVersion+RecoverableText+<SaveAllAsync>d__27.MoveNext()
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.CodeAnalysis.RecoverableTextAndVersion+RecoverableText+<SaveAllAsync>d__27, Microsoft.CodeAnalysis.Workspaces, Version=4.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<SaveAllAsync>d__27 ByRef)
     at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder.Start[[Microsoft.CodeAnalysis.RecoverableTextAndVersion+RecoverableText+<SaveAllAsync>d__27, Microsoft.CodeAnalysis.Workspaces, Version=4.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<SaveAllAsync>d__27 ByRef)
     at Microsoft.CodeAnalysis.RecoverableTextAndVersion+RecoverableText.SaveAllAsync(Microsoft.CodeAnalysis.Collections.ImmutableSegmentedList`1<System.ValueTuple`2<RecoverableText,Microsoft.CodeAnalysis.Text.SourceText>>, System.Threading.CancellationToken)
     at Roslyn.Utilities.AsyncBatchingWorkQueue`1+<>c__DisplayClass2_0+<<Convert>b__0>d[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Roslyn.Utilities.AsyncBatchingWorkQueue`1+<>c__DisplayClass2_0+<<Convert>b__0>d[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Microsoft.CodeAnalysis.Workspaces, Version=4.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<<Convert>b__0>d<System.ValueTuple`2<System.__Canon,System.__Canon>> ByRef)
     at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1[[Roslyn.Utilities.VoidResult, Microsoft.CodeAnalysis.Workspaces, Version=4.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].Start[[Roslyn.Utilities.AsyncBatchingWorkQueue`1+<>c__DisplayClass2_0+<<Convert>b__0>d[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Microsoft.CodeAnalysis.Workspaces, Version=4.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<<Convert>b__0>d<System.ValueTuple`2<System.__Canon,System.__Canon>> ByRef)
     at Roslyn.Utilities.AsyncBatchingWorkQueue`1+<>c__DisplayClass2_0[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<Convert>b__0(Microsoft.CodeAnalysis.Collections.ImmutableSegmentedList`1<System.ValueTuple`2<System.__Canon,System.__Canon>>, System.Threading.CancellationToken)
     at Roslyn.Utilities.AsyncBatchingWorkQueue`2+<ProcessNextBatchAsync>d__17[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Roslyn.Utilities.VoidResult, Microsoft.CodeAnalysis.Workspaces, Version=4.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Roslyn.Utilities.AsyncBatchingWorkQueue`2+<ProcessNextBatchAsync>d__17[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Roslyn.Utilities.VoidResult, Microsoft.CodeAnalysis.Workspaces, Version=4.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]], Microsoft.CodeAnalysis.Workspaces, Version=4.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<ProcessNextBatchAsync>d__17<System.ValueTuple`2<System.__Canon,System.__Canon>,Roslyn.Utilities.VoidResult> ByRef)
     at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1[[Roslyn.Utilities.VoidResult, Microsoft.CodeAnalysis.Workspaces, Version=4.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].Start[[Roslyn.Utilities.AsyncBatchingWorkQueue`2+<ProcessNextBatchAsync>d__17[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Roslyn.Utilities.VoidResult, Microsoft.CodeAnalysis.Workspaces, Version=4.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]], Microsoft.CodeAnalysis.Workspaces, Version=4.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<ProcessNextBatchAsync>d__17<System.ValueTuple`2<System.__Canon,System.__Canon>,Roslyn.Utilities.VoidResult> ByRef)
     at Roslyn.Utilities.AsyncBatchingWorkQueue`2[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Roslyn.Utilities.VoidResult, Microsoft.CodeAnalysis.Workspaces, Version=4.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].ProcessNextBatchAsync()
  [stderr]    at Roslyn.Utilities.AsyncBatchingWorkQueue`2+<<AddWork>g__ContinueAfterDelayAsync|15_1>d[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Roslyn.Utilities.VoidResult, Microsoft.CodeAnalysis.Workspaces, Version=4.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[Roslyn.Utilities.VoidResult, Microsoft.CodeAnalysis.Workspaces, Version=4.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35],[Roslyn.Utilities.AsyncBatchingWorkQueue`2+<<AddWork>g__ContinueAfterDelayAsync|15_1>d[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Roslyn.Utilities.VoidResult, Microsoft.CodeAnalysis.Workspaces, Version=4.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]], Microsoft.CodeAnalysis.Workspaces, Version=4.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].ExecutionContextCallback(System.Object)
     at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[Roslyn.Utilities.VoidResult, Microsoft.CodeAnalysis.Workspaces, Version=4.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35],[Roslyn.Utilities.AsyncBatchingWorkQueue`2+<<AddWork>g__ContinueAfterDelayAsync|15_1>d[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Roslyn.Utilities.VoidResult, Microsoft.CodeAnalysis.Workspaces, Version=4.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]], Microsoft.CodeAnalysis.Workspaces, Version=4.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext(System.Threading.Thread)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[Roslyn.Utilities.VoidResult, Microsoft.CodeAnalysis.Workspaces, Version=4.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35],[Roslyn.Utilities.AsyncBatchingWorkQueue`2+<<AddWork>g__ContinueAfterDelayAsync|15_1>d[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Roslyn.Utilities.VoidResult, Microsoft.CodeAnalysis.Workspaces, Version=4.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]], Microsoft.CodeAnalysis.Workspaces, Version=4.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
     at System.Threading.ThreadPoolWorkQueue.Dispatch()
     at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
  [Info  - 11:22:18 PM] Connection to server got closed. Server will restart.
  true
  Language server process exited with null
  Using dotnet configured on PATH
  Dotnet path: /usr/share/dotnet/dotnet
  Activating C# + C# Dev Kit + C# IntelliCode...
  waiting for named pipe information from server...
  [stdout] fail: Microsoft.CodeAnalysis.LanguageServer.ExportProviderBuilder[0]
        /home/vscode/.vscode-remote/extensions/ms-dotnettools.csharp-2.30.24-linux-x64/.xamlTools/Microsoft.VisualStudio.DesignTools.CodeAnalysis.dll with assembly name Microsoft.VisualStud[stdout] io.DesignTools.CodeAnalysis, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a conflicts with extension loaded from /home/vscode/.vscode-remote/extensions/ms-dotnettools.csharp-2.30.24-linux-x64/.xamlTools
  [stdout] fail: Microsoft.CodeAnalysis.LanguageServer.ExportProviderBuilder[0]
        /home/vscode/.vscode-remote/extensions/ms-dotnettools.csharp-2.30.24-linux-x64/.xamlTools/Microsoft.VisualStudio.DesignTools.CodeAnalysis.Diagnostics.dll with assembly name Microsof[stdout] t.VisualStudio.DesignTools.CodeAnalysis.Diagnostics, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a conflicts with extension loaded from /home/vscode/.vscode-remote/extensions/ms-dotnettools.csharp-2.30.24-linux-x64/.xamlTools
  [stdout] {"pipeName":"/tmp/1713a48b.sock"}
  received named pipe information from server
  attempting to connect client to server...
  client has connected to server
  [Info  - 11:22:20 PM] [Program] Language server initialized
  ```
</details>
