### ISSUE TITLE
[BUG] Maui extension won't load after fresh install

### ISSUE THREAD

**Issue by SamGustinHdr** [microsoft/vscode-dotnettools#1203]
### Describe the Issue

This is occurring in the latest release and pre-release versions.

**Version: v1.0.6**
```
2024-06-14 13:02:55.227 [info] Extension host with pid 68804 started
2024-06-14 13:02:55.227 [info] Skipping acquiring lock for /Users/sgustim/Library/Application Support/Code/User/workspaceStorage/71ea504801a672e99a580bc76d59c845.
2024-06-14 13:02:55.300 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2024-06-14 13:02:55.319 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2024-06-14 13:02:55.338 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2024-06-14 13:02:55.391 [info] Eager extensions activated
2024-06-14 13:02:55.424 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2024-06-14 13:02:55.428 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2024-06-14 13:02:55.447 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2024-06-14 13:02:55.514 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2024-06-14 13:03:18.744 [info] ExtensionService#_doActivateExtension ms-dotnettools.vscode-dotnet-runtime, startup: false, activationEvent: 'onStartupFinished'
2024-06-14 13:03:18.787 [info] ExtensionService#_doActivateExtension ms-dotnettools.csharp, startup: false, activationEvent: 'workspaceContains:**/*.csproj', root cause: ms-dotnettools.csdevkit
2024-06-14 13:03:20.590 [info] ExtensionService#_doActivateExtension ms-dotnettools.csdevkit, startup: false, activationEvent: 'workspaceContains:**/*.csproj'
2024-06-14 13:03:20.785 [info] ExtensionService#_doActivateExtension ms-dotnettools.dotnet-maui, startup: false, activationEvent: 'workspaceContains:**/*.csproj'
2024-06-14 13:03:20.899 [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
2024-06-14 13:03:34.282 [warning] DiagnosticCollection with name 'XamlDiagnostics' does already exist.
2024-06-14 13:03:34.282 [warning] DiagnosticCollection with name 'HotReloadDiagnostics' does already exist.
2024-06-14 13:03:41.219 [info] ExtensionService#_doActivateExtension vscode.html-language-features, startup: false, activationEvent: 'onLanguage:html'
2024-06-14 13:03:45.998 [error] TypeError: Cannot read properties of undefined (reading 'forEach')
	at t.MauiDebugTargetsManager.refreshPlatformsStatus (/Users/sgustim/.vscode/extensions/ms-dotnettools.dotnet-maui-1.0.6-darwin-arm64/dist/extension.js:2:464524)
	at t.MauiDebugTargetsManager.devicesChanged (/Users/sgustim/.vscode/extensions/ms-dotnettools.dotnet-maui-1.0.6-darwin-arm64/dist/extension.js:2:464470)
	at n.value (/Users/sgustim/.vscode/extensions/ms-dotnettools.dotnet-maui-1.0.6-darwin-arm64/dist/extension.js:2:457606)
	at l.y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:664)
	at l.z (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:734)
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:950)
	at t.EventStream.push (/Users/sgustim/.vscode/extensions/ms-dotnettools.dotnet-maui-1.0.6-darwin-arm64/dist/extension.js:2:402899)
	at t.ProjectTrackers.notifyProjectsChanged (/Users/sgustim/.vscode/extensions/ms-dotnettools.dotnet-maui-1.0.6-darwin-arm64/dist/extension.js:2:445562)

```

**Version: 1.1.6**
```
2024-06-14 13:08:13.547 [info] Extension host terminating: renderer closed the MessagePort
2024-06-14 13:08:13.568 [error] Canceled: Canceled
	at new A (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:143:50615)
	at E.U (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:6007)
	at z.<computed>.M.charCodeAt.R.CharCode.DollarSign.z.<computed> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:3091)
	at h.g (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:199937)
	at h.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:199375)
	at I.registerCommand.description (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:198699)
	at h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:200476)
	at h.g (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:199468)
	at h.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:199375)
	at Object.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:163:22742)
	at n.O [as value] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:945191)
	at l.y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:664)
	at l.z (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:734)
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:950)
	at Object.p [as dispose] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:964275)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:970313
	at Array.forEach (<anonymous>)
	at f.dispose (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:970299)
	at a.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:151:4032)
	at a.dispose (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:151:4129)
	at a.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:947448)
	at a.dispose (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:151:4129)
	at f (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:744)
	at u.eb (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:159:9991)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:159:7867
	at Array.map (<anonymous>)
	at u.$ (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:159:7854)
	at u.terminate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:159:8127)
	at f.terminate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:163:1513)
	at t (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:176:10459)
	at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:176:6675)
	at MessagePortMain.emit (node:events:514:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2285) setContext undefined
2024-06-14 13:08:13.569 [error] Canceled: Canceled
	at new A (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:143:50615)
	at E.U (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:6007)
	at z.<computed>.M.charCodeAt.R.CharCode.DollarSign.z.<computed> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:3091)
	at h.g (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:199937)
	at h.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:199375)
	at I.registerCommand.description (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:198699)
	at h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:200476)
	at h.g (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:199468)
	at h.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:199375)
	at Object.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:163:22742)
	at set hasGitHubRepositories (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github/dist/extension.js:2:322969)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github/dist/extension.js:2:323928
	at n.value (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:1050764)
	at l.y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:664)
	at l.z (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:734)
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:950)
	at Object.p [as dispose] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:964275)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:970313
	at Array.forEach (<anonymous>)
	at f.dispose (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:970299)
	at a.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:151:4032)
	at a.dispose (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:151:4129)
	at a.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:947448)
	at a.dispose (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:151:4129)
	at f (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:744)
	at u.eb (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:159:9991)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:159:7867
	at Array.map (<anonymous>)
	at u.$ (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:159:7854)
	at u.terminate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:159:8127)
	at f.terminate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:163:1513)
	at t (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:176:10459)
	at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:176:6675)
	at MessagePortMain.emit (node:events:514:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2285) setContext undefined
2024-06-14 13:08:13.570 [info] Extension host with pid 69516 exiting with code 0
2024-06-14 13:08:13.874 [info] Extension host with pid 69789 started
2024-06-14 13:08:13.874 [info] Skipping acquiring lock for /Users/sgustim/Library/Application Support/Code/User/workspaceStorage/71ea504801a672e99a580bc76d59c845.
2024-06-14 13:08:13.877 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2024-06-14 13:08:13.881 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2024-06-14 13:08:13.891 [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
2024-06-14 13:08:13.897 [info] ExtensionService#_doActivateExtension ms-dotnettools.vscode-dotnet-runtime, startup: false, activationEvent: 'onLanguage:aspnetcorerazor', root cause: ms-dotnettools.csharp
2024-06-14 13:08:13.920 [info] ExtensionService#_doActivateExtension vscode.html-language-features, startup: false, activationEvent: 'onLanguage:html'
2024-06-14 13:08:13.930 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: false, activationEvent: 'onFileSystem:git', root cause: vscode.git
2024-06-14 13:08:13.963 [info] ExtensionService#_doActivateExtension ms-dotnettools.csharp, startup: false, activationEvent: 'onLanguage:aspnetcorerazor'
2024-06-14 13:08:13.989 [info] ExtensionService#_doActivateExtension vscode.git, startup: false, activationEvent: 'onFileSystem:git'
2024-06-14 13:08:14.029 [info] ExtensionService#_doActivateExtension ms-dotnettools.csdevkit, startup: false, activationEvent: 'onLanguage:csharp'
2024-06-14 13:08:14.091 [info] ExtensionService#_doActivateExtension ms-dotnettools.dotnet-maui, startup: false, activationEvent: 'onLanguage:csharp'
2024-06-14 13:08:14.212 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2024-06-14 13:08:14.220 [info] Eager extensions activated
2024-06-14 13:08:14.227 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2024-06-14 13:08:14.229 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2024-06-14 13:08:15.113 [warning] DiagnosticCollection with name 'XamlDiagnostics' does already exist.
2024-06-14 13:08:15.113 [warning] DiagnosticCollection with name 'HotReloadDiagnostics' does already exist.
2024-06-14 13:08:23.743 [error] TypeError: Cannot read properties of undefined (reading 'forEach')
	at t.MauiDebugTargetsManager.refreshPlatformsStatus (/Users/sgustim/.vscode/extensions/ms-dotnettools.dotnet-maui-1.1.6-darwin-arm64/dist/extension.js:2:461688)
	at t.MauiDebugTargetsManager.devicesChanged (/Users/sgustim/.vscode/extensions/ms-dotnettools.dotnet-maui-1.1.6-darwin-arm64/dist/extension.js:2:461634)
	at n.value (/Users/sgustim/.vscode/extensions/ms-dotnettools.dotnet-maui-1.1.6-darwin-arm64/dist/extension.js:2:454770)
	at l.y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:664)
	at l.z (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:734)
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:950)
	at t.EventStream.push (/Users/sgustim/.vscode/extensions/ms-dotnettools.dotnet-maui-1.1.6-darwin-arm64/dist/extension.js:2:400063)
	at t.ProjectTrackers.notifyProjectsChanged (/Users/sgustim/.vscode/extensions/ms-dotnettools.dotnet-maui-1.1.6-darwin-arm64/dist/extension.js:2:442726)
```

### Steps To Reproduce

1. Intall extension
2. Observe extension logs

**Comment by mauroa** [comment]
Hi @SamGustinHdr, thanks for your feedback.

According to your repro steps, it's not clear what is really happening and when.

Based on your provided information and repro steps, it looks like you install the extension and something in the installation fails (you just say install extension, observe extension logs).

However, according to the provided logs, it seems that you are trying to load a MAUI app and then it fails.

Could you please be more detailed on the repro steps and on your particular issue so we can investigate further?

Thanks

**Comment by SamGustinHdr** [comment]
Hi @mauroa,

The logs that I provided are from me installing the extension and then opening any maui project.

![image](https://github.com/microsoft/vscode-dotnettools/assets/167120511/33d6ef1e-4a64-4e85-b889-e1085dfa4b93)

**Comment by SamGustinHdr** [comment]
C# output:
```
Using dotnet configured on PATH
Dotnet path: /usr/local/share/dotnet/dotnet
Activating C# + C# Dev Kit...
waiting for named pipe information from server...
[stdout] {"pipeName":"/var/folders/tn/ndtg0sg95_s3578hl0s64l0w0000gp/T/c636566f.sock"}
received named pipe information from server
attempting to connect client to server...
client has connected to server
[Info  - 12:03:48 PM] [Program] Language server initialized
[Info  - 12:03:51 PM] [WorkspaceProjectFactoryService] Project /Users/sgustim/Repos/nucleus-mobile/Nucleus.Mobile/HDR.Mobile.Core/HDR.Mobile.Core.csproj loaded by C# Dev Kit
[Info  - 12:03:51 PM] [WorkspaceProjectFactoryService] Project /Users/sgustim/Repos/nucleus-mobile/Nucleus.Mobile/HDR.Mobile.Test.Core/HDR.Mobile.Test.Core.csproj loaded by C# Dev Kit
[Info  - 12:03:51 PM] [WorkspaceProjectFactoryService] Project /Users/sgustim/Repos/nucleus-mobile/Nucleus.Mobile/Nucleus.Core/Nucleus.Core.csproj loaded by C# Dev Kit
[Info  - 12:03:51 PM] [WorkspaceProjectFactoryService] Project /Users/sgustim/Repos/nucleus-mobile/Nucleus.Mobile/HDR.Mobile.Maui/HDR.Mobile.Maui.csproj loaded by C# Dev Kit
[Info  - 12:03:51 PM] [WorkspaceProjectFactoryService] Project /Users/sgustim/Repos/nucleus-mobile/Nucleus.Mobile/HDR.Mobile.Maui.Syncfusion/HDR.Mobile.Maui.Syncfusion.csproj loaded by C# Dev Kit
[Info  - 12:03:52 PM] [WorkspaceProjectFactoryService] Project /Users/sgustim/Repos/nucleus-mobile/Nucleus.Mobile/Nucleus.Mobile.UI.Test/Nucleus.Mobile.UI.Test.csproj loaded by C# Dev Kit
[Info  - 12:03:52 PM] [WorkspaceProjectFactoryService] Project /Users/sgustim/Repos/nucleus-mobile/Nucleus.Mobile/Nucleus.EFConsole/Nucleus.EFConsole.csproj loaded by C# Dev Kit
[Info  - 12:03:52 PM] [WorkspaceProjectFactoryService] Project /Users/sgustim/Repos/nucleus-mobile/Nucleus.Mobile/HDR.Mobile.Maui.Syncfusion/HDR.Mobile.Maui.Syncfusion.csproj loaded by C# Dev Kit
[Info  - 12:03:52 PM] [WorkspaceProjectFactoryService] Project /Users/sgustim/Repos/nucleus-mobile/Nucleus.Mobile/HDR.Mobile.Maui/HDR.Mobile.Maui.csproj loaded by C# Dev Kit
[Info  - 12:03:52 PM] [WorkspaceProjectFactoryService] Project /Users/sgustim/Repos/nucleus-mobile/Nucleus.Mobile/HDR.Mobile.Maui.Blazor.SF/HDR.Mobile.Maui.Blazor.SF.csproj loaded by C# Dev Kit
[Info  - 12:03:52 PM] [WorkspaceProjectFactoryService] Project /Users/sgustim/Repos/nucleus-mobile/Nucleus.Mobile/Nucleus.Mobile/Nucleus.Mobile.csproj loaded by C# Dev Kit
[Info  - 12:03:52 PM] [WorkspaceProjectFactoryService] Project /Users/sgustim/Repos/nucleus-mobile/Nucleus.Mobile/Nucleus.Core.Test/Nucleus.Core.Test.csproj loaded by C# Dev Kit
[Info  - 12:03:53 PM] [WorkspaceProjectFactoryService] Project /Users/sgustim/Repos/nucleus-mobile/Nucleus.Mobile/HDR.Mobile.Maui.Blazor.SF/HDR.Mobile.Maui.Blazor.SF.csproj loaded by C# Dev Kit
[Info  - 12:03:53 PM] [WorkspaceProjectFactoryService] Project /Users/sgustim/Repos/nucleus-mobile/Nucleus.Mobile/Nucleus.Mobile/Nucleus.Mobile.csproj loaded by C# Dev Kit
```

C# dev kit:
```
Starting Spawn .NET server...
Starting Open a solution...
Starting handling solution file "/Users/sgustim/Repos/nucleus-mobile/Nucleus.Mobile/Nucleus.Mobile.sln" in Dev Kit server...
Starting Clear environment...
Using preinstalled .NET runtime at "/usr/local/share/dotnet/dotnet"
.NET server started and IPC established in 1363ms
Completed Spawn .NET server (1640ms)
Completed Clear environment (1864ms)
Completed handling solution file "/Users/sgustim/Repos/nucleus-mobile/Nucleus.Mobile/Nucleus.Mobile.sln" in Dev Kit server (1943ms)
Starting Restore solution...
Selected configuration: null, active configuration: Debug|Any CPU
Completed Open a solution (1949ms)
Starting NuGet restore for the solution.
Starting command: "dotnet" restore /Users/sgustim/Repos/nucleus-mobile/Nucleus.Mobile/Nucleus.Mobile.sln --interactive...
Completed command: "dotnet" restore /Users/sgustim/Repos/nucleus-mobile/Nucleus.Mobile/Nucleus.Mobile.sln --interactive (2059ms)
Completed NuGet restore.
Completed Restore solution (2059ms)
```

.NET MAUI output:
```
Java SDK path to be used: /Library/Java/JavaVirtualMachines/microsoft-17.jdk/Contents/Home
User preferred Android SDK path stored on Settings: /Users/sgustim/<AndroidSdkPath>
Android SDK path to be used: /Users/sgustim/Library/Android/sdk
 
Android components:
	- Java SDK: installed version '17.0.10'
 
	Android SDK recommended required components:
	- platforms/android-34: installed version '3'
	- build-tools/34.0.0: installed version '34.0.0'
	- platform-tools: installed version '35.0.1'
	- cmdline-tools/11.0: installed version '11.0'
 
	Android SDK recommended optional components:
	- emulator: installed version '34.2.13'
	- system-images/android-34/google_apis/arm64-v8a: installed version '8'
 
 
Xcode:
	- Path: /Applications/Xcode.app
	- Discovered from: xcode-select -p
	- Installed: true
```

**Comment by AllenD-MSFT** [comment]
A fix for this issue has been release with the most recent (yesterday's) update to MAUI DevKit in the Prerelease channel. @SamGustinHdr , can you try that out and let us know if you see the fix working for you?
