### ISSUE TITLE
Project system ran into an unexpected problem, please report it to the product team.

### ISSUE THREAD

**Issue by solrevdev** [microsoft/vscode-dotnettools#123]
Type: <b>Bug</b>

I was running a clean build of my project and I got told the project system ran into a problem and to report it. 

It opened a log file. See below. I didn't notice anything other than that but instinct made me reload window or close and re-open I forget which and all seemed well again.

```
=====================
12/06/2023 22:59:45
LimitedFunctionality
System.AggregateException: Project system data flow 'ProjectBuildSnapshotService' closed because of an exception.
The JSON-RPC connection with the remote party was lost before the request could complete. (The JSON-RPC connection with the remote party was lost before the request could complete.)
---> (Inner Exception #0) StreamJsonRpc.ConnectionLostException: The JSON-RPC connection with the remote party was lost before the request could complete.
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync(JsonRpcRequest request, Type expectedResultType, CancellationToken cancellationToken)
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
   at Microsoft.VisualStudio.ProjectSystem.Server.BuildManagerServerAdapter.Microsoft.VisualStudio.ProjectServices.IBuildManager.ExecuteBuildRequestAsync(BuildRequestData buildRequestData)
<--- (Inner Exception #0) 
===================
12/06/2023 22:59:45
LimitedFunctionality
System.AggregateException: Project system data flow 'ProjectBuildSubscriptionService' closed because of an exception.
The JSON-RPC connection with the remote party was lost before the request could complete. (The JSON-RPC connection with the remote party was lost before the request could complete.)
---> (Inner Exception #0) StreamJsonRpc.ConnectionLostException: The JSON-RPC connection with the remote party was lost before the request could complete.
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync(JsonRpcRequest request, Type expectedResultType, CancellationToken cancellationToken)
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
   at Microsoft.VisualStudio.ProjectSystem.Server.BuildManagerServerAdapter.Microsoft.VisualStudio.ProjectServices.IBuildManager.ExecuteBuildRequestAsync(BuildRequestData buildRequestData)
<--- (Inner Exception #0) 
===================
```

The script I ran was: 

```bash
#!/usr/bin/env bash

cd "$(dirname "$0")" || exit

echo "Cleaning then building solution.sln from the $(pwd) directory"

dotnet clean ../solution.sln

echo "Deleting any existing bin and obj folders"
rm -rf ../src/Web/bin
rm -rf ../src/Web/obj
rm -rf ../src/Core/bin
rm -rf ../src/Core/obj
rm -rf ../tests/Core.Tests/bin
rm -rf ../tests/Core.Tests/obj

dotnet build ../solution.sln

echo "✅ Clean and build complete"
```

Extension version: 0.1.83
VS Code version: Code - Insiders 1.80.0-insider (Universal) (ef6abe4cd1573689d070b8715e97019cfadaeb51, 2023-06-12T05:25:17.588Z)
OS version: Darwin x64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|15, 10, 9|
|Memory (System)|16.00GB (0.41GB free)|
|Process Argv|--crash-reporter-id 5d0d121e-4fd7-480f-9d89-754f35cbb27e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
py29gd2263cf:30763247
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
showlangstatbar:30737417
pythonms35:30671666
pythonfmttext:30716741
pythoncmvfstr:30726892
fixhidewlkth:30724384
showsbindicator:30724477
pythongtdpath:30726887
bgfeh915:30763804
dh2dc718:30763024
pythonnosmt12:30757129
pythonidxpt:30763123
pythondjangots:30763122

```

</details>

**Comment by chzuluag** [comment]
This issue has been resolved in the latest released version of the C# Dev Kit. Let us know if you keep running into the same problem with the new version.
