### ISSUE TITLE
[BUG] Can't install latest Dev Kit (NullReferenceException)

### ISSUE THREAD

**Issue by sliekens** [microsoft/vscode-dotnettools#1351]
### Describe the Issue

The 1.10.4 release won't appear in my VSCode even though I can see it on the marketplace. Downloading the VSIX and then running it also fails with an error.

```
08/08/2024 22:55:37 - Microsoft VSIX Installer
08/08/2024 22:55:37 - -------------------------------------------
08/08/2024 22:55:37 - vsixinstaller.exe version:
08/08/2024 22:55:37 - 17.10.2185+1efd885b2e
08/08/2024 22:55:37 - -------------------------------------------
08/08/2024 22:55:37 - Command line parameters:
08/08/2024 22:55:37 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,S:\Steven\Downloads\ms-dotnettools.csdevkit-1.10.4@win32-x64.vsix
08/08/2024 22:55:37 - -------------------------------------------
08/08/2024 22:55:37 - Microsoft VSIX Installer
08/08/2024 22:55:37 - -------------------------------------------
08/08/2024 22:55:37 - Initializing Install...
08/08/2024 22:55:37 - Searching for applicable products...
08/08/2024 22:55:38 - Found installed product - Visual Studio Professional 2022
08/08/2024 22:55:38 - Found installed product - Global Location
08/08/2024 22:55:38 - Extension Details...
08/08/2024 22:55:38 - 	Identifier         : csdevkit
08/08/2024 22:55:38 - 	Name               : C# Dev Kit
08/08/2024 22:55:38 - 	Author             : ms-dotnettools
08/08/2024 22:55:38 - 	Version            : 1.10.4
08/08/2024 22:55:38 - 	Description        : Official C# extension from Microsoft
08/08/2024 22:55:38 - 	Locale             : en-US
08/08/2024 22:55:38 - 	MoreInfoURL        : 
08/08/2024 22:55:38 - 	InstalledByMSI     : False
08/08/2024 22:55:38 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
08/08/2024 22:55:38 - 	SignatureState     : InvalidSignature
08/08/2024 22:55:38 - 	SignedBy           : Microsoft Corporation
08/08/2024 22:55:38 - 	Certificate Info   : 
08/08/2024 22:55:38 - 		-------------------------------------------------------
08/08/2024 22:55:38 - 		[Subject]       : CN=Microsoft Corporation, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
08/08/2024 22:55:38 - 		[Issuer]        : CN=Microsoft Code Signing PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
08/08/2024 22:55:38 - 		[Serial Number] : 330000056067F73C897D62BABD000000000560
08/08/2024 22:55:38 - 		[Not Before]    : 11/01/2024 21:05:33
08/08/2024 22:55:38 - 		[Not After]     : 10/01/2025 21:05:33
08/08/2024 22:55:38 - 		[Thumbprint]    : 80AF76D324CE728D7DF51CDCA241F5E9598169B7
08/08/2024 22:55:38 - 	Supported Products : 
08/08/2024 22:55:38 - 		Microsoft.VisualStudio.Code
08/08/2024 22:55:38 - 			Version : 
08/08/2024 22:55:38 - 			ProductArchitecture : x86
08/08/2024 22:55:38 - 	References         : 
08/08/2024 22:55:38 - Signature Details...
08/08/2024 22:55:38 - 	Extension is signed with an invalid signature.
08/08/2024 22:55:38 - System.NullReferenceException: Object reference not set to an instance of an object.
   at VSIXInstaller.ExtensionService.LogSignatureDetails(IExtension extension)
   at VSIXInstaller.ExtensionService.LogExtensionDetails(IExtension extension)
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

```

### Steps To Reproduce

Download 1.10.4 for Windows x64 from https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csdevkit

### Expected Behavior

Installation should proceed

### Environment Information

Version: 1.92.1 (user setup)
Commit: eaa41d57266683296de7d118f574d0c2652e1fc4
Date: 2024-08-07T20:16:39.455Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by sliekens** [comment]
A few more observations:

- 1.10.4 does appear when I switch to pre-release in VSCode
- The marketplace does not indicate pre-release status, it's only mentioned in the change log
