### ISSUE TITLE
[BUG] 20k+ bogus reported errors ping-ponging in- and out of existence

### ISSUE THREAD

**Issue by rjgotten** [microsoft/vscode-dotnettools#1371]
### Describe the Issue

Opening a C# solution containing ~80 projects, configured with
```
"dotnet.backgroundAnalysis.analyzerDiagnosticsScope": "fullSolution",
"dotnet.backgroundAnalysis.compilerDiagnosticsScope": "fullSolution"
```

results in the errors panel ping-ponging like crazy between the normal and accurate diagnostics warnings, and an additional 20k+ of phantom non-existent errors wrt classes or namespaces not existing. This includes errors wrt classes and namespaces defined in the solution itself, as well as predefined classes such as `System.Int32`, `Task` or `Nullable`.

Some of the affected files are all `*.cshtml__virtual.cs` files related to MVC Razor. They contribute ~500 errors. These appear to be more persistent in that they don't blink in and out of existence as frequently.

In addition, the VSCode Extensions Host output log contains an unending deluge of the same error, repeating every ~100ms :
```
2024-08-16 11:22:02.180 [error] Error: Illegal argument: line must be non-negative
	at d (c:\Users\r.otten\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:10:1029)
	at new u (c:\Users\r.otten\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:4879)
	at f (c:\Users\r.otten\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:6395)
	at C (c:\Users\r.otten\.vscode\extensions\ms-dotnettools.csharp-2.39.29-win32-x64\dist\extension.js:2:2229754)
	at w (c:\Users\r.otten\.vscode\extensions\ms-dotnettools.csharp-2.39.29-win32-x64\dist\extension.js:2:2228739)
	at c (c:\Users\r.otten\.vscode\extensions\ms-dotnettools.csharp-2.39.29-win32-x64\dist\extension.js:2:2273282)
	at t.map (c:\Users\r.otten\.vscode\extensions\ms-dotnettools.csharp-2.39.29-win32-x64\dist\extension.js:2:2273368)
	at Object.asDiagnostics (c:\Users\r.otten\.vscode\extensions\ms-dotnettools.csharp-2.39.29-win32-x64\dist\extension.js:2:2241065)
	at S.workDiagnosticQueue (c:\Users\r.otten\.vscode\extensions\ms-dotnettools.csharp-2.39.29-win32-x64\dist\extension.js:2:2123269)
	at Immediate.<anonymous> (c:\Users\r.otten\.vscode\extensions\ms-dotnettools.csharp-2.39.29-win32-x64\dist\extension.js:2:2122935)
	at process.processImmediate (node:internal/timers:478:21)
```

Additionally, csdevkit occasionally spews out an illegal write after end as well:

```
2024-08-16 11:45:53.583 [error] Error: write after end
	at _write (node:internal/streams/writable:481:11)
	at Writable.write (node:internal/streams/writable:502:10)
	at c:\Users\r.otten\.vscode\extensions\ms-dotnettools.csdevkit-1.9.55-win32-x64\dist\extension.js:2:162016
	at new Promise (<anonymous>)
	at a.write (c:\Users\r.otten\.vscode\extensions\ms-dotnettools.csdevkit-1.9.55-win32-x64\dist\extension.js:2:161934)
	at i.doWrite (c:\Users\r.otten\.vscode\extensions\ms-dotnettools.csdevkit-1.9.55-win32-x64\dist\extension.js:2:800400)
	at c:\Users\r.otten\.vscode\extensions\ms-dotnettools.csdevkit-1.9.55-win32-x64\dist\extension.js:2:800295
```

No idea if related.

### Steps To Reproduce

No idea what actually exactly triggers this.
VSCode gives me nothing to go off of that might hint to how to build an isolated reproducing case.

At one point things simply broke in a massive way for the solution in question.
(Which works perfectly fine in VS 2022, btw.)

### Expected Behavior

- Not to get 20k+ nonsense errors obscuring the actual warnings and errors in the error panel.
- Not to get 20k+ nonsense errors blinking in and out of existence making navigation in the error panel absolutely impossible

### Environment Information

- OS: Windows
- VS Code Version: 1.92.2
- Extension Version (found in the settings of the extension): ms-dotnettools.csharp-2.39.29

<sub>(PS: Don't use placeholders to show the 'environment information' template's list of items, please. I had to use F12 debug tools to copy and paste out the template, because typing a single character wipes everything else...)</sub>

**Comment by AArnott** [comment]
This isn't my area. This sounds like something the C# or nuget teams should investigate.

**Comment by rjgotten** [comment]
This appears like it might be a duplicate of dotnet/razor#10505

**Comment by rjgotten** [comment]
Question: is there a way to just completely disable the VSCode Razor support while retaining the nominal C# support?
Like a killswitch?

My interest in managing `.cshtml` files via VSCode is basically _zero_ - because the support that's there is, frankly, abysmally broken. The syntax highlighter has tons of issues, the automatic code reformatting makes a mess of things; it causes a spray of nonsense errors all the time - including non-suppressable popup dialogs; etc.

I've taken to just using VS 2022 when I need to work on those.

**Comment by arunchndr** [comment]
@ryzngard would you first scout and pass on to roslyn as needed? 

Apart from root causing the cshtml firing the bugs, which might be more interesting to us in understanding reliability for a bigger cohort, the user is asking for a way to not kick off rzls altogether. Is that doable today?

cc: @dibarbet

**Comment by ryzngard** [comment]
For not starting razor that's not something I think we plan on supporting until we have a compelling reason beyond bugs we have. I can give you an unsupported way with no promises of what this will or won't break: 

you can set this setting which will force the language server to fail to start. It's likely you'll get some error popups. I would go so far as to say if you do this then any bug you file should just be ignored because it is **NOT SUPPORTED** at all.

```
"razor.languageServer.directory": "does/not/exist"
```


Now with that disclaimer out of the way I can say a few things. One, unfortunately VS Code doesn't support pull diagnostics. This means we are forced to push diagnostics at a cadence. As the project engine learns about types, components, etc, it gets updated and should stabilize to not reporting errors. If you are seeing that not happen that is a serious bug. 

We have seen reports for things that have been fixed in this space, such as https://github.com/dotnet/vscode-csharp/issues/6921 . Recent releases should be much better for you. 

The reason you don't see this in VS is because VS supports pull diagnostics. Diagnostics are asked for when you open a file. Type information is already kicked off when the project/solution is opened and it's much more likely you're in a _good_ state when/if you open a cshtml/razor file. 

With that explanation I'm going to close this issue. If you are still hitting this as a major issue please re-open! With testing on larger projects I have seen a vast improvement with `v2.50.25` and higher

**Comment by rjgotten** [comment]
@ryzngard 
Thanks for the explanation on the push vs pull diagnostics.
That explains _so_ much. :+1:
