### ISSUE TITLE
[FreeBSD build of C# Dev Kit]

### ISSUE THREAD

**Issue by AZDeveloper777** [microsoft/vscode-dotnettools#1388]
### Describe the feature you'd like

I'd like to be able to use the C# Dev Kit in VS Code on FreeBSD.

### Alternatives considered

AFAIK, there aren't any alternatives.
If the source was available, I'd port it myself, but since it isn't there isn't much I can do.

### Environment Information

FreeBSD 14.1-RELEASE

**Comment by plainionist** [comment]
i was able to install the extension by downloading the vsix and installing it through "install from vsix" but during extension load i get

rror: Unsupported platform: freebsd
	at l.<anonymous> (/usr/home/seb/.vscode-oss/extensions/ms-dotnettools.csharp-2.46.32/dist/extension.js:2:1589799)
	at Generator.next (<anonymous>)
	at /usr/home/seb/.vscode-oss/extensions/ms-dotnettools.csharp-2.46.32/dist/extension.js:2:1587667
	at new Promise (<anonymous>)
	at r (/usr/home/seb/.vscode-oss/extensions/ms-dotnettools.csharp-2.46.32/dist/extension.js:2:1587412)
	at l.GetCurrent (/usr/home/seb/.vscode-oss/extensions/ms-dotnettools.csharp-2.46.32/dist/extension.js:2:1589480)
	at /usr/home/seb/.vscode-oss/extensions/ms-dotnettools.csharp-2.46.32/dist/extension.js:2:1290724
	at Generator.next (<anonymous>)
	at s (/usr/home/seb/.vscode-oss/extensions/ms-dotnettools.csharp-2.46.32/dist/extension.js:2:1289686)
	
	
Version: 1.90.2
Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
Date: 2024-07-09T07:09:52.346Z
Electron: 29.4.3
ElectronBuildId: undefined
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: FreeBSD x64 14.0-RELEASE-p6

**Comment by AZDeveloper777** [comment]
Since the source is JavaScript, I wonder if it is as simple as commenting out the code that checks for unsupported platforms.

**Comment by plainionist** [comment]
thought the same but the code included in VsCode is "minimized" and "obfuscated" 😒

**Comment by AZDeveloper777** [comment]
> thought the same but the code included in VsCode is "minimized" and "obfuscated" 😒

I found the function that would need to be changed in extension.js  
In addition to being minimized and obfuscated, it is "signed" so that if there are any alterations, it won't function.
I appreciate Microsoft thinking of our security, but if I'm willing to risk borking my system by making changes to the code, I should be able to make those changes.
