### ISSUE TITLE
[BUG] .NET version 6.0.425 error 

### ISSUE THREAD

**Issue by kojhack** [microsoft/vscode-dotnettools#1428]
### Describe the Issue

An error occurred while installing .NET: .NET Acquisition Failed: The distro Ubuntu 20.04 does not officially support dotnet version 6.0.425., Error: The distro Ubuntu 20.04 does not officially support dotnet version 6.0.425.
    at t.LinuxVersionResolver.next (/home/codespace/.vscode-remote/extensions/vscode-dotnet-runtime-library/dist/Acquisition/LinuxVersionResolver.js:235:23)
    at Generator.next (<anonymous>)
    at s (/home/codespace/.vscode-remote/extensions/vscode-dotnet-runtime-library/dist/Acquisition/LinuxVersionResolver.js:5:58)

**Comment by nagilson** [comment]
May you download .NET 8 or 7 instead? This is unfortunately the case with the way .NET installs work on this version of Ubuntu. You can manually install 6 with a more complicated process if you need 6. 

https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu
