### ISSUE TITLE
[BUG] Projects error when opening Roslyn

### ISSUE THREAD

**Issue by 333fred** [microsoft/vscode-dotnettools#146]
### Describe the Issue

I'm seeing an error in the `Projects` output window when opening roslyn that, AFAICT, doesn't have any actual impact, but is there nonethless. /cc @tmeschter.

### Steps To Reproduce

Open Roslyn.sln.

### Expected Behavior

No errors in the `Projects` output window. I actually see:

```
2023-06-14 14:36:16.482 [error] (/home/fred/git/roslyn/src/VisualStudio/DevKit/Impl/Microsoft.VisualStudio.LanguageServices.DevKit.csproj): The "GetAssemblyAttributes" task failed unexpectedly.
System.IO.FileNotFoundException: /home/fred/git/roslyn/artifacts/obj/Microsoft.VisualStudio.LanguageServices.DevKit/Debug/net7.0/Microsoft.VisualStudio.LanguageServices.DevKit.dll
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at Microsoft.NET.Build.Tasks.GetAssemblyAttributes.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
2023-06-14 14:36:22.558 [info] Project system initialization finished. 192 project(s) are loaded, and 0 failed to load.
```

### Environment Information

DevKit v0.2.53-g9b52ab8917

**Comment by tmeschter** [comment]
@333fred Are you still seeing this issue?

**Comment by 333fred** [comment]
I haven't seen this in a while.

**Comment by kvenkatrajan** [comment]
Closing. Please let us know to reopen if issue is encountered in the future.
