### ISSUE TITLE
System.InvalidOperationException: There is no project properties provider for "Persistence = ProjectFileWithInterception".

### ISSUE THREAD

**Issue by RickKra** [microsoft/vscode-dotnettools#1506]
Type: <b>Bug</b>

Cloned https://dev.azure.com/mseng/Domino/_git/CloudBuild and then opened in VS Code. Received popup with path to log containing this text:

=====================
10/2/2024 1:56:56 PM
LimitedFunctionality
System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'path1'))
---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectDirectoryTreeSubscriptionService.IsFileSystemCaseSensitiveForFolder(String folderPath)
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectDirectoryTreeSubscriptionService.SubscribeDirectoryTreeProvider(String absolutePath)
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectDirectoryGlobTreesSnapshotProvider.UpdateGlobSubscriptions(IProjectVersionedValue`1 projectSnapshotValue)
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectDirectoryGlobTreesSnapshotProvider.<LinkExternalInput>b__15_0(IProjectVersionedValue`1 snapshot)
   at Microsoft.VisualStudio.ProjectSystem.TransformBlockSlim`2.TransformBlockSlimSync.ProcessInputAsync(TInput input)
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.ProcessInputQueueAsync(InputDataBuffer inputQueue)
<--- (Inner Exception #0) 
===================
10/2/2024 1:56:56 PM
LimitedFunctionality
System.AggregateException: Project system data flow 'ProjectDirectoryGlobTreesSnapshotProvider: 38384222' closed because of an exception.
Value cannot be null. (Parameter 'path1') (Value cannot be null. (Parameter 'path1'))
---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectDirectoryTreeSubscriptionService.IsFileSystemCaseSensitiveForFolder(String folderPath)
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectDirectoryTreeSubscriptionService.SubscribeDirectoryTreeProvider(String absolutePath)
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectDirectoryGlobTreesSnapshotProvider.UpdateGlobSubscriptions(IProjectVersionedValue`1 projectSnapshotValue)
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectDirectoryGlobTreesSnapshotProvider.<LinkExternalInput>b__15_0(IProjectVersionedValue`1 snapshot)
   at Microsoft.VisualStudio.ProjectSystem.TransformBlockSlim`2.TransformBlockSlimSync.ProcessInputAsync(TInput input)
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.ProcessInputQueueAsync(InputDataBuffer inputQueue)
<--- (Inner Exception #0) 
===================
10/2/2024 1:57:01 PM
LimitedFunctionality
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.ProjectSystem.Server.ProjectLaunchConfigurationService.<InitializeCoreAsync>g__ActionBlockCallback|25_0(IProjectVersionedValue`1 data)
   at Microsoft.VisualStudio.ProjectSystem.ActionBlockSlimSync`1.ProcessInputAsync(TInput input)
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.ProcessInputQueueAsync(InputDataBuffer inputQueue)
<--- (Inner Exception #0) 
===================
10/2/2024 1:57:12 PM
LimitedFunctionality
System.InvalidOperationException: There is no project properties provider for "Persistence = ProjectFileWithInterceptionViaSnapshot".
   at Microsoft.Verify.FailOperation(String message, Object[] args)
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectEvaluationSubscriptionService.BuildPropertiesSnapshot(Rule schema, IProjectSnapshot projectSnapshot, ImmutableDictionary`2 previousVersion, IImmutableSet`1& changedProperties)
===================
10/2/2024 1:57:12 PM
LimitedFunctionality
System.InvalidOperationException: There is no project properties provider for "Persistence = ProjectFileWithInterceptionViaSnapshot".
   at Microsoft.Verify.FailOperation(String message, Object[] args)
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectEvaluationSubscriptionService.BuildPropertiesSnapshot(Rule schema, IProjectSnapshot projectSnapshot, ImmutableDictionary`2 previousVersion, IImmutableSet`1& changedProperties)
===================
10/2/2024 1:57:12 PM
LimitedFunctionality
System.InvalidOperationException: There is no project properties provider for "Persistence = ProjectFileWithInterception".
   at Microsoft.Verify.FailOperation(String message, Object[] args)
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectEvaluationSubscriptionService.BuildPropertiesSnapshot(Rule schema, IProjectSnapshot projectSnapshot, ImmutableDictionary`2 previousVersion, IImmutableSet`1& changedProperties)
===================
10/2/2024 1:57:12 PM
LimitedFunctionality
System.InvalidOperationException: There is no project properties provider for "Persistence = ProjectFileWithInterception".
   at Microsoft.Verify.FailOperation(String message, Object[] args)
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectEvaluationSubscriptionService.BuildPropertiesSnapshot(Rule schema, IProjectSnapshot projectSnapshot, ImmutableDictionary`2 previousVersion, IImmutableSet`1& changedProperties)
===================
10/2/2024 1:57:27 PM
LimitedFunctionality
System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'path1'))
---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectDirectoryTreeSubscriptionService.IsFileSystemCaseSensitiveForFolder(String folderPath)
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectDirectoryGlobTreesSnapshotProvider.UpdateGlobSubscriptions(IProjectVersionedValue`1 projectSnapshotValue)
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectDirectoryGlobTreesSnapshotProvider.<LinkExternalInput>b__15_0(IProjectVersionedValue`1 snapshot)
   at Microsoft.VisualStudio.ProjectSystem.TransformBlockSlim`2.TransformBlockSlimSync.ProcessInputAsync(TInput input)
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.ProcessInputQueueAsync(InputDataBuffer inputQueue)
<--- (Inner Exception #0) 
===================
10/2/2024 1:57:28 PM
LimitedFunctionality
System.InvalidOperationException: There is no project properties provider for "Persistence = ProjectFileWithInterceptionViaSnapshot".
   at Microsoft.Verify.FailOperation(String message, Object[] args)
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectEvaluationSubscriptionService.BuildPropertiesSnapshot(Rule schema, IProjectSnapshot projectSnapshot, ImmutableDictionary`2 previousVersion, IImmutableSet`1& changedProperties)
===================
10/2/2024 1:57:28 PM
LimitedFunctionality
System.InvalidOperationException: There is no project properties provider for "Persistence = ProjectFileWithInterceptionViaSnapshot".
   at Microsoft.Verify.FailOperation(String message, Object[] args)
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectEvaluationSubscriptionService.BuildPropertiesSnapshot(Rule schema, IProjectSnapshot projectSnapshot, ImmutableDictionary`2 previousVersion, IImmutableSet`1& changedProperties)
===================
10/2/2024 1:57:28 PM
LimitedFunctionality
System.InvalidOperationException: There is no project properties provider for "Persistence = ProjectFileWithInterception".
   at Microsoft.Verify.FailOperation(String message, Object[] args)
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectEvaluationSubscriptionService.BuildPropertiesSnapshot(Rule schema, IProjectSnapshot projectSnapshot, ImmutableDictionary`2 previousVersion, IImmutableSet`1& changedProperties)
===================
10/2/2024 1:57:28 PM
LimitedFunctionality
System.InvalidOperationException: There is no project properties provider for "Persistence = ProjectFileWithInterception".
   at Microsoft.Verify.FailOperation(String message, Object[] args)
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectEvaluationSubscriptionService.BuildPropertiesSnapshot(Rule schema, IProjectSnapshot projectSnapshot, ImmutableDictionary`2 previousVersion, IImmutableSet`1& changedProperties)
===================

Extension version: 1.10.18
VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD EPYC 7763 64-Core Processor                 (16 x 2445)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.95GB (37.35GB free)|
|Process Argv|--crash-reporter-id 7ed6e29c-2a14-4768-a7ff-b8591f75b88c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
nativeloc2:31134642
wkspc-ranged-t:31125599
cf971741:31144450
autoexpandse:31146404
iacca1:31150322
notype1cf:31150298
5fd0e150:31146321

```

</details>

**Comment by lifengl** [comment]
@drewnoakes : this issue actually happened earlier, but ignored earlier.

**Comment by lifengl** [comment]
fix merged in, should be in a later release.
