### ISSUE TITLE
Error loading .net maui sln 

### ISSUE THREAD

**Issue by rmarinho** [microsoft/vscode-dotnettools#1519]
Type: <b>Bug</b>

=====================
09/10/2024 13:56:22
LimitedFunctionality
System.AggregateException: Project system data flow 'DataflowBlockSlim (ActionBlockSlimSync`1 : 23787684)' closed because of an exception: One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (Value cannot be null. (Parameter 'second'))))))))))))))))). (Value cannot be null. (Parameter 'second'))
---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null. (Parameter 'second')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Except[TSource](IEnumerable`1 first, IEnumerable`1 second)
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectBuildSnapshotService.ProcessPendingUpdatingSnapshotAsync(IProjectVersionedValue`1 source, IEnumerable`1 subscriptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.CustomizableBlockSubscriberBase`3.<Initialize>b__28_1(TSource s)
   at Microsoft.VisualStudio.ProjectSystem.TransformBlockSlim`2.TransformBlockSlimAsync.ProcessInputAsync(TInput input)
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.ProcessInputQueueAsync(InputDataBuffer inputQueue)
<--- (Inner Exception #0) 
===================
09/10/2024 13:56:22
LimitedFunctionality
System.AggregateException: Project system data flow 'ProjectBuildSubscriptionService' closed because of an exception.
Value cannot be null. (Parameter 'second') (Value cannot be null. (Parameter 'second'))
---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null. (Parameter 'second')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Except[TSource](IEnumerable`1 first, IEnumerable`1 second)
   at Microsoft.VisualStudio.ProjectSystem.Designers.ProjectBuildSnapshotService.ProcessPendingUpdatingSnapshotAsync(IProjectVersionedValue`1 source, IEnumerable`1 subscriptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.CustomizableBlockSubscriberBase`3.<Initialize>b__28_1(TSource s)
   at Microsoft.VisualStudio.ProjectSystem.TransformBlockSlim`2.TransformBlockSlimAsync.ProcessInputAsync(TInput input)
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.ProcessInputQueueAsync(InputDataBuffer inputQueue)
<--- (Inner Exception #0) 
===================

Extension version: 1.12.2
VS Code version: Code 1.94.1 (Universal) (e10f2369d0d9614a452462f2e01cdc4aa9486296, 2024-10-05T05:44:32.189Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|7, 7, 5|
|Memory (System)|36.00GB (0.32GB free)|
|Process Argv|./maui.code-workspace --crash-reporter-id 965577f0-b8c5-4316-83db-6df42abadaac|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca1:31150322
notype1:31151523
cc771715:31146322

```

</details>

**Comment by emaf** [comment]
@rmarinho what version of the MAUI Dev Kit extension are you using?

**Comment by rmarinho** [comment]
v1.12.2 (pre-release)

**Comment by emaf** [comment]
@rmarinho that's the C# Dev Kit version, we also need to know what's the .NET MAUI extension version you are running.

**Comment by mauroa** [comment]
@rmarinho are you still reproducing this issue? Can you update to latest .NET MAUI and C# DevKit pre-release versions and let us know? Thanks

**Comment by emaf** [comment]
Closing as there is not enough information to investigate this.
