### ISSUE TITLE
[BUG] projects loading partial failure

### ISSUE THREAD

**Issue by baywet** [microsoft/vscode-dotnettools#1556]
### Describe the Issue

Getting the following error message:

```
10/24/2024 8:52:22 AM
LimitedFunctionality
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.VisualStudio.ProjectSystem.Server.ProjectLaunchConfigurationService.g__ActionBlockCallback|25_1(IProjectVersionedValue1 data) at Microsoft.VisualStudio.ProjectSystem.ActionBlockSlimSync1.ProcessInputAsync(TInput input)
at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.ProcessInputQueueAsync(InputDataBuffer inputQueue)
<--- (Inner Exception #1179 
```

### Steps To Reproduce

1. clone https://github.com/microsoft/semantic-kernel (main/f414fcd2fe03d0cdf93ec6d2022ce97d6b22d45f)
2. Open VSCode with the dev kit installed

### Expected Behavior

The dev kit not to fail when opening the repo.

### Environment Information

All details here as I originally opened from VSCode report a bug. https://github.com/microsoft/vscode/issues/232138

**Comment by NerdsRule** [comment]
Getting same error. Running latest Mac OS. Repo is private. 
```
=====================
25/10/2024 06:40:10
LimitedFunctionality
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.ProjectSystem.Server.ProjectLaunchConfigurationService.<InitializeCoreAsync>g__ActionBlockCallback|25_1(IProjectVersionedValue`1 data)
   at Microsoft.VisualStudio.ProjectSystem.ActionBlockSlimSync`1.ProcessInputAsync(TInput input)
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.ProcessInputQueueAsync(InputDataBuffer inputQueue)
<--- (Inner Exception #0) 
===================
```
