### ISSUE TITLE
[BUG] NullReferenceException in project launch system

### ISSUE THREAD

**Issue by rmunn** [microsoft/vscode-dotnettools#1599]
### Describe the Issue

VS Code just popped up a message saying something like "Project launch system had an error. Please report this to the dev team." Sorry I didn't think to copy the error text before dismissing it, so that's from memory and probably not exact.

When I dismissed the error, the following text appeared in a new VS Code tab:

```
=====================
11/12/2024 10:46:30 AM
LimitedFunctionality
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.ProjectSystem.Server.ProjectLaunchConfigurationService.<InitializeCoreAsync>g__ActionBlockCallback|25_1(IProjectVersionedValue`1 data)
   at Microsoft.VisualStudio.ProjectSystem.ActionBlockSlimSync`1.ProcessInputAsync(TInput input)
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.ProcessInputQueueAsync(InputDataBuffer inputQueue)
<--- (Inner Exception #0) 
===================
```

### Steps To Reproduce

Might have trouble reproducing this, as it's probably a timing-dependent race condition of some kind. But I had two C# projects open in two different VS Code windows. In one of them, I clicked "Close All", closing 20+ .cs files, then immediately closed that VS Code window. I then Alt-Tabbed over to the other VS Code window where my other C# project was loaded, and this error popped up.

### Expected Behavior

No NullReferenceExceptions would be thrown.

### Environment Information

- OS: Linux
- VS Code Version: 1.95.2
- Extension version: ms-dotnettools.csdevkit v1.11.14

**Comment by JakeRadMSFT** [comment]
We were unable to reproduce this. Can you help provide more repro steps and re-open if you're still hitting this.
