### ISSUE TITLE
Test diffing is broken

### ISSUE THREAD

**Issue by 333fred** [microsoft/vscode-dotnettools#1604]
Type: <b>Bug</b>

There's some new test output auto-diffing feature that is rendering the test output window entirely useless for Roslyn. The actual test output from the log is:

```
[xUnit.net 00:00:00.43]   Starting:    Microsoft.CodeAnalysis.CSharp.Emit3.UnitTests
[xUnit.net 00:00:01.10]     Microsoft.CodeAnalysis.CSharp.Test.OverloadResolutionPriorityTests.ExtensionsOnlyFilteredByApplicability [FAIL]
[xUnit.net 00:00:01.10]       
[xUnit.net 00:00:01.10]       Expected:
[xUnit.net 00:00:01.10]       Actual:
[xUnit.net 00:00:01.10]                       // (9,11): error CS0121: The call is ambiguous between the following methods or properties: 'E1.R(int)' and 'E2.R(int)'
[xUnit.net 00:00:01.11]                       //         x.R(); // E1.R(int)
[xUnit.net 00:00:01.11]                       Diagnostic(ErrorCode.ERR_AmbigCall, "R").WithArguments("E1.R(int)", "E2.R(int)").WithLocation(9, 11)
[xUnit.net 00:00:01.11]       Diff:
[xUnit.net 00:00:01.11]       ++>                 Diagnostic(ErrorCode.ERR_AmbigCall, "R").WithArguments("E1.R(int)", "E2.R(int)").WithLocation(9, 11)
[xUnit.net 00:00:01.11]       Stack Trace:
[xUnit.net 00:00:01.11]         /home/fred/git/roslyn/src/Compilers/Test/Core/Diagnostics/DiagnosticExtensions.cs(99,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected, Boolean errorCodeOnly)
[xUnit.net 00:00:01.11]         /home/fred/git/roslyn/src/Compilers/Test/Core/Diagnostics/DiagnosticExtensions.cs(48,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected)
[xUnit.net 00:00:01.11]         /home/fred/git/roslyn/src/Compilers/Test/Core/Diagnostics/DiagnosticExtensions.cs(63,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(ImmutableArray`1 actual, DiagnosticDescription[] expected)
[xUnit.net 00:00:01.11]         /home/fred/git/roslyn/src/Compilers/Test/Core/Diagnostics/DiagnosticExtensions.cs(109,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.VerifyDiagnostics[TCompilation](TCompilation c, DiagnosticDescription[] expected)
[xUnit.net 00:00:01.11]         /home/fred/git/roslyn/src/Compilers/CSharp/Test/Emit3/OverloadResolutionPriorityTests.cs(2635,0): at Microsoft.CodeAnalysis.CSharp.Test.OverloadResolutionPriorityTests.ExtensionsOnlyFilteredByApplicability()
[xUnit.net 00:00:01.11]            at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
[xUnit.net 00:00:01.11]            at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
[xUnit.net 00:00:01.11]   Finished:    Microsoft.CodeAnalysis.CSharp.Emit3.UnitTests
```

However, the test results window doesn't the full output anymore. It just shows the first line of the comment; the error text here tells me exactly what I need to copy into the test file, and it's very important that it shows exactly as it was produced.

This is what I see, which is just useless to me. I end up needing to go into the raw test output to retrieve the real message.
![Image](https://github.com/user-attachments/assets/148e2bc3-9742-4fc2-a3b6-4cf9a01eeabb)

Extension version: 1.13.6
VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Linux x64 5.15.0-124-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor (32 x 2667)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 3, 4|
|Memory (System)|62.70GB (30.99GB free)|
|Process Argv|. --crash-reporter-id c9f05a69-d019-464b-b1f2-b43e5fb75046|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|regolith|
|XDG_CURRENT_DESKTOP|Regolith:GNOME-Flashback:GNOME|
|XDG_SESSION_DESKTOP|regolith|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc1:31134641
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
j44ff735:31179530

```

</details>

**Comment by peterwald** [comment]
cc @ocallesp

**Comment by AbhitejJohn** [comment]
@ocallesp : Is there a way of turning off the new diff view for results? There's got to be a VSCode setting for this.

**Comment by ocallesp** [comment]
WIP. Fix in code review

**Comment by ocallesp** [comment]
Fix was merged today. It should be available in the next release

**Comment by AbhitejJohn** [comment]
@ocallesp : Can you also share a little more context on the fix? Possibly a screenshot for the scenario above with the fix.

**Comment by 333fred** [comment]
Some of the output seems to be fixed, but I'm still seeing some bad behavior. For example, commenting out [this](https://github.com/dotnet/roslyn/blob/704e4225b2a581caaa80de562df78d1090344e31/src/Compilers/CSharp/Test/Symbol/Symbols/RequiredMembersTests.cs#L7200) line and running the containing test, the output is still bad.

![Image](https://github.com/user-attachments/assets/5223e515-6161-4ed2-8936-5b83b194337a)
```
[xUnit.net 00:00:00.53]   Starting:    Microsoft.CodeAnalysis.CSharp.Symbol.UnitTests
[xUnit.net 00:00:01.33]     Microsoft.CodeAnalysis.CSharp.UnitTests.Symbols.RequiredMembersTests.CycleOnConstructorAppliedToSelf [FAIL]
[xUnit.net 00:00:01.33]       
[xUnit.net 00:00:01.33]       Expected:
[xUnit.net 00:00:01.33]                       Diagnostic(ErrorCode.ERR_AttributeOnBadSymbolType, "Conditional").WithArguments("Conditional", "class, method").WithLocation(6, 6)
[xUnit.net 00:00:01.33]       Actual:
[xUnit.net 00:00:01.33]                       // (6,6): warning CS0436: The type 'ConditionalAttribute' in '' conflicts with the imported type 'ConditionalAttribute' in 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Using the type defined in ''.
[xUnit.net 00:00:01.33]                       //     [Conditional("blah")]
[xUnit.net 00:00:01.33]                       Diagnostic(ErrorCode.WRN_SameFullNameThisAggAgg, "Conditional").WithArguments("", "System.Diagnostics.ConditionalAttribute", "netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51", "System.Diagnostics.ConditionalAttribute").WithLocation(6, 6),
[xUnit.net 00:00:01.33]                       // (6,6): error CS0592: Attribute 'Conditional' is not valid on this declaration type. It is only valid on 'class, method' declarations.
[xUnit.net 00:00:01.33]                       //     [Conditional("blah")]
[xUnit.net 00:00:01.33]                       Diagnostic(ErrorCode.ERR_AttributeOnBadSymbolType, "Conditional").WithArguments("Conditional", "class, method").WithLocation(6, 6)
[xUnit.net 00:00:01.33]       Diff:
[xUnit.net 00:00:01.33]       ++>                 Diagnostic(ErrorCode.WRN_SameFullNameThisAggAgg, "Conditional").WithArguments("", "System.Diagnostics.ConditionalAttribute", "netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51", "System.Diagnostics.ConditionalAttribute").WithLocation(6, 6)
[xUnit.net 00:00:01.33]       Stack Trace:
[xUnit.net 00:00:01.33]         /home/fred/git/roslyn/src/Compilers/Test/Core/Diagnostics/DiagnosticExtensions.cs(99,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected, Boolean errorCodeOnly)
[xUnit.net 00:00:01.33]         /home/fred/git/roslyn/src/Compilers/Test/Core/Diagnostics/DiagnosticExtensions.cs(48,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected)
[xUnit.net 00:00:01.33]         /home/fred/git/roslyn/src/Compilers/Test/Core/Diagnostics/DiagnosticExtensions.cs(63,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(ImmutableArray`1 actual, DiagnosticDescription[] expected)
[xUnit.net 00:00:01.33]         /home/fred/git/roslyn/src/Compilers/Test/Core/Diagnostics/DiagnosticExtensions.cs(356,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.VerifyEmitDiagnostics[TCompilation](TCompilation c, EmitOptions options, DiagnosticDescription[] expected)
[xUnit.net 00:00:01.33]         /home/fred/git/roslyn/src/Compilers/Test/Core/Diagnostics/DiagnosticExtensions.cs(373,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.VerifyEmitDiagnostics[TCompilation](TCompilation c, DiagnosticDescription[] expected)
[xUnit.net 00:00:01.33]         /home/fred/git/roslyn/src/Compilers/CSharp/Test/Symbol/Symbols/RequiredMembersTests.cs(7197,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.Symbols.RequiredMembersTests.CycleOnConstructorAppliedToSelf()
[xUnit.net 00:00:01.33]            at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
[xUnit.net 00:00:01.33]            at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by AbhitejJohn** [comment]
@ocallesp : Thoughts on the above?

**Comment by ocallesp** [comment]
There is a new option in Settings to enable/disable this Diff

![Image](https://github.com/user-attachments/assets/3db68ba3-3d07-4298-b249-9a779b2e6890)

**Comment by ocallesp** [comment]
A fix was submitted and partially fixed the previous error. 

I need to first validate this new error scenario.

**Comment by AbhitejJohn** [comment]
@ocallesp : Is there an issue tracking that other fix or are we using this? If we are using this, we would probably not want to say "fixed-pending-release" on it because the fix isn't complete.

**Comment by TheFurnace** [comment]
As of version 1.16.6 Test diffing is still broken and there is no option to disable

**Comment by ocallesp** [comment]
@TheFurnace There is an Option in Setting that allows to enable/disable Diff

![Image](https://github.com/user-attachments/assets/984995e6-0e3e-41f6-a362-7f51acfe7726)

**Comment by Werebunny** [comment]
The option does not show up in the release version 1.16.6, it does show up in pre-release version 1.17.27. 

It should be disabled by default as it's a broken feature. See here: 

> If they ever change how their messages are structured, it could break our Diff.

This is an incredibly bad practice, for everyone involved.

Developers of the chosen few frameworks are now beholden to an external project. A seemingly innocuous change will break their user's workflows. It'd be one thing if it was just some random other project doing something they shouldn't be doing, but this is official Microsoft tooling for a mainstream IDE. If they want to make a change they have to sync up with this project now? That's a huge ask for everyone involved, for really no reason.

Other projects are simply left behind/broken. I'm supposed to tell my users (hah, if I had any, but let's pretend) they have to disable an IDE option because Microsoft broke my framework by playing favorites? It's bad enough that this "feature" broke developer workflows for nearly half a year (including my bug case here #1688), but the "solution" is to simply ignore that it's breaking others by default?

Why is it co-opting my framework's exceptions to begin with? It's an undocumented feature that's apparently parsing exceptions blindly. If you want to make a fancy thing for those chosen frameworks, then the base thing that should be done is to ensure the exceptions are coming from those chosen frameworks. But that also misses the mark a bit, because I should have some way to opt in to the feature that's not automatic, shouldn't I? To make my framework compatible, like adding an attribute or something. Then I'm not penalized for not being a popular favorite while having control if I want part of this feature.

Who even asked for a "feature" that hides test/debug information from developers really? When something goes wrong, I want all the information, not for my IDE to decide what I should see and what is irrelevant (and failing at it to boot). There should absolutely be an option to view the raw full exception even with this feature enabled. Thus the feature should not be enabled by default until that's the case at the very bare minimum.

**Comment by Werebunny** [comment]
I should make sure to clarify, this bug still exists in 1.17.27, although the workaround is appreciated.

**Comment by ocallesp** [comment]
These fixes should be included in pre-release version v1.17.48.
