### ISSUE TITLE
[BUG] Error running command csdevkit.addNewFile: The type initializer for 'HostData' threw an exception.

### ISSUE THREAD

**Issue by jorgelaranjo** [microsoft/vscode-dotnettools#1689]
### Describe the Issue

I can't add files from solution explorer from a simple project. Gives me this error:

`Error running command csdevkit.addNewFile: The type initializer for 'HostData' threw an exception.. This is likely caused by the extension that contributes csdevkit.addNewFile.`

### Expected Behavior

Creates file

### Environment Information

* **VSCode**: 1.95.3
* **OS**: 6.12.1-arch1-1
* **SDK**: 8.0.110
* **csdevkit** v1.14.14
Project is on Dotnet 8.0

Seems similar to #1000

**Comment by Michael-Eng** [comment]
@JakeRadMSFT can you take a look - could it be related to the template engine?

**Comment by jorgelaranjo** [comment]
Log is

```log
2024-12-17 11:38:23.606 [error] Error: The type initializer for '**HostData**' threw an exception.
    at ~/.vscode/extensions/ms-dotnettools.csdevkit-1.14.14-linux-x64/dist/extension.js:2:831486
    at ne (~/.vscode/extensions/ms-dotnettools.csdevkit-1.14.14-linux-x64/dist/extension.js:2:831780)
    at ~/.vscode/extensions/ms-dotnettools.csdevkit-1.14.14-linux-x64/dist/extension.js:2:826564
    at Immediate.<anonymous> (~/.vscode/extensions/ms-dotnettools.csdevkit-1.14.14-linux-x64/dist/extension.js:2:826584)
    at processImmediate (node:internal/timers:483:21) csdevkit.addNewFile {"value":"ms-dotnettools.csdevkit","_lower":"ms-dotnettools.csdevkit"}

```

However
`File > New File... > .NET: New File...`

Creates
```csharp
namespace ConsoleApp1;

public class Class1
{
    
}
```

**Comment by LittleLittleCloud** [comment]
@jorgelaranjo Sorry I can't reproduce this bug on my end, would you mind sharing more details on how to reproduce this issue.

Regards

**Comment by jorgelaranjo** [comment]
Bug **not present** anymore on latest version

**Version**: 1.96.2 (**1.96.2-1**)
**Commit**: fabdb6a30b49f79a7aba0f2ad9df9b399473380f
**Date**: 2024-12-19T10:22:47.216Z
**Electron**: 32.2.6
**ElectronBuildId**: 10629634
**Chromium**: 128.0.6613.186
**Node.js**: 20.18.1
**V8**: 12.8.374.38-electron.0
**OS:** Linux x64 6.12.4-arch1-1

**Comment by jorgelaranjo** [comment]
Showing again and thus need to find logs to pinpoint root cause. Where would those log be at?
`Error running command csdevkit.addNewFile: The type initializer for 'HostData' threw an exception.. This is likely caused by the extension that contributes csdevkit.addNewFile.`


Changed from Linux x64 6.12.**4**-arch1-1 to OS: Linux x64 6.12.**6**-arch1-1
```
Version: 1.96.2
Commit: fabdb6a30b49f79a7aba0f2ad9df9b399473380f
Date: 2024-12-19T10:22:47.216Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Linux x64 6.12.**6**-arch1-1
```

**Comment by jorgelaranjo** [comment]
Additional log

```
2024-12-31 11:26:54.493 [info] Using dotnet configured on PATH
2024-12-31 11:26:54.494 [info] Dotnet path: /usr/share/dotnet/dotnet
2024-12-31 11:26:54.494 [info] Activating C# + C# Dev Kit...
2024-12-31 11:26:58.469 [info] [stdout] {"pipeName":"/tmp/8b81eeaa.sock"}

2024-12-31 11:26:58.469 [info] received named pipe information from server
2024-12-31 11:26:59.166 [info] client has connected to server
2024-12-31 11:26:59.387 [info] [Info  - 11:26:59] [Program] Language server initialized
2024-12-31 11:27:00.122 [info] [Warn  - 11:27:00] [LanguageServerHost] Culture en was not found, falling back to OS culture
```

**Comment by jorgelaranjo** [comment]
**Root Cause:**  
The issue occurred because `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT` was set to `1`, disabling full globalization support.

**Resolution:**  
Unset `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT` or set it to `0` to enable proper functionality.
