### ISSUE TITLE
Log full of errors, cannot use

### ISSUE THREAD

**Issue by jtsom** [microsoft/vscode-dotnettools#170]
Type: <b>Bug</b>

The developer tools log is full of errors from the new C# extensions, and it is unusable. Intellicode does not work, reporting errors where there aren't any, etc. I would post the error log but it is too large. Here is a small sample:

```
 ERR MainThreadFileSystem#$watch(): failed to stat a resource for file watching (extension: ms-dotnettools.csharp, path: d:\source\repos\company.Audit\company.Audit.DataAccess\, recursive: true, session: 0.8889823638932173): Error: Unable to resolve filesystem provider with relative file path 'd:\source\repos\company.Audit\company.Audit.DataAccess\'
log.ts:441   ERR Error: Unable to resolve filesystem provider with relative file path 'd:\source\repos\company.Audit\company.Audit.DataAccess\'
    at e.$Uo.j (fileService.ts:131:10)
    at e.$Uo.W (fileService.ts:1110:31)
    at fileService.ts:1095:35
    at e.$Uo.watch (fileService.ts:1104:3)
    at s.$watch (mainThreadFileSystem.ts:250:42)
log.ts:441   ERR MainThreadFileSystem#$watch(): failed to stat a resource for file watching (extension: ms-dotnettools.csharp, path: d:\source\repos\company.Audit\company.Infrastructure\company.Core\company.Core\, recursive: true, session: 0.31527665431695917): Error: Unable to resolve filesystem provider with relative file path 'd:\source\repos\company.Audit\company.Infrastructure\company.Core\company.Core\'
log.ts:441   ERR Error: Unable to resolve filesystem provider with relative file path 'd:\source\repos\company.Audit\company.Infrastructure\company.Core\company.Core\'
    at e.$Uo.j (fileService.ts:131:10)
    at e.$Uo.W (fileService.ts:1110:31)
    at fileService.ts:1095:35
    at e.$Uo.watch (fileService.ts:1104:3)
    at s.$watch (mainThreadFileSystem.ts:250:42)
log.ts:441   ERR MainThreadFileSystem#$watch(): failed to stat a resource for file watching (extension: ms-dotnettools.csharp, path: d:\source\repos\company.Audit\company.Infrastructure\DigitalOptometrcis.Queries.Core\, recursive: true, session: 0.06423337911906923): Error: Unable to resolve filesystem provider with relative file path 'd:\source\repos\company.Audit\company.Infrastructure\DigitalOptometrcis.Queries.Core\'
log.ts:441   ERR Error: Unable to resolve filesystem provider with relative file path 'd:\source\repos\company.Audit\company.Infrastructure\DigitalOptometrcis.Queries.Core\'
    at e.$Uo.j (fileService.ts:131:10)
    at e.$Uo.W (fileService.ts:1110:31)
    at fileService.ts:1095:35
    at e.$Uo.watch (fileService.ts:1104:3)
    at s.$watch (mainThreadFileSystem.ts:250:42)
log.ts:441   ERR MainThreadFileSystem#$watch(): failed to stat a resource for file watching (extension: ms-dotnettools.csharp, path: d:\source\repos\company.Audit\company.Audit.Queries\, recursive: true, session: 0.6303309060624285): Error: Unable to resolve filesystem provider with relative file path 'd:\source\repos\company.Audit\company.Audit.Queries\'
log.ts:441   ERR Error: Unable to resolve filesystem provider with relative file path 'd:\source\repos\company.Audit\company.Audit.Queries\'
    at e.$Uo.j (fileService.ts:131:10)
    at e.$Uo.W (fileService.ts:1110:31)
    at fileService.ts:1095:35
    at e.$Uo.watch (fileService.ts:1104:3)
    at s.$watch (mainThreadFileSystem.ts:250:42)
log.ts:441   ERR MainThreadFileSystem#$watch(): failed to stat a resource for file watching (extension: ms-dotnettools.csharp, path: d:\source\repos\company.Audit\company.Infrastructure\company.Web.Core\, recursive: true, session: 0.5022204153885379): Error: Unable to resolve filesystem provider with relative file path 'd:\source\repos\company.Audit\company.Infrastructure\company.Web.Core\'
log.ts:441   ERR Error: Unable to resolve filesystem provider with relative file path 'd:\source\repos\company.Audit\company.Infrastructure\company.Web.Core\'
    at e.$Uo.j (fileService.ts:131:10)
    at e.$Uo.W (fileService.ts:1110:31)
    at fileService.ts:1095:35
    at e.$Uo.watch (fileService.ts:1104:3)
    at s.$watch (mainThreadFileSystem.ts:250:42)
log.ts:441   ERR MainThreadFileSystem#$watch(): failed to stat a resource for file watching (extension: ms-dotnettools.csharp, path: d:\source\repos\company.Audit\company.Audit.Web\, recursive: true, session: 0.04672839223835856): Error: Unable to resolve filesystem provider with relative file path 'd:\source\repos\company.Audit\company.Audit.Web\'
log.ts:441   ERR Error: Unable to resolve filesystem provider with relative file path 'd:\source\repos\company.Audit\company.Audit.Web\'
    at e.$Uo.j (fileService.ts:131:10)
    at e.$Uo.W (fileService.ts:1110:31)
    at fileService.ts:1095:35
    at e.$Uo.watch (fileService.ts:1104:3)
    at s.$watch (mainThreadFileSystem.ts:250:42)
log.ts:441   ERR Error: Unable to resolve filesystem provider with relative file path 'd:\source\repos\company.Audit'
    at e.$Uo.j (fileService.ts:131:10)
    at e.$Uo.W (fileService.ts:1110:31)
    at fileService.ts:1095:35
    at e.$Uo.watch (fileService.ts:1104:3)
    at s.$watch (mainThreadFileSystem.ts:250:42)
    at b.N (rpcProtocol.ts:455:17)
    at b.M (rpcProtocol.ts:440:32)
    at b.H (rpcProtocol.ts:370:19)
    at b.G (rpcProtocol.ts:296:10)
    at rpcProtocol.ts:161:42
    at g.invoke (event.ts:862:17)
    at r.deliver (event.ts:1075:22)
    at s.fire (event.ts:1031:24)
    at c.fire (ipc.net.ts:650:19)
    at Q.onmessage (localProcessExtensionHost.ts:583:40)
log.ts:441   ERR Error: Unable to resolve filesystem provider with relative file path 'C:\Program Files\dotnet\sdk\7.0.400-preview.23274.1\Sdks\Microsoft.NET.Sdk\analyzers\build\config'
    at e.$Uo.j (fileService.ts:131:10)
    at e.$Uo.W (fileService.ts:1110:31)
    at fileService.ts:1095:35
    at e.$Uo.watch (fileService.ts:1104:3)
    at s.$watch (mainThreadFileSystem.ts:250:42)
    at b.N (rpcProtocol.ts:455:17)
    at b.M (rpcProtocol.ts:440:32)
    at b.H (rpcProtocol.ts:370:19)
    at b.G (rpcProtocol.ts:296:10)
    at rpcProtocol.ts:161:42
    at g.invoke (event.ts:862:17)
    at r.deliver (event.ts:1075:22)
    at s.fire (event.ts:1031:24)
    at c.fire (ipc.net.ts:650:19)
    at Q.onmessage (localProcessExtensionHost.ts:583:40)
log.ts:441   ERR Error: Unable to resolve filesystem provider with relative file path 'd:\source\repos\company.Audit\company.Infrastructure\company.Web.Core\obj\Debug\net7.0'
    at e.$Uo.j (fileService.ts:131:10)
    at e.$Uo.W (fileService.ts:1110:31)
    at fileService.ts:1095:35
    at e.$Uo.watch (fileService.ts:1104:3)
    at s.$watch (mainThreadFileSystem.ts:250:42)
    at b.N (rpcProtocol.ts:455:17)
    at b.M (rpcProtocol.ts:440:32)
    at b.H (rpcProtocol.ts:370:19)
    at b.G (rpcProtocol.ts:296:10)
    at rpcProtocol.ts:161:42
    at g.invoke (event.ts:862:17)
    at r.deliver (event.ts:1075:22)
    at s.fire (event.ts:1031:24)
    at c.fire (ipc.net.ts:650:19)
    at Q.onmessage (localProcessExtensionHost.ts:583:40)
log.ts:441   ERR Error: Unable to resolve filesystem provider with relative file path 'd:\source\repos\company.Audit\company.Infrastructure\company.Web.Core'
    at e.$Uo.j (fileService.ts:131:10)
    at e.$Uo.W (fileService.ts:1110:31)
    at fileService.ts:1095:35
    at e.$Uo.watch (fileService.ts:1104:3)
    at s.$watch (mainThreadFileSystem.ts:250:42)
    at b.N (rpcProtocol.ts:455:17)
    at b.M (rpcProtocol.ts:440:32)
    at b.H (rpcProtocol.ts:370:19)
    at b.G (rpcProtocol.ts:296:10)
    at rpcProtocol.ts:161:42
    at g.invoke (event.ts:862:17)
    at r.deliver (event.ts:1075:22)
    at s.fire (event.ts:1031:24)
    at c.fire (ipc.net.ts:650:19)
    at Q.onmessage (localProcessExtensionHost.ts:583:40)
log.ts:441   ERR Error: Unable to resolve filesystem provider with relative file path 'C:\Program Files\dotnet\sdk\7.0.400-preview.23274.1\Roslyn\bincore'
    at e.$Uo.j (fileService.ts:131:10)
    at e.$Uo.W (fileService.ts:1110:31)
    at fileService.ts:1095:35
    at e.$Uo.watch (fileService.ts:1104:3)
    at s.$watch (mainThreadFileSystem.ts:250:42)
    at b.N (rpcProtocol.ts:455:17)
    at b.M (rpcProtocol.ts:440:32)
    at b.H (rpcProtocol.ts:370:19)
    at b.G (rpcProtocol.ts:296:10)
    at rpcProtocol.ts:161:42
    at g.invoke (event.ts:862:17)
    at r.deliver (event.ts:1075:22)
    at s.fire (event.ts:1031:24)
    at c.fire (ipc.net.ts:650:19)
    at Q.onmessage (localProcessExtensionHost.ts:583:40)
log.ts:441   ERR MainThreadFileSystem#$watch(): failed to stat a resource for file watching (extension: ms-dotnettools.csharp, path: c:\Users\jtsombakos\AppData\Roaming\Code - Insiders\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.7\packs\, recursive: true, session: 0.05038840404856537): Error: Unable to resolve filesystem provider with relative file path 'c:\Users\jtsombakos\AppData\Roaming\Code - Insiders\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.7\packs\'
log.ts:441   ERR Error: Unable to resolve filesystem provider with relative file path 'c:\Users\jtsombakos\AppData\Roaming\Code - Insiders\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.7\packs\'
    at e.$Uo.j (fileService.ts:131:10)
    at e.$Uo.W (fileService.ts:1110:31)
    at fileService.ts:1095:35
    at e.$Uo.watch (fileService.ts:1104:3)
    at s.$watch (mainThreadFileSystem.ts:250:42)
log.ts:441   ERR MainThreadFileSystem#$watch(): failed to stat a resource for file watching (extension: ms-dotnettools.csharp, path: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\, recursive: true, session: 0.12049143538942975): Error: Unable to resolve filesystem provider with relative file path 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\'
log.ts:441   ERR Error: Unable to resolve filesystem provider with relative file path 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\'
    at e.$Uo.j (fileService.ts:131:10)
    at e.$Uo.W (fileService.ts:1110:31)
    at fileService.ts:1095:35
    at e.$Uo.watch (fileService.ts:1104:3)
    at s.$watch (mainThreadFileSystem.ts:250:42)
log.ts:441   ERR MainThreadFileSystem#$watch(): failed to stat a resource for file watching (extension: ms-dotnettools.csharp, path: C:\Program Files\dotnet\packs\, recursive: true, session: 0.6481336019112085): Error: Unable to resolve filesystem provider with relative file path 'C:\Program Files\dotnet\packs\'
log.ts:441   ERR Error: Unable to resolve filesystem provider with relative file path 'C:\Program Files\dotnet\packs\'
    at e.$Uo.j (fileService.ts:131:10)
    at e.$Uo.W (fileService.ts:1110:31)
    at fileService.ts:1095:35
    at e.$Uo.watch (fileService.ts:1104:3)
    at s.$watch (mainThreadFileSystem.ts:250:42)
```

more:
```
  ERR Error: Unable to resolve filesystem provider with relative file path 'C:\Users\jtsombakos\.nuget\packages\microsoft.entityframeworkcore.abstractions\7.0.2\lib\net6.0'
    at e.$Uo.j (fileService.ts:131:10)
    at e.$Uo.W (fileService.ts:1110:31)
    at fileService.ts:1095:35
    at e.$Uo.watch (fileService.ts:1104:3)
    at s.$watch (mainThreadFileSystem.ts:250:42)
    at b.N (rpcProtocol.ts:455:17)
    at b.M (rpcProtocol.ts:440:32)
    at b.H (rpcProtocol.ts:370:19)
    at b.G (rpcProtocol.ts:296:10)
    at rpcProtocol.ts:161:42
    at g.invoke (event.ts:862:17)
    at r.deliver (event.ts:1075:22)
    at s.fire (event.ts:1031:24)
    at c.fire (ipc.net.ts:650:19)
    at Q.onmessage (localProcessExtensionHost.ts:583:40)
log.ts:441   ERR Error: Unable to resolve filesystem provider with relative file path 'C:\Users\jtsombakos\.nuget\packages\system.security.cryptography.protecteddata\5.0.0\ref\netstandard2.0'
    at e.$Uo.j (fileService.ts:131:10)
    at e.$Uo.W (fileService.ts:1110:31)
    at fileService.ts:1095:35
    at e.$Uo.watch (fileService.ts:1104:3)
    at s.$watch (mainThreadFileSystem.ts:250:42)
    at b.N (rpcProtocol.ts:455:17)
    at b.M (rpcProtocol.ts:440:32)
    at b.H (rpcProtocol.ts:370:19)
    at b.G (rpcProtocol.ts:296:10)
    at rpcProtocol.ts:161:42
    at g.invoke (event.ts:862:17)
    at r.deliver (event.ts:1075:22)
    at s.fire (event.ts:1031:24)
    at c.fire (ipc.net.ts:650:19)
    at Q.onmessage (localProcessExtensionHost.ts:583:40)
```

Extension version: 0.1.103
VS Code version: Code - Insiders 1.80.0-insider (73eb619afb87cab4aa83a569259c891b6983c11e, 2023-06-19T05:35:37.388Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (13.55GB free)|
|Process Argv|--crash-reporter-id 362817d9-b661-4b35-92b7-fe18e5872851|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263cf:30763247
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
vscrp:30624060
pythonsymbol12:30651887
a9j8j154:30646983
showlangstatbar:30737417
pythonms35:30671666
03d35959:30757351
ecj1e332:30687743
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30724385
showindicator:30766888
pythongtdpath:30726887
bgfeh915:30769767
gsof2:30767485
dh2dc718:30770000
pythonidxpt:30768918
pythondjangots:30768917
pythonnocebcf:30766856
copilotsettingt:30767686
e537b577:30769889

```

</details>

**Comment by arkalyanms** [comment]
@jasonmalinowski feel free to move it to vscode-csharp when ready. Leaving it here to continue the discussion for now.

**Comment by jtsom** [comment]
I tried just updating the C# extension to the preview version, and it has all sorts of issues with "go to reference", coloring not correct, console errors.

**Comment by jtsom** [comment]
When will this fix be released? I just reinstalled the C# dev kit, and associated C# extension and the problem persists.

**Comment by dibarbet** [comment]
This fix will be in next weeks release - it will fix the console log errors, however I'm not so certain it will fix issues with go to def / coloring.  That is likely a separate issue.

If you wouldn't mind sharing your extensions log folder (can find it here with this command
![image](https://github.com/microsoft/vscode-dotnettools/assets/5749229/ec6de647-b5a9-4409-9b99-a0dd48bc9ebb) ) I should be able to tell if it is the same issue.

Most importantly I'm interested in the C# / C# Dev Kit / and Projects output window logs.

**Comment by jtsom** [comment]
[exthost.zip](https://github.com/microsoft/vscode-dotnettools/files/11852692/exthost.zip)

Thanks!

**Comment by dibarbet** [comment]
Hmm.  From the logs things *appear* to be functioning correctly.  

Mind getting a bit more info for me to help figure out where things are going wrong?
1.  I'm seeing a solution with 1 project being loaded, is that the right number of projects?
2.  If you could set the `dotnet.server.trace` setting to `Trace`, reload the window, invoke the go to def / references and then send me the C# / C# LSP Trace logs?  That will tell me if the correct info is getting to the language server.
3.  If you could, share a screenshot of what the solution explorer looks like?
e.g. should be something like this
![image](https://github.com/microsoft/vscode-dotnettools/assets/5749229/3b6d0e17-283f-41e4-ae8b-afa5ef2fbe2e)

**Comment by jtsom** [comment]
I did have a solution that had one project in it, and when I went to test, Go To Reference seemed to be working.

I opened another project that has multiple projects in it and Go To Reference was not working, syntax coloring was not correct. I went to look at the solution, as you mentioned, and noticed there was not a solution open. When I clicked to open the solution (and selected my solution), things reloaded and the reference lookup, and syntax coloring came back.

Guessing it has to do with not having a solution open, just an open folder with a project (csproj) in it (as was under the "old" C# extension)

I can still get the trace (it's big and has company info in it I'll need to cut out) if you need it, but I think I'll wait to for the next release and hope the flood of errors goes away.

Thanks!

**Comment by jtsom** [comment]
Had to back out the extension again. While the references were ok for a little bit, the language service seemed to restart and was back to not seeing any references. Go To Reference could not find anything, syntax coloring went away.

Returned to old OmniShart based extension, and it's all working again.

**Comment by dibarbet** [comment]
Sorry to hear that - do you have any more details on what triggered the restart (was there an error pop-up or anything)?

If you could paste the C# output window log here the next time it happens that would super be helpful.

**Comment by jtsom** [comment]
I'm not sure what caused it, perhaps I did a build and it happened after that. (I was seeing issues in the Problems window, where warning messages were being truncated - I submitted a new report for that). I could not get it back working, no matter how many times I tried to reload the window.

If I do try again, I will certainly send a log along. I will keep an eye out for any updates.

Thanks.
