### ISSUE TITLE
[BUG] Request textDocument/documentSymbol failed

### ISSUE THREAD

**Issue by ivanjx** [microsoft/vscode-dotnettools#203]
### Describe the Issue

```
[Error - 11:43:27 AM] Request textDocument/documentSymbol failed.
Error: name must not be falsy
	at k.validate (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:26587)
	at new k (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:26882)
	at V (/home/ivan/.vscode/extensions/ms-dotnettools.csharp-2.0.238-linux-x64/dist/extension.js:2:1969097)
	at c (/home/ivan/.vscode/extensions/ms-dotnettools.csharp-2.0.238-linux-x64/dist/extension.js:2:2007153)
	at t.map (/home/ivan/.vscode/extensions/ms-dotnettools.csharp-2.0.238-linux-x64/dist/extension.js:2:2007239)
	at Object.asDocumentSymbols (/home/ivan/.vscode/extensions/ms-dotnettools.csharp-2.0.238-linux-x64/dist/extension.js:2:1976915)
	at r (/home/ivan/.vscode/extensions/ms-dotnettools.csharp-2.0.238-linux-x64/dist/extension.js:2:1915464)
	at async a.provideDocumentSymbols (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:101:37935)
```

### Steps To Reproduce

not sure. usually happens when im creating a new file and start writing stuff in it.

### Expected Behavior

error does not show or provide options to hide it permanently.

### Environment Information

- OS: Ubuntu 23.04
- VSCode: 1.79.2
- Extension: v2.0.238

**Comment by smitpatel** [comment]
Error seems to be coming from LSP

**Comment by JorgeHerreraU** [comment]
I second this

VSCode: 1.79.2
Extension: v2.0.238
OS: Windows 11 Enterprise 22H2

https://github.com/microsoft/vscode-dotnettools/assets/34349731/b086480d-5c03-4229-a4f7-db2943f5bcb9

**Comment by arkalyanms** [comment]
This is a dup of https://github.com/dotnet/roslyn/issues/68742
