### ISSUE TITLE
[BUG] C# Dev Kit: Extension host terminated unexpectedly 3 times within the last 5 minutes

### ISSUE THREAD

**Issue by myesn** [microsoft/vscode-dotnettools#233]
### Describe the Issue

When I enable the C# Dev Kit plugin, an error box pops up in the lower right corner saying "Extension host terminated unexpectedly 3 times within the last 5 minutes.".

Output -> Window:
```
2023-07-07 10:03:16.571 [error] Extension host (LocalProcess) terminated unexpectedly. No extensions were activated.
2023-07-07 10:03:16.572 [info] Automatically restarting the extension host.
2023-07-07 10:03:18.771 [error] Extension host (LocalProcess) terminated unexpectedly. No extensions were activated.
2023-07-07 10:03:18.772 [info] Automatically restarting the extension host.
2023-07-07 10:03:18.773 [error] Canceled: Canceled
    at Object.v [as canceled] (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:10:1192)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1535:12007
    at Array.forEach (<anonymous>)
    at p.dispose (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1535:11972)
    at Nr.dispose (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1535:24371)
    at e.NativeExtensionService.qb (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2607:22610)
    at e.NativeExtensionService.wb (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2608:999)
    at e.NativeExtensionService.wb (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2608:9773)
    at e.NativeExtensionService.vb (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2608:812)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2608:507
    at g.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:93:145)
    at r.deliver (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:93:2121)
    at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:93:1729)
    at e.NativeLocalProcessExtensionHost.K (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1635:10393)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1635:6957
    at g.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:93:145)
    at r.deliver (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:93:2121)
    at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:93:1729)
    at Z (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:564:793)
    at A.t (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:564:1577)
    at A.s (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:564:1471)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:563:1334
    at g.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:93:145)
    at r.deliver (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:93:2121)
    at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:93:1729)
    at Function.ne (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:91:29722)
2023-07-07 10:03:18.780 [error] Canceled: Canceled
    at Object.v [as canceled] (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:10:1192)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1535:12007
    at Array.forEach (<anonymous>)
    at p.dispose (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1535:11972)
    at Nr.dispose (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1535:24371)
    at e.NativeExtensionService.qb (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2607:22610)
    at e.NativeExtensionService.wb (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2608:999)
    at e.NativeExtensionService.wb (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2608:9773)
    at e.NativeExtensionService.vb (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2608:812)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2608:507
    at g.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:93:145)
    at r.deliver (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:93:2121)
    at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:93:1729)
    at e.NativeLocalProcessExtensionHost.K (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1635:10393)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1635:6957
    at g.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:93:145)
    at r.deliver (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:93:2121)
    at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:93:1729)
    at Z (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:564:793)
    at A.t (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:564:1577)
    at A.s (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:564:1471)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:563:1334
    at g.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:93:145)
    at r.deliver (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:93:2121)
    at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:93:1729)
    at Function.ne (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:91:29722)
2023-07-07 10:03:18.780 [warning] Settings Sync: Accounts are not initialized
2023-07-07 10:03:19.427 [info] [perf] Render performance baseline is 61ms
2023-07-07 10:03:20.943 [error] Extension host (LocalProcess) terminated unexpectedly. No extensions were activated.
```

### Steps To Reproduce

1. Install or enable C# Dev Kit

### Expected Behavior

Normal work

### Environment Information

- OS: Ubuntu 20.04.6 LTS x86_64
- VS Code: 1.79.2
- C# Dev Kit(Extension): v0.1.103

**Comment by Michael-Eng** [comment]
This doesn't look like our code for C# Dev Kit. Is VS Code working with other extensions? The error "No extensions were activated." implies errors in VS Code before we even get activated.

**Comment by timheuer** [comment]
@myesn Are you still experiencing this error?

**Comment by timheuer** [comment]
HI @myesn Are you able to confirm if still experiencing this error.  This issue is a bit stale now. It would be good if you can update to the latest pre-release version and confirm either you are still experiencing the issue or no longer.  Thank you!

**Comment by myesn** [comment]
I'm not using that computer anymore and I haven't had time to use vs code lately, so I'll close this issue for now, thanks for your attention!
