### ISSUE TITLE
[BUG] Command `signIntoVsAccount` not found on signin

### ISSUE THREAD

**Issue by renebentes** [microsoft/vscode-dotnettools#27]
Type: <b>Bug</b>

I can't connect to my Visual Studio account because the extension returns `command csdevkit.signIntoVsAccount not found`

Extension version: 0.1.83
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (0.75GB free)|
|Process Argv|--crash-reporter-id 10b5fe83-156f-494a-97fe-70431051817a --crash-reporter-id 10b5fe83-156f-494a-97fe-70431051817a --crash-reporter-id 10b5fe83-156f-494a-97fe-70431051817a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyonecf:30548226
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixhidewlkth:30730051
showsbindicator:30760979
pythongtdpathcf:30739705

```

</details>

**Comment by timheuer** [comment]
Hi @renebentes can you try to reload window (from command pallette and choose 'reload window')?

**Comment by timheuer** [comment]
Possibly related #24

**Comment by timheuer** [comment]
> Same problem here on macOS 13.4.
> 
> C# extension version: v1.25.9 C# Dev Kit extension version: v0.1.83 IntelliCode extension version: v0.1.9 VS Code version: 1.78.2
> 
> I assume this is why I don't actually see the Solution view in the Explorer.
> 
> EDIT: "Reload Window" and completely restarting VS Code have no effect.

@sandyarmstrong based on your output here, you need to move to the pre-release of the C# extension (should be 2.0.x not 1.25.9) -- there should have been a notification telling you to do so. But if you go to the marketplace and "Switch to Pre-Release" nad then see if yours still repros, but for now I can see you don't have the right extensions.

**Comment by sandyarmstrong** [comment]
@timheuer I didn't have the C# extension installed originally. The only install I invoked was for IntelliCode, which pulled in the others. So I guess some dependencies are not configured correctly?

**Comment by renebentes** [comment]
> Hi @renebentes can you try to reload window (from command pallette and choose 'reload window')?

I reloaded the window and restarted VS Code but it didn't change the behavior. I still can't log into the VS account.

I'm using the preview release of the C# extension.

**Comment by timheuer** [comment]
@AndreyTretyak

**Comment by AndreyTretyak** [comment]
> > Hi @renebentes can you try to reload window (from command pallette and choose 'reload window')?
> 
> I reloaded the window and restarted VS Code but it didn't change the behavior. I still can't log into the VS account.
> 
> I'm using the preview release of the C# extension.

@renebentes are you able to use any other functionality of the C# Dev Kit, for example running `.NET: Open Solution` or `.NET: Build`. I'm trying to understand if whole extension was not initialized or it's only sign in command.

Also do you see C# Dev Kit extension icon in the status bar that should indicate that it was succesfully loaded
![image](https://github.com/microsoft/vscode-dotnettools/assets/2550113/f1507c45-1ee3-4aa2-9122-909e472f7f17)

**Comment by renebentes** [comment]
I can't able to use anything. All C# Dev Kit features return error.

My system language is pt-BR.

**Comment by AndreyTretyak** [comment]
> I can't able to use anything. All C# Dev Kit features return error.
> 
> My system language is pt-BR.

Thank you for checking, looks like extension was not initialized correctly.

Could you please open the Output pane (ctrl+shift+u) and check if you have `C# Dev Kit` channel there:
![image](https://github.com/microsoft/vscode-dotnettools/assets/2550113/08ebd707-27b2-4ba7-bf8c-28ce7b824adb)
This channel might contain inforamation about extension initialization failures that migth help us to investigate problem.


If you don't see `C# Dev Kit` channel , then it's possible that extension did not attempted to start. As a way to for it to start could you please open in VS Code folder that contains file with extension `.cproj` (C# project file) and check if it would enable commands or at least show extension icon in the status bar and add `C# Dev Kit` output channel.

**Comment by renebentes** [comment]
I defined a new profile and installed only the C# Dev Kit and ptBR Translation extensions.

<img width="951" alt="C# Dev Kit installed" src="https://github.com/microsoft/vscode-dotnettools/assets/2778144/04e09ec4-2450-421a-8f98-10f9402a1c6a">

After pre-release C# extension  update, Dev Kit prompted this.

<img width="960" alt="C# upgraded" src="https://github.com/microsoft/vscode-dotnettools/assets/2778144/807d346d-b06f-4c33-bc25-7c5db652426a">

Reverting the upgrade doesn't work.

**Comment by timheuer** [comment]
@renebentes is this describing a new problem for you? I can’t tell what you are trying to describe in this last comment.

**Comment by renebentes** [comment]
No. I'm describing the steps of my attempts to use

**Comment by timheuer** [comment]
> No. I'm describing the steps of my attempts to use

Okay after your latest attempt are you still unable to open a solution? Based on the screenshot it looks like you have everything installed right (Dev Kit, pre-release C#).  So I'm curious if you are still unable to open?  You'd basically still open a folder containing your C# solution/project and then the extensions will activate.  Then I'm curious if you are still getting this error.

**Comment by renebentes** [comment]
Yes. I'm still getting error. The extension just doesn't work for me. 🙁

**Comment by AndreyTretyak** [comment]
> Yes. I'm still getting error. The extension just doesn't work for me. 🙁

Did you get any info in the output channels? as described in my previous comment https://github.com/microsoft/vscode-dotnettools/issues/27#issuecomment-1588356420

**Comment by renebentes** [comment]
No. When I switch to C# pre-release the extension stops and without that everything else doesn't work either

**Comment by timheuer** [comment]
> No. When I switch to C# pre-release the extension stops and without that everything else doesn't work either

@renebentes Do you happen to have a space in your user name on the machine? 

Would you be open to a video call to see this experience? I just installed pt-BR languages, etc. and seems to be working for me. I would like to understand more about your workstation setup.  For example what is the output of `dotnet --info` for you

**Comment by renebentes** [comment]
My Microsoft account has an underscore `_` but I don't see it in the user folder on my computer.

```powershell
dotnet --info
.NET SDK:
 Version:   7.0.400-preview.23274.1
 Commit:    44de7b351c

Ambiente de runtime:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.400-preview.23274.1\

Host:
  Version:      7.0.7
  Architecture: x64
  Commit:       5b20af47d9

.NET SDKs installed:
  6.0.101 [C:\Program Files\dotnet\sdk]
  6.0.102 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]
  6.0.300-preview.22154.4 [C:\Program Files\dotnet\sdk]
  6.0.301 [C:\Program Files\dotnet\sdk]
  6.0.302 [C:\Program Files\dotnet\sdk]
  6.0.401 [C:\Program Files\dotnet\sdk]
  6.0.410 [C:\Program Files\dotnet\sdk]
  7.0.304 [C:\Program Files\dotnet\sdk]
  7.0.400-preview.23274.1 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

Maybe all of these SDKs could be conflicting?

**Comment by AndreyTretyak** [comment]
> No. When I switch to C# pre-release the extension stops and without that everything else doesn't work either

Thank you for checking, could you also please check `Extension Host` output channel (simular to checking C# Dev Kit output channel) if extension crashed (looks like the case if you don't see logs mentioned above) there should be some errors in it about reasons for that.

Also having multiple .NET SDKs installed is as supported scenario and they should not conflict with each other.

**Comment by renebentes** [comment]
Sorry for the delay.

Extension Host:

```txt
2023-06-24 10:30:00.151 [info] Extension host terminating: renderer closed the MessagePort
2023-06-24 10:30:00.221 [error] Canceled: Canceled
	at new l (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:105905)
	at s.O (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:11754)
	at $.<computed>.j.charCodeAt.$.<computed> (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:9029)
	at e.ExtHostCommands.g (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:130078)
	at e.ExtHostCommands.executeCommand (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:129454)
	at k.registerCommand.description (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:128747)
	at e.ExtHostCommands.h (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:130664)
	at e.ExtHostCommands.g (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:129554)
	at e.ExtHostCommands.executeCommand (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:129454)
	at Object.executeCommand (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:24230)
	at D (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1261288)
	at b.invoke (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:145)
	at d.deliver (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2121)
	at n.fire (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1729)
	at Object.m [as dispose] (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1276121)
	at c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1280622
	at Array.forEach (<anonymous>)
	at g.dispose (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1280608)
	at r.<anonymous> (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:12552)
	at r.dispose (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:12687)
	at r.<anonymous> (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1263418)
	at r.dispose (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:12687)
	at I (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:10:12083)
	at n.Z (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:11285)
	at c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:9187
	at Array.map (<anonymous>)
	at n.S (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:9175)
	at n.terminate (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:9445)
	at h.terminate (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:1544)
	at p (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:127:34497)
	at MessagePortMain.<anonymous> (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:127:30636)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367) setContext undefined
2023-06-24 10:30:00.222 [error] Canceled: Canceled
	at new l (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:105905)
	at s.O (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:11754)
	at $.<computed>.j.charCodeAt.$.<computed> (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:9029)
	at e.ExtHostCommands.g (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:130078)
	at e.ExtHostCommands.executeCommand (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:129454)
	at k.registerCommand.description (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:128747)
	at e.ExtHostCommands.h (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:130664)
	at e.ExtHostCommands.g (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:129554)
	at e.ExtHostCommands.executeCommand (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:129454)
	at Object.executeCommand (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:24230)
	at set b [as b] (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\github\dist\extension.js:2:152873)
	at c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\github\dist\extension.js:2:153583
	at c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1348881
	at b.invoke (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:145)
	at d.deliver (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2121)
	at n.fire (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1729)
	at Object.m [as dispose] (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1276121)
	at c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1280622
	at Array.forEach (<anonymous>)
	at g.dispose (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1280608)
	at r.<anonymous> (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:12552)
	at r.dispose (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:12687)
	at r.<anonymous> (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main.js:2:1263418)
	at r.dispose (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:12687)
	at I (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:10:12083)
	at n.Z (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:11285)
	at c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:9187
	at Array.map (<anonymous>)
	at n.S (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:9175)
	at n.terminate (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:9445)
	at h.terminate (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:1544)
	at p (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:127:34497)
	at MessagePortMain.<anonymous> (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:127:30636)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367) setContext undefined
2023-06-24 10:30:00.231 [info] Extension host with pid 14308 exiting with code 0
2023-06-24 10:30:01.843 [info] Extension host with pid 14676 started
2023-06-24 10:30:01.843 [info] Skipping acquiring lock for c:\Users\username\AppData\Roaming\Code\User\workspaceStorage\5314605add3c57d8c9032128512557ea.
2023-06-24 10:30:01.936 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2023-06-24 10:30:02.010 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2023-06-24 10:30:02.095 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2023-06-24 10:30:02.157 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2023-06-24 10:30:02.223 [info] ExtensionService#_doActivateExtension ms-dotnettools.vscode-dotnet-runtime, startup: true, activationEvent: 'workspaceContains:**/*.csproj', root cause: ms-dotnettools.csdevkit
2023-06-24 10:30:02.373 [info] ExtensionService#_doActivateExtension ms-dotnettools.csharp, startup: true, activationEvent: 'workspaceContains:**/*.csproj', root cause: ms-dotnettools.csdevkit
2023-06-24 10:30:02.557 [info] ExtensionService#_doActivateExtension vscode.json-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2023-06-24 10:30:02.583 [info] ExtensionService#_doActivateExtension vscode.typescript-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2023-06-24 10:30:02.629 [error] Activating extension ms-dotnettools.csharp failed due to an error:
2023-06-24 10:30:02.629 [error] TypeError: Cannot read properties of undefined (reading 'scope')
    at z.Hb (vscode-file://vscode-app/c:/Users/username/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2269:74144)
    at async Promise.all (index 0)
    at async Object.q [as settled] (vscode-file://vscode-app/c:/Users/username/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:97:21518)
    at async z.updateValue (vscode-file://vscode-app/c:/Users/username/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2269:62177)
2023-06-24 10:30:02.629 [info] Eager extensions activated
2023-06-24 10:30:02.697 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2023-06-24 10:30:02.704 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2023-06-24 10:30:02.725 [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl-recommender, startup: false, activationEvent: 'onStartupFinished'
2023-06-24 10:30:03.349 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2023-06-24 10:30:03.470 [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
```

**Comment by timheuer** [comment]
@renebentes are you still facing this?

**Comment by renebentes** [comment]
> @renebentes are you still facing this?

No. This issue is solved.

Thank you all.

**Comment by timheuer** [comment]
Thank you for confirming @renebentes.  Closing.
