### ISSUE TITLE
Entirely unable to install `ms-dotnettools.csharp`

### ISSUE THREAD

**Issue by just-ero** [microsoft/vscode-dotnettools#338]
Type: <b>Bug</b>

As the title states, I am entirely unable to install the C# extension. It is supposed to come as a dependency for the C# Dev Kit extension and they do install together, but the moment VSCode is restarted or reloaded, the C# extension is uninstalled again, leading C# Dev Kit (and IntelliCode) to complain about the missing dependency.

I'm unsure about actual reproduction steps. All I'm doing is installing the C# Dev Kit extension, reloading, and that's it.

This issue has halted my entire development process at the moment and I'd love to get this fixed ASAP. If there's anything else I need to provide, please let me know.

Extension version: 0.3.21
VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:37:13.485Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor              (16 x 4200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.91GB (54.16GB free)|
|Process Argv|C:\\Users\\Ero\\Desktop\\mingw-w64-v11.0.0 --crash-reporter-id 07e98ea7-4363-4c08-a600-c28db3bdbc18|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
89544117:30613380
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
7ij38806:30736111
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by timheuer** [comment]
@just-ero Sorry you are getting this issue.  Can you provide any screen shots of errors you are seeing, and logs from both the 'Extension Host' logs as well as anything from the "C#,C# Dev Kit, .NET Tools *" logs?

**Comment by just-ero** [comment]
<details>
  <summary>Extension Host Logs</summary>

  ```
  2023-08-07 18:11:42.754 [info] Extension host with pid 10896 started
  2023-08-07 18:11:42.754 [info] Skipping acquiring lock for c:\Users\Ero\AppData\Roaming\Code\User\workspaceStorage\d7c0aa07e635a8510688ffec9a257d81.
  2023-08-07 18:11:42.822 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
  2023-08-07 18:11:42.868 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
  2023-08-07 18:11:42.871 [info] ExtensionService#_doActivateExtension EditorConfig.EditorConfig, startup: true, activationEvent: '*'
  2023-08-07 18:11:42.990 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
  2023-08-07 18:11:43.005 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
  2023-08-07 18:11:43.102 [info] Eager extensions activated
  2023-08-07 18:11:43.116 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
  2023-08-07 18:11:43.118 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
  2023-08-07 18:11:43.124 [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl-recommender, startup: false, activationEvent: 'onStartupFinished'
  2023-08-07 18:11:43.135 [info] ExtensionService#_doActivateExtension eamodio.gitlens, startup: false, activationEvent: 'onStartupFinished'
  2023-08-07 18:11:43.165 [info] ExtensionService#_doActivateExtension GitHub.copilot, startup: false, activationEvent: 'onStartupFinished'
  2023-08-07 18:11:43.223 [info] ExtensionService#_doActivateExtension GitHub.copilot-chat, startup: false, activationEvent: 'onStartupFinished'
  2023-08-07 18:11:43.293 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onStartupFinished', root cause: GitHub.vscode-pull-request-github
  2023-08-07 18:11:43.301 [info] ExtensionService#_doActivateExtension LeonardSSH.vscord, startup: false, activationEvent: 'onStartupFinished'
  2023-08-07 18:11:43.347 [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl, startup: false, activationEvent: 'onStartupFinished'
  2023-08-07 18:11:43.440 [info] ExtensionService#_doActivateExtension PKief.material-icon-theme, startup: false, activationEvent: 'onStartupFinished'
  2023-08-07 18:11:43.473 [info] ExtensionService#_doActivateExtension zhuangtongfa.material-theme, startup: false, activationEvent: 'onStartupFinished'
  2023-08-07 18:11:44.128 [info] ExtensionService#_doActivateExtension GitHub.vscode-pull-request-github, startup: false, activationEvent: 'onStartupFinished'
  2023-08-07 18:11:44.446 [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
  ```
</details>

<details>
  <summary>C# Extension Output (after clicking 'Install')</summary>

  ```
  [ERROR] Failed to activate 'ms-dotnettools.csdevkit'
  Dotnet path: c:\Users\Ero\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.9\dotnet.exe
  Activating C# + C# Dev Kit + C# IntelliCode...
  [Error - 6:15:20 PM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
  Error: Cannot activate the 'IntelliCode for C# Dev Kit' extension because it depends on unknown extension 'ms-dotnettools.csharp'
    at D.j (c:\Users\Ero\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:4853)
    at c:\Users\Ero\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:4039
    at Array.map (<anonymous>)
    at D.h (c:\Users\Ero\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:4027)
    at D.activateByEvent (c:\Users\Ero\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:3704)
    at r.U (c:\Users\Ero\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:116:8350)
    at c:\Users\Ero\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:116:19776
  ```
</details>

<details>
  <summary>C# LSP Trace Logs</summary>

  ```
  Extension vscode.bat does not contribute csharpExtensionLoadPaths
  Extension vscode.clojure does not contribute csharpExtensionLoadPaths
  Extension vscode.coffeescript does not contribute csharpExtensionLoadPaths
  Extension vscode.configuration-editing does not contribute csharpExtensionLoadPaths
  Extension vscode.cpp does not contribute csharpExtensionLoadPaths
  Extension vscode.csharp does not contribute csharpExtensionLoadPaths
  Extension vscode.css does not contribute csharpExtensionLoadPaths
  Extension vscode.css-language-features does not contribute csharpExtensionLoadPaths
  Extension vscode.dart does not contribute csharpExtensionLoadPaths
  Extension vscode.debug-auto-launch does not contribute csharpExtensionLoadPaths
  Extension vscode.debug-server-ready does not contribute csharpExtensionLoadPaths
  Extension vscode.diff does not contribute csharpExtensionLoadPaths
  Extension vscode.docker does not contribute csharpExtensionLoadPaths
  Extension vscode.emmet does not contribute csharpExtensionLoadPaths
  Extension vscode.extension-editing does not contribute csharpExtensionLoadPaths
  Extension vscode.fsharp does not contribute csharpExtensionLoadPaths
  Extension vscode.git does not contribute csharpExtensionLoadPaths
  Extension vscode.git-base does not contribute csharpExtensionLoadPaths
  Extension vscode.github does not contribute csharpExtensionLoadPaths
  Extension vscode.github-authentication does not contribute csharpExtensionLoadPaths
  Extension vscode.go does not contribute csharpExtensionLoadPaths
  Extension vscode.groovy does not contribute csharpExtensionLoadPaths
  Extension vscode.grunt does not contribute csharpExtensionLoadPaths
  Extension vscode.gulp does not contribute csharpExtensionLoadPaths
  Extension vscode.handlebars does not contribute csharpExtensionLoadPaths
  Extension vscode.hlsl does not contribute csharpExtensionLoadPaths
  Extension vscode.html does not contribute csharpExtensionLoadPaths
  Extension vscode.html-language-features does not contribute csharpExtensionLoadPaths
  Extension vscode.ini does not contribute csharpExtensionLoadPaths
  Extension vscode.ipynb does not contribute csharpExtensionLoadPaths
  Extension vscode.jake does not contribute csharpExtensionLoadPaths
  Extension vscode.java does not contribute csharpExtensionLoadPaths
  Extension vscode.javascript does not contribute csharpExtensionLoadPaths
  Extension vscode.json does not contribute csharpExtensionLoadPaths
  Extension vscode.json-language-features does not contribute csharpExtensionLoadPaths
  Extension vscode.julia does not contribute csharpExtensionLoadPaths
  Extension vscode.latex does not contribute csharpExtensionLoadPaths
  Extension vscode.less does not contribute csharpExtensionLoadPaths
  Extension vscode.log does not contribute csharpExtensionLoadPaths
  Extension vscode.lua does not contribute csharpExtensionLoadPaths
  Extension vscode.make does not contribute csharpExtensionLoadPaths
  Extension vscode.markdown does not contribute csharpExtensionLoadPaths
  Extension vscode.markdown-language-features does not contribute csharpExtensionLoadPaths
  Extension vscode.markdown-math does not contribute csharpExtensionLoadPaths
  Extension vscode.media-preview does not contribute csharpExtensionLoadPaths
  Extension vscode.merge-conflict does not contribute csharpExtensionLoadPaths
  Extension vscode.microsoft-authentication does not contribute csharpExtensionLoadPaths
  Extension ms-vscode-remote.remote-wsl-recommender does not contribute csharpExtensionLoadPaths
  Extension ms-vscode.js-debug does not contribute csharpExtensionLoadPaths
  Extension ms-vscode.js-debug-companion does not contribute csharpExtensionLoadPaths
  Extension ms-vscode.vscode-js-profile-table does not contribute csharpExtensionLoadPaths
  Extension vscode.builtin-notebook-renderers does not contribute csharpExtensionLoadPaths
  Extension vscode.npm does not contribute csharpExtensionLoadPaths
  Extension vscode.objective-c does not contribute csharpExtensionLoadPaths
  Extension vscode.perl does not contribute csharpExtensionLoadPaths
  Extension vscode.php does not contribute csharpExtensionLoadPaths
  Extension vscode.php-language-features does not contribute csharpExtensionLoadPaths
  Extension vscode.powershell does not contribute csharpExtensionLoadPaths
  Extension vscode.pug does not contribute csharpExtensionLoadPaths
  Extension vscode.python does not contribute csharpExtensionLoadPaths
  Extension vscode.r does not contribute csharpExtensionLoadPaths
  Extension vscode.razor does not contribute csharpExtensionLoadPaths
  Extension vscode.references-view does not contribute csharpExtensionLoadPaths
  Extension vscode.restructuredtext does not contribute csharpExtensionLoadPaths
  Extension vscode.ruby does not contribute csharpExtensionLoadPaths
  Extension vscode.rust does not contribute csharpExtensionLoadPaths
  Extension vscode.scss does not contribute csharpExtensionLoadPaths
  Extension vscode.search-result does not contribute csharpExtensionLoadPaths
  Extension vscode.shaderlab does not contribute csharpExtensionLoadPaths
  Extension vscode.shellscript does not contribute csharpExtensionLoadPaths
  Extension vscode.simple-browser does not contribute csharpExtensionLoadPaths
  Extension vscode.sql does not contribute csharpExtensionLoadPaths
  Extension vscode.swift does not contribute csharpExtensionLoadPaths
  Extension vscode.theme-abyss does not contribute csharpExtensionLoadPaths
  Extension vscode.theme-defaults does not contribute csharpExtensionLoadPaths
  Extension vscode.theme-kimbie-dark does not contribute csharpExtensionLoadPaths
  Extension vscode.theme-monokai does not contribute csharpExtensionLoadPaths
  Extension vscode.theme-monokai-dimmed does not contribute csharpExtensionLoadPaths
  Extension vscode.theme-quietlight does not contribute csharpExtensionLoadPaths
  Extension vscode.theme-red does not contribute csharpExtensionLoadPaths
  Extension vscode.vscode-theme-seti does not contribute csharpExtensionLoadPaths
  Extension vscode.theme-solarized-dark does not contribute csharpExtensionLoadPaths
  Extension vscode.theme-solarized-light does not contribute csharpExtensionLoadPaths
  Extension vscode.theme-tomorrow-night-blue does not contribute csharpExtensionLoadPaths
  Extension vscode.typescript does not contribute csharpExtensionLoadPaths
  Extension vscode.typescript-language-features does not contribute csharpExtensionLoadPaths
  Extension vscode.vb does not contribute csharpExtensionLoadPaths
  Extension vscode.xml does not contribute csharpExtensionLoadPaths
  Extension vscode.yaml does not contribute csharpExtensionLoadPaths
  Extension akamud.vscode-theme-onedark does not contribute csharpExtensionLoadPaths
  Extension B0sh.asl-extension does not contribute csharpExtensionLoadPaths
  Extension eamodio.gitlens does not contribute csharpExtensionLoadPaths
  Extension EditorConfig.EditorConfig does not contribute csharpExtensionLoadPaths
  Extension GitHub.copilot does not contribute csharpExtensionLoadPaths
  Extension GitHub.copilot-chat does not contribute csharpExtensionLoadPaths
  Extension GitHub.github-vscode-theme does not contribute csharpExtensionLoadPaths
  Extension GitHub.vscode-pull-request-github does not contribute csharpExtensionLoadPaths
  Extension LeonardSSH.vscord does not contribute csharpExtensionLoadPaths
  Extension llvm-vs-code-extensions.vscode-clangd does not contribute csharpExtensionLoadPaths
  Extension MichaelZhou.fleet-theme does not contribute csharpExtensionLoadPaths
  Extension ms-azuretools.vscode-docker does not contribute csharpExtensionLoadPaths
  Extension ms-dotnettools.csdevkit does not contribute csharpExtensionLoadPaths
  Extension ms-dotnettools.csharp does not contribute csharpExtensionLoadPaths
  Extension ms-dotnettools.vscode-dotnet-runtime does not contribute csharpExtensionLoadPaths
  Extension ms-dotnettools.vscodeintellicode-csharp does not contribute csharpExtensionLoadPaths
  Extension ms-vscode-remote.remote-wsl does not contribute csharpExtensionLoadPaths
  Extension ms-vscode.hexeditor does not contribute csharpExtensionLoadPaths
  Extension PKief.material-icon-theme does not contribute csharpExtensionLoadPaths
  Extension redhat.vscode-xml does not contribute csharpExtensionLoadPaths
  Extension zhuangtongfa.material-theme does not contribute csharpExtensionLoadPaths
  ```
</details>

The issue persists; reloading VSCode after installing the C# extension uninstalls it. Likewise, clicking "Install and Reload" on the "Cannot activate the 'C# Dev Kit' extension because it depends on..." pop-up reloads VSCode with the C# extension uninstalled again.

**Comment by just-ero** [comment]
I managed to get this fixed. I'm unsure what exactly did it. Uninstalling all extensions which had anything to do with C# and reinstalling them is what did it.
