### ISSUE TITLE
[BUG] Project system ran into an unexpected problem

### ISSUE THREAD

**Issue by P2441M** [microsoft/vscode-dotnettools#368]
### Describe the Issue

I'm a C# programmer and I'm new to `C# Dev Kit`. I've tried to change to use vscode instead of vs to program with C# these days.
But when I created a simple web app (Razor), an error box popped up:

![图片](https://github.com/microsoft/vscode-dotnettools/assets/93473486/0a06b5e7-15cd-43ed-8be0-93d7e52632d0)

And the content of the error log looks like this:
```
=====================
8/9/2023 9:10:50 PM
LimitedFunctionality
System.AggregateException: Project system data flow 'Workspace update handler ActionBlockSlimAsync`1' closed because of an exception: 'virtualCSharp-razor:///c:/Users/Lenovo/code/C__virtual.cs' has already been added to this project. (Parameter 'filePath'). ('virtualCSharp-razor:///c:/Users/Lenovo/code/C__virtual.cs' has already been added to this project. (Parameter 'filePath'))
---> (Inner Exception #0) StreamJsonRpc.RemoteInvocationException: 'virtualCSharp-razor:///c:/Users/Lenovo/code/C__virtual.cs' has already been added to this project. (Parameter 'filePath')
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
   at Microsoft.VisualStudio.ProjectSystem.VSCode.LanguageServices.Handlers.DynamicItemHandler.<>c__DisplayClass6_0.<<HandleProjectChangeAsync>g__ProcessAdditions|4>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.ProjectSystem.VSCode.LanguageServices.Handlers.DynamicItemHandler.HandleProjectChangeAsync(IWorkspaceProject context, IComparable version, IProjectChangeDescription projectChange, ContextState state, ITelemetryOperation telemetryOperation, IManagedProjectDiagnosticOutputService logger)
   at Microsoft.VisualStudio.ProjectSystem.VSCode.LanguageServices.Handlers.DynamicItemHandler.HandleAsync(IWorkspaceProject context, IComparable version, IImmutableDictionary`2 projectChanges, ContextState state, ITelemetryOperation telemetryOperation, IManagedProjectDiagnosticOutputService logger)
   at Microsoft.VisualStudio.ProjectSystem.VSCode.LanguageServices.Workspace.<>c__DisplayClass42_1.<<OnEvaluationUpdateAsync>g__ProcessSourceItemsHandlersAsync|6>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.ProjectSystem.VSCode.LanguageServices.Workspace.<>c__DisplayClass42_0.<<OnEvaluationUpdateAsync>g__ApplyProjectEvaluationAsync|2>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.ProjectSystem.VSCode.LanguageServices.Workspace.<>c__DisplayClass45_1`1.<<OnProjectChangedAsync>g__ApplyInBatchAsync|1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Threading.ReentrantSemaphore.StackSemaphore.<>c__DisplayClass3_0.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Threading.ReentrantSemaphore.StackSemaphore.ExecuteAsync(Func`1 operation, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.OnceInitializedOnceDisposedUnderLockAsync.ExecuteUnderLockCoreAsync(Func`2 action, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.VSCode.LanguageServices.Workspace.OnEvaluationUpdateAsync(IProjectVersionedValue`1 evaluationUpdate)
   at Microsoft.VisualStudio.ProjectSystem.VSCode.LanguageServices.Workspace.<>c__DisplayClass41_0.<<OnWorkspaceUpdateAsync>g__ApplyUpdateWithinLockAsync|1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.ProjectSystem.VSCode.LanguageServices.Workspace.<>c__DisplayClass41_0.<<OnWorkspaceUpdateAsync>g__ApplyUpdateWithinLockAsync|1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.ProjectSystem.VSCode.LanguageServices.Workspace.<>c__DisplayClass41_0.<<OnWorkspaceUpdateAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Threading.ReentrantSemaphore.StackSemaphore.<>c__DisplayClass3_0.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Threading.ReentrantSemaphore.StackSemaphore.ExecuteAsync(Func`1 operation, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.OnceInitializedOnceDisposedUnderLockAsync.ExecuteUnderLockCoreAsync(Func`2 action, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.ProcessInputQueueAsync(InputDataBuffer inputQueue)
<--- (Inner Exception #0) 
===================
```

Neither using command line nor the extension UI to create the project, this error always occurs.
Except for the .NET SDK Path, I didn't change any default settings. So I don't know what's the reason of this at all.
Thanks!

### Steps To Reproduce

1. Run `dotnet new create webapp -n ProjectName -o .` in the Terminal (powershell).
2. Let the extension detect the project automatically.

### Expected Behavior

The error box won't pop up and the Intellisense can work.

### Environment Information

- OS: Windows 11
- VSCode Version: 1.81.0
- `C# Dev Kit` Version: `v0.3.21`
- `C#` Version: `v2.0.328`
- .NET Version: 7.0.10

**Comment by P2441M** [comment]
And I soon found that those errors won't happen while opening a console application.

**Comment by tmeschter** [comment]
Next step is to verify that the Project System is not sending duplicate files to the Language Service.

**Comment by P2441M** [comment]
> Next step is to verify that the Project System is not sending duplicate files to the Language Service.

How can I do this?

**Comment by tmeschter** [comment]
The .NET Project System already filters out duplicate files--that is, we won't tell the Language Service about the same file twice. @phil-allen-msft I think this is an issue on the Razor/Language Service side specifically.

**Comment by davidwengier** [comment]
@P2441M Would it be possible for you to share the full path to the project you're trying to open?

I can't reproduce this (though I did run into, and had to workaround #318, so my machine could be behaving quite differently to yours), but I noticed in your error message that its trying to load the file `virtualCSharp-razor:///c:/Users/Lenovo/code/C__virtual.cs`. Normally a Razor generated file name would have `.razor` or `.cshtml` somewhere in it. I also think it would be surprising if your Razor files were just sitting in the folder `C:\Users\Lenovo\code` on your machine. I suspect the path has a character in it (space, hashtag, percent sign, etc.) that is causing Uri encoding/deconding issues somewhere between the VS Code, the project system, Roslyn or Razor.

**Comment by P2441M** [comment]
OMG, your tip seems to have solved the problem! My project path is `C:\Users\Lenovo\code\C#\RazorPagesMovie` (with a special character `#`), so I renamed `C#` to `CSharp` and it doesn't give an error anymore! Thank you so much!

However, I still have a little confusion, because there is also a special character in `C:\Users\Lenovo\code\C#\Console`, but it can still be opened normally.😖

**Comment by davidwengier** [comment]
Different project types and file types exercise different bits of the code, in this case a `.razor` file is a "dynamic file", and its the handling of those that has the issue. Thanks for confirming where the problem lies, and glad you were able to work around it for now.

**Comment by davidwengier** [comment]
Problem seems to be in the Razor TypeScript code:

We're constructing a uri with `vscode.Uri.parse('file:' + razorDocumentUri, true)` where `razorDocumentUri` is `e:\Scratch\Blazor#\Pages\Error.cshtml` and the Uri type is stopping at the `#`. I'm guessing we need to urlencode, but that sounds like a slightly scary prospect.

<img width="406" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/754264/ef7d9903-25a6-41ce-9113-d31daf65480a">

**Comment by davidwengier** [comment]
lol this exact example is even called out in the code for the `vscode.Uri` type 🤦‍♂️

https://github.com/microsoft/vscode-uri/blob/5af89bac2109c0dc7f904b20cc88cac0568747b1/src/uri.ts#L281-L298

**Comment by P2441M** [comment]
Haha, "`URI.file(path)` is **not the same as** `URI.parse('file://' + path)`".
It seems like a common mistake😂

**Comment by davidwengier** [comment]
You won't believe what the fix is :D

**Comment by martinjt** [comment]
I don't think this is just related to Razor @davidwengier .

I'm getting this on a pure WebApi project.

The different may be that I'm running this using WSL2 remoting, is there a chance your fix will help that too?

**Comment by davidwengier** [comment]
@martinjt the call stack in the original description definitely points to a `.cshtml` or `.razor` file path being the source of the bug. If you can repro it with a different call stack, specifically without `DynamicItemHandler` being in there, then it would be great if you could log a separate issue. There have been various Uri issues on Linux that we've encountered, and I would not be surprised if there were still some rough edges.

**Comment by martinjt** [comment]
Yup, it's happening across insiders, and main, and also with pre-release or release c# extension...  Log here:

```
=====================
8/28/2023 9:12:04 PM
LimitedFunctionality
System.AggregateException: Project system data flow 'Workspace update handler ActionBlockSlimAsync`1' closed because of an exception: Invalid URI: The format of the URI could not be determined.. (Invalid URI: The format of the URI could not be determined.)
---> (Inner Exception #0) StreamJsonRpc.RemoteInvocationException: Invalid URI: The format of the URI could not be determined.
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
   at Microsoft.VisualStudio.ProjectSystem.VSCode.LanguageServices.Workspace.<>c__DisplayClass45_1`1.<<OnProjectChangedAsync>g__ApplyInBatchAsync|1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Threading.ReentrantSemaphore.StackSemaphore.<>c__DisplayClass3_0.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Threading.ReentrantSemaphore.StackSemaphore.ExecuteAsync(Func`1 operation, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.OnceInitializedOnceDisposedUnderLockAsync.ExecuteUnderLockCoreAsync(Func`2 action, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.VSCode.LanguageServices.Workspace.OnBuildUpdateAsync(IProjectVersionedValue`1 update)
   at Microsoft.VisualStudio.ProjectSystem.VSCode.LanguageServices.Workspace.<>c__DisplayClass41_0.<<OnWorkspaceUpdateAsync>g__ApplyUpdateWithinLockAsync|1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.ProjectSystem.VSCode.LanguageServices.Workspace.<>c__DisplayClass41_0.<<OnWorkspaceUpdateAsync>g__ApplyUpdateWithinLockAsync|1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.ProjectSystem.VSCode.LanguageServices.Workspace.<>c__DisplayClass41_0.<<OnWorkspaceUpdateAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Threading.ReentrantSemaphore.StackSemaphore.<>c__DisplayClass3_0.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Threading.ReentrantSemaphore.StackSemaphore.ExecuteAsync(Func`1 operation, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.OnceInitializedOnceDisposedUnderLockAsync.ExecuteUnderLockCoreAsync(Func`2 action, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.ProcessInputQueueAsync(InputDataBuffer inputQueue)
<--- (Inner Exception #0) 
===================
8/28/2023 9:12:04 PM
LimitedFunctionality
System.AggregateException: Project system data flow 'Workspace update handler ActionBlockSlimAsync`1' closed because of an exception: Invalid URI: The format of the URI could not be determined.. (Invalid URI: The format of the URI could not be determined.)
---> (Inner Exception #0) StreamJsonRpc.RemoteInvocationException: Invalid URI: The format of the URI could not be determined.
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
   at Microsoft.VisualStudio.ProjectSystem.VSCode.LanguageServices.Workspace.<>c__DisplayClass45_1`1.<<OnProjectChangedAsync>g__ApplyInBatchAsync|1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Threading.ReentrantSemaphore.StackSemaphore.<>c__DisplayClass3_0.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Threading.ReentrantSemaphore.StackSemaphore.ExecuteAsync(Func`1 operation, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.OnceInitializedOnceDisposedUnderLockAsync.ExecuteUnderLockCoreAsync(Func`2 action, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.VSCode.LanguageServices.Workspace.OnBuildUpdateAsync(IProjectVersionedValue`1 update)
   at Microsoft.VisualStudio.ProjectSystem.VSCode.LanguageServices.Workspace.<>c__DisplayClass41_0.<<OnWorkspaceUpdateAsync>g__ApplyUpdateWithinLockAsync|1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.ProjectSystem.VSCode.LanguageServices.Workspace.<>c__DisplayClass41_0.<<OnWorkspaceUpdateAsync>g__ApplyUpdateWithinLockAsync|1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.ProjectSystem.VSCode.LanguageServices.Workspace.<>c__DisplayClass41_0.<<OnWorkspaceUpdateAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Threading.ReentrantSemaphore.StackSemaphore.<>c__DisplayClass3_0.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Threading.ReentrantSemaphore.StackSemaphore.ExecuteAsync(Func`1 operation, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.OnceInitializedOnceDisposedUnderLockAsync.ExecuteUnderLockCoreAsync(Func`2 action, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.ProcessInputQueueAsync(InputDataBuffer inputQueue)
<--- (Inner Exception #0) 
===================
```

Hope that helps, my vscode is currently completely broken for .NET

**Comment by davidwengier** [comment]
Thanks @martinjt, that looks like a different issue so I've moved it to https://github.com/microsoft/vscode-dotnettools/issues/449 so the appropriate team can take a look (FYI @tmeschter )

**Comment by benjaminbours** [comment]
Hi guys, I still have the same problem about duplicate files sent to the language service I guess.

I am running the version `0.5.150`, I am on MacOS 13.5.2. I don't have any special character in my path.
