### ISSUE TITLE
Unity - Cannot get it to work. Code highlighting and IntelliSense doesn't work correctly.

### ISSUE THREAD

**Issue by Kotsuha** [microsoft/vscode-dotnettools#463]
Type: <b>Bug</b>

1. Go to URL: https://code.visualstudio.com/#alt-downloads

2. Download the "Windows .zip x64" one

3. Unzip the downloaded zip file

4. Create the data/tmp folder to make it portable

5. Launch Code.exe, install the following extensions

- Unity
- C# Dev Kit
- C#
- .NET Runtime Install Tool
- IntelliCode for C# Dev Kit

6. In Unity, the "Visual Studio Editor" version is 2.0.18

7. In Unity, the External Script Editor is set to Visual Studio Code

8. In Unity, double click on the C# script. VSCode is launched. The code highlighting and IntelliSense doesn't work correctly.

![Snipaste_2023-08-31_13-57-20](https://github.com/microsoft/vscode-dotnettools/assets/10438710/342ee433-1d7e-421e-9aa3-a136aaa26144)

C# OUTPUT:

<details>

```
Using dotnet configured on PATH
Dotnet path: C:\Program Files\dotnet\dotnet.exe
Activating C# + C# Dev Kit + C# IntelliCode...
[Info  - 1:45:22 PM] [Program]Language server initialized
[Error - 1:45:23 PM] [LanguageServerHost]Microsoft.ServiceHub.Framework.ServiceActivationFailedException: Activating the "helloServiceHubDotNetHost (0.1)" service failed.
 ---> StreamJsonRpc.RemoteInvocationException: Activating the "helloServiceHubDotNetHost (0.1)" service failed.
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
   at Microsoft.ServiceHub.Framework.RemoteServiceBroker.GetProxyAsync[T](ServiceRpcDescriptor serviceDescriptor, ServiceActivationOptions options, CancellationToken cancellationToken)
RPC server exception:
Microsoft.ServiceHub.Framework.ServiceActivationFailedException: Activating the "helloServiceHubDotNetHost (0.1)" service failed.
 ---> StreamJsonRpc.RemoteInvocationException: Could not load file or assembly 'c:\Users\usr2\Downloads\vsc\VSCode-win32-x64-1.81.1\data\extensions\ms-dotnettools.csdevkit-0.4.10-win32-x64\components\vs-green-server\platforms\win32-x64\node_modules\@microsoft\visualstudio-code-servicehost.win32-x64/Microsoft.VisualStudio.Code.ServiceHost.exe'. The system cannot find the file specified. (ErrorKind: Error HResult: 80070002)
      at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
      at Microsoft.ServiceHub.Client.HubClient.RemoteServiceBrokerWrapper.<>c__DisplayClass9_0.<<RequestServiceChannelAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.ServiceHub.Client.HubClient.RemoteServiceBrokerWrapper.<>c__DisplayClass9_0.<<RequestServiceChannelAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.ServiceHub.Utility.Shared.ServiceHubRetry.ExecuteAsync[TReturnType](Func`1 actionToExecute, TraceSource logger, ServiceHubRetryConfiguration`1 serviceHubRetryConfiguration, CancellationToken cancellationToken)
      at Microsoft.ServiceHub.Utility.Shared.ServiceHubRetry.ExecuteAsync[TReturnType](Func`1 actionToExecute, TraceSource logger, ServiceHubRetryConfiguration`1 serviceHubRetryConfiguration, CancellationToken cancellationToken)
      at Microsoft.ServiceHub.Client.HubClient.RemoteServiceBrokerWrapper.RequestServiceChannelAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
      at Microsoft.ServiceHub.Client.HubClient.RemoteServiceBrokerWrapper.RequestServiceChannelAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
      at Microsoft.ServiceHub.Framework.RemoteServiceBroker.GetPipeAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
      at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.ProfferedRemoteServiceBroker.GetPipeAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
      at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.View.GetPipeAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
      at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.View.GetPipeAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
      at Microsoft.ServiceHub.Framework.MultiplexingRelayServiceBroker.RequestServiceChannelAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)

   --- End of inner exception stack trace ---
   at Microsoft.ServiceHub.Framework.RemoteServiceBroker.GetProxyAsync[T](ServiceRpcDescriptor serviceDescriptor, ServiceActivationOptions options, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.ProfferedRemoteServiceBroker.GetProxyAsync[T](ServiceRpcDescriptor serviceDescriptor, ServiceActivationOptions options, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.View.GetProxyAsync[T](ServiceRpcDescriptor serviceDescriptor, ServiceActivationOptions options, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.LanguageServer.BrokeredServices.Services.HelloWorld.RemoteHelloWorldProvider.TryGetHelloWorldAsync(CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/BrokeredServices/Services/HelloWorld/RemoteHelloWorldProvider.cs:line 51
   at Microsoft.CodeAnalysis.LanguageServer.BrokeredServices.Services.HelloWorld.RemoteHelloWorldProvider.SayHelloToRemoteServerAsync(CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/BrokeredServices/Services/HelloWorld/RemoteHelloWorldProvider.cs:line 39
   at Microsoft.CodeAnalysis.LanguageServer.BrokeredServices.ServiceBrokerFactory.CreateAndConnectAsync(String brokeredServicePipeName) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/BrokeredServices/ServiceBrokerFactory.cs:line 82
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 136
[Error - 1:49:01 PM] [Microsoft.CodeAnalysis.LanguageServer.StarredSuggestions.StarredCompletionAssemblyHelper]N/A with Microsoft.ServiceHub.Framework.ServiceActivationFailedException: Activating the "vs-intellicode-base-models (0.1)" service failed.
 ---> StreamJsonRpc.RemoteInvocationException: Activating the "vs-intellicode-base-models (0.1)" service failed.
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
   at Microsoft.ServiceHub.Framework.RemoteServiceBroker.GetPipeAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.ProfferedRemoteServiceBroker.GetPipeAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.View.GetPipeAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
RPC server exception:
Microsoft.ServiceHub.Framework.ServiceActivationFailedException: Activating the "vs-intellicode-base-models (0.1)" service failed.
 ---> StreamJsonRpc.RemoteInvocationException: Could not load file or assembly 'c:\Users\usr2\Downloads\vsc\VSCode-win32-x64-1.81.1\data\extensions\ms-dotnettools.csdevkit-0.4.10-win32-x64\components\vs-green-server\platforms\win32-x64\node_modules\@microsoft\visualstudio-code-servicehost.win32-x64/Microsoft.VisualStudio.Code.ServiceHost.exe'. The system cannot find the file specified. (ErrorKind: Error HResult: 80070002)
      at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
      at Microsoft.ServiceHub.Client.HubClient.RemoteServiceBrokerWrapper.<>c__DisplayClass9_0.<<RequestServiceChannelAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.ServiceHub.Client.HubClient.RemoteServiceBrokerWrapper.<>c__DisplayClass9_0.<<RequestServiceChannelAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.ServiceHub.Utility.Shared.ServiceHubRetry.ExecuteAsync[TReturnType](Func`1 actionToExecute, TraceSource logger, ServiceHubRetryConfiguration`1 serviceHubRetryConfiguration, CancellationToken cancellationToken)
      at Microsoft.ServiceHub.Utility.Shared.ServiceHubRetry.ExecuteAsync[TReturnType](Func`1 actionToExecute, TraceSource logger, ServiceHubRetryConfiguration`1 serviceHubRetryConfiguration, CancellationToken cancellationToken)
      at Microsoft.ServiceHub.Client.HubClient.RemoteServiceBrokerWrapper.RequestServiceChannelAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
      at Microsoft.ServiceHub.Client.HubClient.RemoteServiceBrokerWrapper.RequestServiceChannelAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
      at Microsoft.ServiceHub.Framework.RemoteServiceBroker.GetPipeAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
      at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.ProfferedRemoteServiceBroker.GetPipeAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
      at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.View.GetPipeAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
      at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.View.GetPipeAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
      at Microsoft.ServiceHub.Framework.MultiplexingRelayServiceBroker.RequestServiceChannelAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)

   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.View.GetPipeAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
   at PythiaCSDevKit.CSDevKitCompletionHelper.GetModelServiceAsync(IServiceBroker serviceBroker, ServiceRpcDescriptor modelServiceDescriptor) in D:\a\_work\1\s\src\PythiaVSGreen\CSDevKit\CSDevKitCompletionHelper.cs:line 51
   at PythiaCSDevKit.CSDevKitCompletionHelper.CreateCompletionProviderAsync(IServiceBroker serviceBroker, ServiceRpcDescriptor modelServiceDescriptor, String baseModelPath, ILogger logger) in D:\a\_work\1\s\src\PythiaVSGreen\CSDevKit\CSDevKitCompletionHelper.cs:line 34
[Error - 1:49:01 PM] [Microsoft.CodeAnalysis.LanguageServer.StarredSuggestions.StarredCompletionAssemblyHelper]Unable to create the StarredCompletionProvider. Microsoft.ServiceHub.Framework.ServiceActivationFailedException: Activating the "vs-intellicode-base-models (0.1)" service failed.
 ---> StreamJsonRpc.RemoteInvocationException: Activating the "vs-intellicode-base-models (0.1)" service failed.
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
   at Microsoft.ServiceHub.Framework.RemoteServiceBroker.GetPipeAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.ProfferedRemoteServiceBroker.GetPipeAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.View.GetPipeAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
RPC server exception:
Microsoft.ServiceHub.Framework.ServiceActivationFailedException: Activating the "vs-intellicode-base-models (0.1)" service failed.
 ---> StreamJsonRpc.RemoteInvocationException: Could not load file or assembly 'c:\Users\usr2\Downloads\vsc\VSCode-win32-x64-1.81.1\data\extensions\ms-dotnettools.csdevkit-0.4.10-win32-x64\components\vs-green-server\platforms\win32-x64\node_modules\@microsoft\visualstudio-code-servicehost.win32-x64/Microsoft.VisualStudio.Code.ServiceHost.exe'. The system cannot find the file specified. (ErrorKind: Error HResult: 80070002)
      at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
      at Microsoft.ServiceHub.Client.HubClient.RemoteServiceBrokerWrapper.<>c__DisplayClass9_0.<<RequestServiceChannelAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.ServiceHub.Client.HubClient.RemoteServiceBrokerWrapper.<>c__DisplayClass9_0.<<RequestServiceChannelAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.ServiceHub.Utility.Shared.ServiceHubRetry.ExecuteAsync[TReturnType](Func`1 actionToExecute, TraceSource logger, ServiceHubRetryConfiguration`1 serviceHubRetryConfiguration, CancellationToken cancellationToken)
      at Microsoft.ServiceHub.Utility.Shared.ServiceHubRetry.ExecuteAsync[TReturnType](Func`1 actionToExecute, TraceSource logger, ServiceHubRetryConfiguration`1 serviceHubRetryConfiguration, CancellationToken cancellationToken)
      at Microsoft.ServiceHub.Client.HubClient.RemoteServiceBrokerWrapper.RequestServiceChannelAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
      at Microsoft.ServiceHub.Client.HubClient.RemoteServiceBrokerWrapper.RequestServiceChannelAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
      at Microsoft.ServiceHub.Framework.RemoteServiceBroker.GetPipeAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
      at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.ProfferedRemoteServiceBroker.GetPipeAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
      at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.View.GetPipeAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
      at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.View.GetPipeAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
      at Microsoft.ServiceHub.Framework.MultiplexingRelayServiceBroker.RequestServiceChannelAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)

   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.View.GetPipeAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
   at PythiaCSDevKit.CSDevKitCompletionHelper.GetModelServiceAsync(IServiceBroker serviceBroker, ServiceRpcDescriptor modelServiceDescriptor) in D:\a\_work\1\s\src\PythiaVSGreen\CSDevKit\CSDevKitCompletionHelper.cs:line 51
   at PythiaCSDevKit.CSDevKitCompletionHelper.CreateCompletionProviderAsync(IServiceBroker serviceBroker, ServiceRpcDescriptor modelServiceDescriptor, String baseModelPath, ILogger logger) in D:\a\_work\1\s\src\PythiaVSGreen\CSDevKit\CSDevKitCompletionHelper.cs:line 34
   at Microsoft.CodeAnalysis.LanguageServer.StarredSuggestions.StarredCompletionAssemblyHelper.CreateCompletionProviderAsync(MethodInfo createCompletionProviderMethodInfo, IServiceBroker serviceBroker, String modelBasePath, ILogger logger) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Services/StarredCompletions/StarredCompletionsAssemblyHelper.cs:line 120
   at Microsoft.CodeAnalysis.LanguageServer.StarredSuggestions.StarredCompletionAssemblyHelper.GetCompletionProviderAsync(CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Services/StarredCompletions/StarredCompletionsAssemblyHelper.cs:line 100
[Error - 1:49:01 PM] [LanguageServerHost]Microsoft.ServiceHub.Framework.ServiceActivationFailedException: Activating the "vs-intellicode-base-models (0.1)" service failed.
 ---> StreamJsonRpc.RemoteInvocationException: Activating the "vs-intellicode-base-models (0.1)" service failed.
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
   at Microsoft.ServiceHub.Framework.RemoteServiceBroker.GetPipeAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.ProfferedRemoteServiceBroker.GetPipeAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.View.GetPipeAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
RPC server exception:
Microsoft.ServiceHub.Framework.ServiceActivationFailedException: Activating the "vs-intellicode-base-models (0.1)" service failed.
 ---> StreamJsonRpc.RemoteInvocationException: Could not load file or assembly 'c:\Users\usr2\Downloads\vsc\VSCode-win32-x64-1.81.1\data\extensions\ms-dotnettools.csdevkit-0.4.10-win32-x64\components\vs-green-server\platforms\win32-x64\node_modules\@microsoft\visualstudio-code-servicehost.win32-x64/Microsoft.VisualStudio.Code.ServiceHost.exe'. The system cannot find the file specified. (ErrorKind: Error HResult: 80070002)
      at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
      at Microsoft.ServiceHub.Client.HubClient.RemoteServiceBrokerWrapper.<>c__DisplayClass9_0.<<RequestServiceChannelAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.ServiceHub.Client.HubClient.RemoteServiceBrokerWrapper.<>c__DisplayClass9_0.<<RequestServiceChannelAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.ServiceHub.Utility.Shared.ServiceHubRetry.ExecuteAsync[TReturnType](Func`1 actionToExecute, TraceSource logger, ServiceHubRetryConfiguration`1 serviceHubRetryConfiguration, CancellationToken cancellationToken)
      at Microsoft.ServiceHub.Utility.Shared.ServiceHubRetry.ExecuteAsync[TReturnType](Func`1 actionToExecute, TraceSource logger, ServiceHubRetryConfiguration`1 serviceHubRetryConfiguration, CancellationToken cancellationToken)
      at Microsoft.ServiceHub.Client.HubClient.RemoteServiceBrokerWrapper.RequestServiceChannelAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
      at Microsoft.ServiceHub.Client.HubClient.RemoteServiceBrokerWrapper.RequestServiceChannelAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
      at Microsoft.ServiceHub.Framework.RemoteServiceBroker.GetPipeAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
      at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.ProfferedRemoteServiceBroker.GetPipeAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
      at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.View.GetPipeAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
      at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.View.GetPipeAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
      at Microsoft.ServiceHub.Framework.MultiplexingRelayServiceBroker.RequestServiceChannelAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)

   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.View.GetPipeAsync(ServiceMoniker serviceMoniker, ServiceActivationOptions options, CancellationToken cancellationToken)
   at PythiaCSDevKit.CSDevKitCompletionHelper.GetModelServiceAsync(IServiceBroker serviceBroker, ServiceRpcDescriptor modelServiceDescriptor) in D:\a\_work\1\s\src\PythiaVSGreen\CSDevKit\CSDevKitCompletionHelper.cs:line 51
   at PythiaCSDevKit.CSDevKitCompletionHelper.CreateCompletionProviderAsync(IServiceBroker serviceBroker, ServiceRpcDescriptor modelServiceDescriptor, String baseModelPath, ILogger logger) in D:\a\_work\1\s\src\PythiaVSGreen\CSDevKit\CSDevKitCompletionHelper.cs:line 34
   at Microsoft.CodeAnalysis.LanguageServer.StarredSuggestions.StarredCompletionAssemblyHelper.CreateCompletionProviderAsync(MethodInfo createCompletionProviderMethodInfo, IServiceBroker serviceBroker, String modelBasePath, ILogger logger) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Services/StarredCompletions/StarredCompletionsAssemblyHelper.cs:line 120
   at Microsoft.CodeAnalysis.LanguageServer.StarredSuggestions.StarredCompletionAssemblyHelper.GetCompletionProviderAsync(CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Services/StarredCompletions/StarredCompletionsAssemblyHelper.cs:line 100
   at Microsoft.CodeAnalysis.LanguageServer.StarredSuggestions.StarredCompletionProvider.ProvideCompletionsAsync(CompletionContext context) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Services/StarredCompletions/StarredCompletionProvider.cs:line 25
   at Microsoft.CodeAnalysis.Completion.CompletionService.GetContextAsync(CompletionProvider provider, Document document, Int32 position, CompletionTrigger triggerInfo, CompletionOptions options, TextSpan defaultSpan, SharedSyntaxContextsWithSpeculativeModel sharedContext, CancellationToken cancellationToken) in /_/src/Features/Core/Portable/Completion/CompletionService_GetCompletions.cs:line 322
   at Microsoft.CodeAnalysis.Completion.CompletionService.ComputeNonEmptyCompletionContextsAsync(Document document, Int32 caretPosition, CompletionTrigger trigger, CompletionOptions options, TextSpan completionListSpan, ImmutableArray`1 providers, SharedSyntaxContextsWithSpeculativeModel sharedContext, CancellationToken cancellationToken) in /_/src/Features/Core/Portable/Completion/CompletionService_GetCompletions.cs:line 240
   at Microsoft.CodeAnalysis.Completion.CompletionService.GetCompletionsAsync(Document document, Int32 caretPosition, CompletionOptions options, OptionSet passThroughOptions, CompletionTrigger trigger, ImmutableHashSet`1 roles, CancellationToken cancellationToken) in /_/src/Features/Core/Portable/Completion/CompletionService_GetCompletions.cs:line 93
   at Microsoft.CodeAnalysis.LanguageServer.Handler.CompletionHandler.CalculateListAsync(CompletionParams request, Document document, Int32 position, CompletionTrigger completionTrigger, CompletionOptions completionOptions, CompletionService completionService, CompletionListCache completionListCache, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/Completion/CompletionHandler.cs:line 129
   at Microsoft.CodeAnalysis.LanguageServer.Handler.CompletionHandler.GetFilteredCompletionListAsync(CompletionParams request, RequestContext context, SourceText sourceText, Document document, CompletionOptions completionOptions, CompletionService completionService, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/Completion/CompletionHandler.cs:line 103
   at Microsoft.CodeAnalysis.LanguageServer.Handler.CompletionHandler.HandleRequestAsync(CompletionParams request, RequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/Completion/CompletionHandler.cs:line 67
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 176
[Error - 1:49:01 PM] Request textDocument/completion failed.
  Message: Activating the "vs-intellicode-base-models (0.1)" service failed.
  Code: -32000 
[object Object]

```

</details>

C# Dev Kit OUTPUT

```
Starting Spawn .NET server...
Starting Open a solution...
Starting Open a solution with environment service...
Starting Clear environment...
Using preinstalled .NET runtime at "C:\Program Files\dotnet\dotnet.exe"
.NET server started and IPC established in 2075ms
Completed Spawn .NET server (2777ms)
Completed Clear environment (3318ms)
Completed Open a solution with environment service (3365ms)
Starting Restore solution...
Completed Open a solution (3385ms)
Starting NuGet restore for the solution.
Starting command: "dotnet.exe" restore c:\Users\usrpub\Projects\XXX\FakeFlowBlock2\Repo\FakeFlow\FakeFlow.sln --interactive...
Failed to listen to project initialization status: $(err)
Completed command: "dotnet.exe" restore c:\Users\usrpub\Projects\XXX\FakeFlowBlock2\Repo\FakeFlow\FakeFlow.sln --interactive (4003ms)
Completed NuGet restore.
Completed Restore solution (4006ms)

```

Extension version: 0.9.0
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10980HK CPU @ 2.40GHz (16 x 3096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (5.82GB free)|
|Process Argv|C:\\Users\\usrpub\\Projects\\Mantis\\FakeFlowBlock2\\Repo\\FakeFlow -g C:\\Users\\usrpub\\Projects\\Mantis\\FakeFlowBlock2\\Repo\\FakeFlow\\Assets\\FakeFlow\\Utilities\\Test\\ListWithChangeEvent.cs:1:0 --crash-reporter-id f38948fc-64d4-4f92-aa7d-7e0898e26904|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
2e4cg342:30602488
f6dab269:30613381
vscrpc:30673769
a9j8j154:30646983
showlangstatbar:30737416
03d35959:30757346
7ij38806:30736111
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571

```

</details>

**Comment by jbevain** [comment]
> In Unity, the "Visual Studio Editor" version is 2.0.18

This is likely the issue? As indicated in the README, you'll need `2.0.20` or above.

**Comment by Kotsuha** [comment]
Oops. For some reason I thought I have the latest version. I've updated it to 2.0.20. Now there is a message in Unity:

> Unable to use UDP port 56066 for VS/Unity messaging. You should check if another process is already bound to this port or if your firewall settings are compatible.

Google brings me [this](https://discussions.unity.com/t/unity-editor-has-not-permission-on-udp-port/212299). Haven't try it yet. Will update after I try.

**Comment by Kotsuha** [comment]
It's working now. Let me close this issue.
