### ISSUE TITLE
[BUG] Access to the path '/home/user/.ServiceHub/1d5d2d6a2e' is denied

### ISSUE THREAD

**Issue by ms-mayya** [microsoft/vscode-dotnettools#501]
### Describe the Issue

```cs
at Microsoft.ServiceHub.Controller.Controller.RetryStartServer(Exception e, HubController controller, Boolean retryStartingController)
   at Microsoft.ServiceHub.Controller.Controller.<>c__DisplayClass12_0.<MainAsync>b__0(Exception e)
   at Microsoft.ServiceHub.Controller.ServerManager.StartServiceAsync(ServiceOptions options, Func`3 connectionCallback)
   at Microsoft.ServiceHub.Controller.Controller.StartServerAsync(ServiceOptions options, HubController controller, DevHubTraceSource logger).

.NET server STDERR: Unhandled exception. 
.NET server STDERR: Microsoft.ServiceHub.Client.ControllerConnectionException: Controller terminated before accepting connections. Exit code: 22 (ErrorStartingServer).
   at Microsoft.ServiceHub.Client.HubControllerClient.StartAsync(ServiceHubConfig config, String clientName, CancellationToken cancellationToken)
   at Microsoft.ServiceHub.Client.HubClient.LaunchOrFindControllerAsync()
   at Microsoft.ServiceHub.Client.HubClient.GetLocationServiceAsync()
   at Microsoft.ServiceHub.Utility.Shared.ServiceHubRetry.ExecuteAsync[TReturnType](Func`1 actionToExecute, TraceSource logger, ServiceHubRetryConfiguration`1 serviceHubRetryConfiguration, CancellationToken cancellationToken)
   at Microsoft.ServiceHub.Utility.Shared.ServiceHubRetry.ExecuteAsync[TReturnType](Func`1 actionToExecute, TraceSource logger, ServiceHubRetryConfiguration`1 serviceHubRetryConfiguration, CancellationToken cancellationToken)
   at Microsoft.ServiceHub.Client.HubClient.GetThisAsRemoteServiceBrokerAsync()
   at Microsoft.VisualStudio.Server.ServiceBroker.Program.RunAsync(Stream rpcStream, String bridgePipeName, ExportProvider exportProvider, Boolean includeServiceHub, String serviceHubConfigPath, Func`2 traceSourceFactory, TraceSource traceSource, TelemetrySession telemetrySession, TelemetryEvent perfTelemetryEvent, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Server.ServiceBroker.Program.RunAsync(Stream rpcStream, String bridgePipeName, ExportProvider exportProvider, Boolean includeServiceHub, String serviceHubConfigPath, Func`2 traceSourceFactory, TraceSource traceSource, TelemetrySession telemetrySession, TelemetryEvent perfTelemetryEvent, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Server.ServiceBroker.Program.<>c.<<BuildCommandLine>b__7_1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<
BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass18_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass13_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass20_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__19_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__6_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<CancelOnProcessTermination>b__1_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.InvocationPipeline.InvokeAsync(IConsole console)
   at System.CommandLine.Parsing.ParseResultExtensions.InvokeAsync(ParseResult parseResult, IConsole console)
   at System.CommandLine.Parsing.ParserExtensions.InvokeAsync(Parser parser, String[] args, IConsole console)
   at Microsoft.VisualStudio.Server.ServiceBroker.Program.Main(String[] args)
   at Microsoft.VisualStudio.Server.ServiceBroker.Program.<Main>(String[] args)

.NET server STDOUT: [createdump] Gathering state for process 7900 Microsoft.Visua
[createdump] Crashing thread 1edc signal 6 (0006)

```
[Microsoft.Visua.7900.dmp.crashreport.zip](https://github.com/microsoft/vscode-dotnettools/files/12566036/Microsoft.Visua.7900.dmp.crashreport.zip)

### Environment Information

.NET SDK:
 Version:   7.0.400
 Commit:    73bf45718d

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   [/usr/share/dotnet/sdk/7.0.400/]([url](url))

Host:
  Version:      7.0.10
  Architecture: x64
  Commit:       a6dbb800a4

.NET SDKs installed:
  6.0.412 [/usr/share/dotnet/sdk]
  7.0.400 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.20 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.20 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/home/mayya/.dotnet]

global.json file:
  Not found

**Comment by RyanToth3** [comment]
Can you please follow these steps to help us gather some more information about your issue:

1. Close VS Code.
2. Open a command prompt.
3. Set the `ServiceHubTraceLevel` environment variable to `ALL`
4. Launch VS Code from that window with the code command.
5. Reproduce the problem.
6. Use the "Open Extension Logs Folder" command in VS Code and zip up the ms-dotnettools.csdevkit folder found inside and share that?

**Comment by Michael-Eng** [comment]
Also, what were you doing when you hit this exception?

**Comment by ms-mayya** [comment]
> Can you please follow these steps to help us gather some more information about your issue:
> 
> 1. Close VS Code.
> 2. Open a command prompt.
> 3. Set the `ServiceHubTraceLevel` environment variable to `ALL`
> 4. Launch VS Code from that window with the code command.
> 5. Reproduce the problem.
> 6. Use the "Open Extension Logs Folder" command in VS Code and zip up the ms-dotnettools.csdevkit folder found inside and share that?

No such folder found after doing these steps. by the way, the .sln is in wsl.

**Comment by ms-mayya** [comment]
@Michael-Eng just open the solution folder with `code .`

**Comment by ms-mayya** [comment]
After granting access with `sudo chmod -R 777 ~/.ServiceHub` dir, it worked.
