### ISSUE TITLE
[BUG] Unable to load/run the MAUI repository with VSCode

### ISSUE THREAD

**Issue by PureWeen** [microsoft/vscode-dotnettools#520]
### Describe the Issue

At one point I was able to deploy the MAUI repository with vscode but it no longer seems to work.

Not sure if this is related but my log has the following exception

```C#
LimitedFunctionality
System.AggregateException: One or more errors occurred. (Expected 1 export(s) with contract name "Microsoft.VisualStudio.ProjectSystem.Debug.ILaunchProfileHandlerAggregator" but found 0 after applying applicable constraints.)
---> (Inner Exception #0) Microsoft.VisualStudio.Composition.CompositionFailedException: Expected 1 export(s) with contract name "Microsoft.VisualStudio.ProjectSystem.Debug.ILaunchProfileHandlerAggregator" but found 0 after applying applicable constraints.
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(ImportDefinition importDefinition)
   at Microsoft.VisualStudio.Composition.DelegatingExportProvider.GetExports(ImportDefinition importDefinition)
   at Microsoft.VisualStudio.Composition.DelegatingExportProvider.GetExports(ImportDefinition importDefinition)
   at Microsoft.VisualStudio.ProjectSystem.FilteringExportProvider.GetExports(ImportDefinition importDefinition)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(String contractName, ImportCardinality cardinality, Type type, Type metadataViewType, IMetadataViewProvider& metadataViewProvider)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T,TMetadataView](String contractName)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T](String contractName)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T]()
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]()
   at Microsoft.VisualStudio.ProjectSystem.Debug.LaunchableProfilesLaunchConfigurationProvider.<>c.<LinkExternalInput>b__4_0(ConfiguredProject c)
   at Microsoft.VisualStudio.ProjectSystem.ConfiguredProjectDataSourceJoinBlock`1.<>c__DisplayClass7_0.<.ctor>g__OnConfigurationGroupChanged|2(IProjectVersionedValue`1 configurationProjectGroup)
   at Microsoft.VisualStudio.ProjectSystem.ConfiguredProjectDataSourceJoinBlock`1.<>c__DisplayClass7_0.<.ctor>b__1(IProjectVersionedValue`1 configurationProjectGroup)
   at Microsoft.VisualStudio.ProjectSystem.TransformBlockSlim`2.TransformBlockSlimSync.ProcessInputAsync(TInput input)
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.ProcessInputQueueAsync(InputDataBuffer inputQueue)
<--- (Inner Exception #0)
```

I'm able to deploy a basic maui app just fine.

### Steps To Reproduce

- git clone git@github.com:dotnet/maui.git
- dotnet build Microsoft.Maui.BuildTasks.slnf
- now when you open vscode set Microsoft.Maui-vscode.sln as the startup sln

Now when I try to pick a project the project dialog is empty

### Expected Behavior

I should be able to select Maui.Controls.Sample.Sandbox.csproj and deploy

### Environment Information

- OS: macOS
- Version: 1.82.1 (Universal)
- C# Dev Kit v0.4.10
- .NET MAUI v0.3.22

**Comment by tmeschter** [comment]
@PureWeen The exception you reported should already be fixed. Can you try your scenario on a more recent version of C# Dev Kit and let me know if that helps?

**Comment by kvenkatrajan** [comment]
Followed up with @PureWeen who is no longer seeing this issue. Closing
