### ISSUE TITLE
[BUG] Workspace update handlers close due to JSON-RPC connection lost

### ISSUE THREAD

**Issue by clkbng** [microsoft/vscode-dotnettools#522]
### Describe the Issue

I did the following steps.

- Launched VSCode on Windows, opening an existing C# .NET 6.0 project in WSL2 remote
- Automatically updated C# Dev Kit plugin from 0.5.2 to 0.5.47 (both are pre-release versions)
- Clicked "Reload Requred" to reflesh plugins
- After a while, the following message is shown when the C# project have been loaded.

> Project system ran into an unexpected problem, please report it to the product team.

### Error Log

```
=====================
9/14/2023 11:54:38AM
LimitedFunctionality
System.AggregateException: Project system data flow 'Workspace update handler 46956100' closed because of an exception: The JSON-RPC connection with the remote party was lost before the request could complete.. (The JSON-RPC connection with the remote party was lost before the request could complete.)
---> (Inner Exception #0) StreamJsonRpc.ConnectionLostException: The JSON-RPC connection with the remote party was lost before the request could complete.
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync(JsonRpcRequest request, Type expectedResultType, CancellationToken cancellationToken)
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
   at Microsoft.VisualStudio.ProjectSystem.VSCode.LanguageServices.Handlers.MetadataReferenceItemHandler.AddReferencesAsync(IWorkspaceProject context, ImmutableArray`1 addedReferences, ITelemetryOperation telemetryOperation, IManagedProjectDiagnosticOutputService logger)
   at Microsoft.VisualStudio.ProjectSystem.VSCode.LanguageServices.Handlers.MetadataReferenceItemHandler.HandleAsync(IWorkspaceProject context, IComparable version, BuildOptions added, BuildOptions removed, ContextState state, ITelemetryOperation telemetryOperation, IManagedProjectDiagnosticOutputService logger)
   at Microsoft.VisualStudio.ProjectSystem.VSCode.LanguageServices.Workspace.<>c__DisplayClass44_0.<<OnBuildUpdateAsync>g__InvokeCommandLineUpdateHandlersAsync|5>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.ProjectSystem.VSCode.LanguageServices.Workspace.<>c__DisplayClass44_0.<<OnBuildUpdateAsync>g__ProcessCommandLineAsync|2>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.ProjectSystem.VSCode.LanguageServices.Workspace.<OnBuildUpdateAsync>g__ApplyProjectBuildAsync|44_1(IProjectVersionedValue`1 update, ContextState state, ITelemetryOperation telemetryOperation, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.VSCode.LanguageServices.Workspace.<>c__DisplayClass46_1`1.<<OnProjectChangedAsync>g__ApplyInBatchAsync|1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Threading.ReentrantSemaphore.StackSemaphore.<>c__DisplayClass3_0.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Threading.ReentrantSemaphore.StackSemaphore.ExecuteAsync(Func`1 operation, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.OnceInitializedOnceDisposedUnderLockAsync.ExecuteUnderLockCoreAsync(Func`2 action, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.VSCode.LanguageServices.Workspace.OnBuildUpdateAsync(IProjectVersionedValue`1 update)
   at Microsoft.VisualStudio.ProjectSystem.VSCode.LanguageServices.Workspace.<>c__DisplayClass42_0.<<OnWorkspaceUpdateAsync>g__ApplyUpdateWithinLockAsync|1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.ProjectSystem.VSCode.LanguageServices.Workspace.<>c__DisplayClass42_0.<<OnWorkspaceUpdateAsync>g__ApplyUpdateWithinLockAsync|1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.ProjectSystem.VSCode.LanguageServices.Workspace.<>c__DisplayClass42_0.<<OnWorkspaceUpdateAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Threading.ReentrantSemaphore.StackSemaphore.<>c__DisplayClass3_0.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Threading.ReentrantSemaphore.StackSemaphore.ExecuteAsync(Func`1 operation, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.OnceInitializedOnceDisposedUnderLockAsync.ExecuteUnderLockCoreAsync(Func`2 action, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.ProcessInputQueueAsync(InputDataBuffer inputQueue)
<--- (Inner Exception #0) 
===================
9/14/2023 11:54:38AM
LimitedFunctionality
System.AggregateException: Project system data flow 'Workspace update handler 39837611' closed because of an exception: The JSON-RPC connection with the remote party was lost before the request could complete.. (The JSON-RPC connection with the remote party was lost before the request could complete.)
# ... similar exceptions are repeated ...
```

Full logs archive is here:
[ms-dotnettools.csdevkit.tar.gz](https://github.com/microsoft/vscode-dotnettools/files/12604580/ms-dotnettools.csdevkit.tar.gz)

### Environment Information

- OS: Windows_NT x64 10.0.19045
- WSL: Alpine Linux (edge repository), 5.15.90.1-microsoft-standard-WSL2
- VS Code Version: 1.82.1 (user setup)
  - Commid ID: 6509174151d557a81c9d0b5f8a5a1e9274db5585
- Extension Version: 0.5.47 (pre-release)
- .NET Version: 7.0.110 (using preinstalled runtime)
- CPU: AMD Ryzen 5 PRO 3500U w/ Radeon Vega Mobile Gfx (8 CPUs)

**Comment by dibarbet** [comment]
The language server encountered an issue, meaning this is likely on the C# extension side.  @clkbng Would you be able to post the output from the 'C#' output window when you encounter this issue?

**Comment by clkbng** [comment]
@dibarbet 

> The language server encountered an issue, meaning this is likely on the C# extension side. @clkbng Would you be able to post the output from the 'C#' output window when you encounter this issue?

```
Using dotnet configured on PATH
Dotnet path: /usr/lib/dotnet/dotnet
Activating C# + C# Dev Kit...
[Info  - 9:46:35 AM] [Program] Language server initialized
[Info  - 9:48:22 AM] Connection to server got closed. Server will restart.
true
Using dotnet configured on PATH
Dotnet path: /usr/lib/dotnet/dotnet
Activating C# + C# Dev Kit...
[Info  - 9:48:32 AM] [Program] Language server initialized
```

* C# extension version: 2.2.10-prerelease

I still get a similar problem today.
Log directory `ms-dotnettools.csharp/` is empty.

**Comment by dibarbet** [comment]
Ok, it looks like the server is silently crashing.  I'm not super hopeful about this, but we did just release an update today that fixes one known issue with client <-> server communication.  You could try that out.  If you still have issues, would it be possible for you to collect a crash dump?

The easiest way to collect a crash dump is to launch vscode with two specific environment variables - DOTNET_DbgEnableMiniDump to 1, and DOTNET_DbgMiniDumpName to a path you can write to. Then you launch vscode from that same shell to ensure the environment variables are picked up.

For example, in bash I believe you'd do this:
```
dabarbet@MININT-F3T9PTT:~$ DOTNET_DbgEnableMiniDump=1
dabarbet@MININT-F3T9PTT:~$ DOTNET_DbgMiniDumpName="/home/dibarbet"
dabarbet@MININT-F3T9PTT:~$ code .
```

If the process crashes it will output a dump file to the location you specified.  You can upload that to your favorite file share and share with me (via email to dabarbet@microsoft.com).

**Comment by clkbng** [comment]
@dibarbet 

Thank you for your helpful response.
Unfortunately, I still have issues after update.

I tried to collect a crash dump as you said. My WSL environment doesn't have `code` command themself, so I did the following steps.

1. Added following lines to `~/.profile`
```sh
export DOTNET_DbgEnableMiniDump=1
export COMPlus_DbgEnableMiniDump=1
```
2. Shutdown the distro by `wsl --terminate Alpine` command
1. Launched VSCode on Windows, opening the project in WSL

However, I can't find the dumps in `/tmp` or in `~`. I will continue to investigate ways to collect dumps.

---

In the process, I found some suspicious behaviors.

<details>
<summary>C# Output</summary>

```
Using dotnet configured on PATH
Dotnet path: /usr/lib/dotnet/dotnet
Activating C# + C# Dev Kit...
waiting for named pipe information from server...
[stdout] {"pipeName":"/tmp/6e15e5ea-88c4-4178-b50b-9e21ae230828.sock"}
received named pipe information from server
attempting to connect client to server...
client has connected to server
[Info  - 7:12:54 PM] [Program] Language server initialized
[Error - 7:15:10 PM] Client Microsoft.CodeAnalysis.LanguageServer: connection to server is erroring. Shutting down server.
[Error - 7:15:10 PM] Client Microsoft.CodeAnalysis.LanguageServer: connection to server is erroring. Shutting down server.
[Error - 7:15:10 PM] Stopping server failed
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 7:15:10 PM] Stopping server failed
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 7:15:10 PM] Stopping server failed
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
```

</details>

<details>
<summary>Extension Host (Remote) Output</summary>

```
2023-09-22 19:12:24.831 [info] Extension host with pid 355 started
2023-09-22 19:12:24.860 [error] Error: EEXIST: file already exists, open '/home/nakano/.vscode-server/data/User/workspaceStorage/ea1357175416198fac8e9bec4650c332/vscode.lock'
2023-09-22 19:12:24.958 [info] Lock '/home/nakano/.vscode-server/data/User/workspaceStorage/ea1357175416198fac8e9bec4650c332/vscode.lock': Could not acquire lock, checking if the file is stale.
2023-09-22 19:12:24.972 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2023-09-22 19:12:24.976 [info] ExtensionService#_doActivateExtension vscode.tunnel-forwarding, startup: false, activationEvent: 'onTunnel'
2023-09-22 19:12:25.059 [info] Lock '/home/nakano/.vscode-server/data/User/workspaceStorage/ea1357175416198fac8e9bec4650c332/vscode.lock': The lockfile is scheduled to have been released.
2023-09-22 19:12:25.059 [info] Lock '/home/nakano/.vscode-server/data/User/workspaceStorage/ea1357175416198fac8e9bec4650c332/vscode.lock': Deleting a stale lock.
2023-09-22 19:12:25.108 [info] Lock '/home/nakano/.vscode-server/data/User/workspaceStorage/ea1357175416198fac8e9bec4650c332/vscode.lock': Lock acquired.
2023-09-22 19:12:25.243 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2023-09-22 19:12:25.243 [info] ExtensionService#_doActivateExtension Shopify.vscode-shadowenv, startup: true, activationEvent: '*'
2023-09-22 19:12:25.350 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2023-09-22 19:12:25.352 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2023-09-22 19:12:26.961 [info] ExtensionService#_doActivateExtension ms-dotnettools.vscode-dotnet-runtime, startup: true, activationEvent: 'workspaceContains:**/*.{csproj,sln,slnf,csx,cake}', root cause: ms-dotnettools.csharp
2023-09-22 19:12:27.842 [info] ExtensionService#_doActivateExtension ms-dotnettools.csharp, startup: true, activationEvent: 'workspaceContains:**/*.{csproj,sln,slnf,csx,cake}'
2023-09-22 19:12:35.252 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2023-09-22 19:12:35.253 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2023-09-22 19:12:35.256 [info] ExtensionService#_doActivateExtension amazonwebservices.aws-toolkit-vscode, startup: false, activationEvent: 'onStartupFinished'
2023-09-22 19:12:35.256 [info] ExtensionService#_doActivateExtension Shopify.ruby-extensions-pack, startup: false, activationEvent: 'onStartupFinished'
2023-09-22 19:12:39.795 [info] ExtensionService#_doActivateExtension ms-dotnettools.csdevkit, startup: true, activationEvent: 'workspaceContains:**/*.csproj'
2023-09-22 19:12:40.260 [info] Eager extensions activated
2023-09-22 19:15:12.037 [error] Error: Cannot call write after a stream was destroyed
	at new NodeError (node:internal/errors:399:5)
	at _write (node:internal/streams/writable:324:11)
	at Writable.write (node:internal/streams/writable:337:10)
	at /home/nakano/.vscode-server/extensions/ms-dotnettools.csharp-2.3.27-alpine-x64/dist/extension.js:2:2261719
	at new Promise (<anonymous>)
	at a.write (/home/nakano/.vscode-server/extensions/ms-dotnettools.csharp-2.3.27-alpine-x64/dist/extension.js:2:2261637)
	at g.doWrite (/home/nakano/.vscode-server/extensions/ms-dotnettools.csharp-2.3.27-alpine-x64/dist/extension.js:2:2249232)
	at /home/nakano/.vscode-server/extensions/ms-dotnettools.csharp-2.3.27-alpine-x64/dist/extension.js:2:2249127
```

</details>

<details>
<summary>Window Output</summary>

```
2023-09-22 19:12:12.855 [warning] Settings pattern "application.*" doesn't match any settings
2023-09-22 19:12:14.143 [warning] Settings pattern "application.*" doesn't match any settings
2023-09-22 19:12:14.208 [error] Extension 'ms-vscode.remote-server' appears in product.json but enables LESS API proposals than the extension wants.
package.json (LOSES): resolvers, tunnelFactory
product.json (WINS): resolvers, tunnels, contribViewsWelcome
2023-09-22 19:12:14.830 [info] Invoking resolveAuthority(wsl)...
2023-09-22 19:12:14.830 [info] [LocalProcess0][resolveAuthority(wsl,1)][0ms] obtaining proxy...
2023-09-22 19:12:14.831 [info] [LocalProcess0][resolveAuthority(wsl,1)][0ms] invoking...
2023-09-22 19:12:14.859 [warning] Settings pattern "application.*" doesn't match any settings
2023-09-22 19:12:15.621 [warning] Settings pattern "application.*" doesn't match any settings
2023-09-22 19:12:15.836 [info] [LocalProcess0][resolveAuthority(wsl,1)][1004ms] waiting...
2023-09-22 19:12:16.831 [info] [LocalProcess0][resolveAuthority(wsl,1)][2001ms] waiting...
2023-09-22 19:12:17.839 [info] [LocalProcess0][resolveAuthority(wsl,1)][3007ms] waiting...
2023-09-22 19:12:18.840 [info] [LocalProcess0][resolveAuthority(wsl,1)][4010ms] waiting...
2023-09-22 19:12:19.315 [info] [LocalProcess0][resolveAuthority(wsl,1)][4484ms] returned WebSocket(127.0.0.1:50787)
2023-09-22 19:12:19.315 [info] resolveAuthority(wsl) returned 'WebSocket(127.0.0.1:50787)' after 4486 ms
2023-09-22 19:12:19.319 [info] Creating a socket (renderer-Management-72f68447-f8b1-43b2-a7a6-9506eee8e9c9)...
2023-09-22 19:12:19.325 [info] Creating a socket (renderer-ExtensionHost-5622e4df-93d2-403d-b037-69a5644cf3b5)...
2023-09-22 19:12:20.403 [info] Creating a socket (renderer-Management-72f68447-f8b1-43b2-a7a6-9506eee8e9c9) was successful after 1083 ms.
2023-09-22 19:12:21.172 [info] Creating a socket (renderer-ExtensionHost-5622e4df-93d2-403d-b037-69a5644cf3b5) was successful after 1847 ms.
2023-09-22 19:12:23.226 [warning] Settings pattern "application.*" doesn't match any settings
2023-09-22 19:12:24.152 [info] [perf] Render performance baseline is 128ms
2023-09-22 19:12:25.446 [warning] Settings pattern "application.*" doesn't match any settings
2023-09-22 19:12:26.789 [warning] Settings pattern "application.*" doesn't match any settings
2023-09-22 19:12:29.625 [error] [Extension Host] (node:355) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
2023-09-22 19:12:39.061 [error] [Extension Host] (node:355) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
2023-09-22 19:13:25.978 [error] MainThreadFileSystem#$watch(): failed to stat a resource for file watching (extension: ms-dotnettools.csharp, path: vscode-remote://wsl+alpine/usr/share/dotnet/packs/, recursive: true, session: 0.06611551887062861): EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat '/usr/share/dotnet/packs/'
2023-09-22 19:15:11.111 [error] [Extension Host] Sending request failed.
```

</details>

Additionally, I noticed that there are multiple forwarded ports listed. They are increased each time VSCode is started. Perhaps the previous sessions still remain.

![vscode_csharp_ports](https://github.com/microsoft/vscode-dotnettools/assets/33856068/860d8dc7-e58f-44fc-b807-90f87bec0577)

**Comment by clkbng** [comment]
At the end of Window Output:

> ```
> 2023-09-22 19:13:25.978 [error] MainThreadFileSystem#$watch(): failed to stat a resource for file watching (extension: ms-dotnettools.csharp, path: vscode-remote://wsl+alpine/usr/share/dotnet/packs/, recursive: true, session: 0.06611551887062861): EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat '/usr/share/dotnet/packs/'
> 2023-09-22 19:15:11.111 [error] [Extension Host] Sending request failed.
> ```

`/usr/share/dotnet/` is incorrect dotnet path in my Alpine system. The correct path is '/usr/lib/dotnet', also shown at the beginning of C# Output.

> ```
> Dotnet path: /usr/lib/dotnet/dotnet # This is correct.
> ```

**Comment by dibarbet** [comment]
Thanks for the additional logs.  Yeah all of the logs point to the language server crashing, but I think we need the crash dump to figure out why.

The other error:
```
2023-09-22 19:13:25.978 [error] MainThreadFileSystem#$watch(): failed to stat a resource for file watching (extension: ms-dotnettools.csharp, path: vscode-remote://wsl+alpine/usr/share/dotnet/packs/, recursive: true, session: 0.06611551887062861): EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat '/usr/share/dotnet/packs/'
```

should not be causing a language server crash itself.

I'm going to take a look this week at adding support for collecting crash dumps automatically from the extension to make it easier on code server scenarios.

**Comment by dibarbet** [comment]
Thanks for trying that out.  It's likely that the server isn't actually crashing, but shutting down normally (but unexpectedly).  Will take a look to see what other information we can collect.

**Comment by dibarbet** [comment]
Ah one thing to try as well - set the `dotnet.server.trace` setting to `Trace` and collect the C# output window logs there.  It may have more clues.

**Comment by arkalyanms** [comment]
Closing due to lack of info.
