### ISSUE TITLE
[BUG] "Microsoft.DotNet.MSBuildWorkloadSdkResolver" failed while attempting to resolve the SDK "Microsoft.NET.Sdk.Web".

### ISSUE THREAD

**Issue by dibarbet** [microsoft/vscode-dotnettools#551]
### Describe the Issue

Originally filed in https://github.com/dotnet/vscode-csharp/issues/6314

Appears to be a failure to load the project (causing downstream issues). See comment here - https://github.com/dotnet/vscode-csharp/issues/6314#issuecomment-1715194898
```
2023-09-12 15:42:41.182 [error] (/Users/vs/RazorNoAuth/RazorNoAuth.csproj): SDK Resolver Failure: "The SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" failed while attempting to resolve the SDK "Microsoft.NET.Sdk.Web". Exception: "System.IO.FileNotFoundException: Could not load file or assembly 'System.Collections.Immutable, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
```

See full projects log below
<details> <summary>Project log</summary>Version:1.0
StartHTML:000000096
EndHTML:000010607
StartFragment:000000186
EndFragment:000010593

2023-09-12 15:42:41.182 [error] (/Users/vs/RazorNoAuth/RazorNoAuth.csproj): SDK Resolver Failure: "The SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" failed while attempting to resolve the SDK "Microsoft.NET.Sdk.Web". Exception: "System.IO.FileNotFoundException: Could not load file or assembly 'System.Collections.Immutable, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

 

File name: 'System.Collections.Immutable, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

   at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.CachingWorkloadResolver.Resolve(String sdkReferenceName, String dotnetRootPath, String sdkVersion, String userProfileDir, String globalJsonPath)

   at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.WorkloadSdkResolver.Resolve(SdkReference sdkReference, SdkResolverContext resolverContext, SdkResultFactory factory)

   at Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.TryResolveSdkUsingSpecifiedResolvers(IList`1 resolvers, Int32 submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath, Boolean interactive, Boolean isRunningInVisualStudio, SdkResult& sdkResult, IEnumerable`1& errors, IEnumerable`1& warnings)""

2023-09-12 15:42:41.327 [info] Project system initialization finished. 0 project(s) are loaded, and 1 failed to load.

2023-09-12 15:42:41.347 [error] Failed to load project '/Users/vs/RazorNoAuth/RazorNoAuth.csproj'. One or more errors occurred. (SDK Resolver Failure: "The SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" failed while attempting to resolve the SDK "Microsoft.NET.Sdk.Web". Exception: "System.IO.FileNotFoundException: Could not load file or assembly 'System.Collections.Immutable, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

 

File name: 'System.Collections.Immutable, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

   at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.CachingWorkloadResolver.Resolve(String sdkReferenceName, String dotnetRootPath, String sdkVersion, String userProfileDir, String globalJsonPath)

   at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.WorkloadSdkResolver.Resolve(SdkReference sdkReference, SdkResolverContext resolverContext, SdkResultFactory factory)

   at Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.TryResolveSdkUsingSpecifiedResolvers(IList`1 resolvers, Int32 submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath, Boolean interactive, Boolean isRunningInVisualStudio, SdkResult& sdkResult, IEnumerable`1& errors, IEnumerable`1& warnings)""  /Users/vs/RazorNoAuth/RazorNoAuth.csproj)

2023-09-12 15:47:31.038 [error] (/Users/vs/RazorNoAuth/RazorNoAuth.csproj): SDK Resolver Failure: "The SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" failed while attempting to resolve the SDK "Microsoft.NET.Sdk.Web". Exception: "System.IO.FileNotFoundException: Could not load file or assembly 'System.Collections.Immutable, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

 

File name: 'System.Collections.Immutable, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

   at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.CachingWorkloadResolver.Resolve(String sdkReferenceName, String dotnetRootPath, String sdkVersion, String userProfileDir, String globalJsonPath)

   at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.WorkloadSdkResolver.Resolve(SdkReference sdkReference, SdkResolverContext resolverContext, SdkResultFactory factory)

   at Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.TryResolveSdkUsingSpecifiedResolvers(IList`1 resolvers, Int32 submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath, Boolean interactive, Boolean isRunningInVisualStudio, SdkResult& sdkResult, IEnumerable`1& errors, IEnumerable`1& warnings)""

2023-09-12 15:47:31.151 [error] Failed to load project '/Users/vs/RazorNoAuth/RazorNoAuth.csproj'. One or more errors occurred. (SDK Resolver Failure: "The SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" failed while attempting to resolve the SDK "Microsoft.NET.Sdk.Web". Exception: "System.IO.FileNotFoundException: Could not load file or assembly 'System.Collections.Immutable, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

 

File name: 'System.Collections.Immutable, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

   at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.CachingWorkloadResolver.Resolve(String sdkReferenceName, String dotnetRootPath, String sdkVersion, String userProfileDir, String globalJsonPath)

   at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.WorkloadSdkResolver.Resolve(SdkReference sdkReference, SdkResolverContext resolverContext, SdkResultFactory factory)

   at Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.TryResolveSdkUsingSpecifiedResolvers(IList`1 resolvers, Int32 submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath, Boolean interactive, Boolean isRunningInVisualStudio, SdkResult& sdkResult, IEnumerable`1& errors, IEnumerable`1& warnings)""  /Users/vs/RazorNoAuth/RazorNoAuth.csproj)

2023-0</details>

# The original issue as filed is copied below

## Environment data

**VS Code version:** 1.81.1
**C# Extension version:** v 2.1.2
**C# Dev Kit:** v 0.5.2

## Steps to reproduce

1. Install the VsCode (`1.81.1`)
2.  Install the **C# Dev kit** (`v 0.5.2`) with C# extension (`v2.1.2`)
3. Create a new project by following code
```
mkdir Razor
cd Razor
dotnet new razor
```
4. `code .` to open the project.
5. F5 to run the project, then select .NET 5+ and .Net Core, the VsCode not respond.
6. When I try to create a launch.json file, will meet the error

## Note

1. This issue only repro on Mac OS.
2. This issue does not repro on Linux/Windows OS.
3. This issue does not repro if I only install the C# extension (`v 2.1.2`).

## Actual behavior

![MicrosoftTeams-image](https://github.com/dotnet/vscode-csharp/assets/108645282/7012adfe-f2ac-450f-96b1-034393e470f7)
![MicrosoftTeams-image (1)](https://github.com/dotnet/vscode-csharp/assets/108645282/2b392475-13b6-44a3-ab95-07846cf0cbb9)

## Expected  behavior

When I debug or run the project, it could create the configurations file successfully.

**Comment by Michael-Eng** [comment]
@dibarbet I'm not able to reference v-Judy but we've taken a newer MSBuidLocator in the prerelease builds of C# Dev Kit so this issue may be fixed.

**Comment by dibarbet** [comment]
@v-Judy would you mind trying the latest prerelease of C# devkit to check if it repros?  version v0.5.98

**Comment by v-Judy** [comment]
> @v-Judy would you mind trying the latest prerelease of C# devkit to check if it repros? version v0.5.98


This issue also repro on the latest prerelease of C# devkit `v0.5.98`.

**Comment by lifengl** [comment]
@v-Judy : can you run dotnet --info (run in a command shell inside the workspace folder) on your machine and capture the output here?  That will tells us what has been installed on the machine?

**Comment by v-Judy** [comment]
> @v-Judy : can you run dotnet --info (run in a command shell inside the workspace folder) on your machine and capture the output here? That will tells us what has been installed on the machine?

The `dotnet --info` show as below:
<details> <summary>dotnet --info</summary>
dotnet --info

.NET SDK:

Version:   8.0.100-rc.2.23471.16

Commit:    f1b52f68f8




Runtime Environment:

OS Name:     Mac OS X

OS Version:  13.2

OS Platform: Darwin

RID:         osx-x64

Base Path:   /usr/local/share/dotnet/sdk/8.0.100-rc.2.23471.16/




.NET workloads installed:

There are no installed workloads to display.




Host:

  Version:      8.0.0-rc.2.23466.4

  Architecture: x64

  Commit:       287c10d253




.NET SDKs installed:

  8.0.100-rc.2.23471.16 [/usr/local/share/dotnet/sdk]




.NET runtimes installed:

  Microsoft.AspNetCore.App 8.0.0-rtm.23468.24 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]

  Microsoft.NETCore.App 8.0.0-rc.2.23466.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]




Other architectures found:

  None




Environment variables:

  Not set




global.json file:

  Not found




Learn more:

  https://aka.ms/dotnet/info




Download .NET:

  https://aka.ms/dotnet/download
</details>
And after I created a project, then open it on VsCode, will meet this error:

![2](https://github.com/microsoft/vscode-dotnettools/assets/108645282/ef1eac0c-7344-4a2d-a9f8-d5e5f4bfb5f7)
The C# Dev Kit log show as below:
<details> <summary>C# Dev Kit log</summary>Version:1.0
StartHTML:000000096
EndHTML:000006693
StartFragment:000000186
EndFragment:000006679


Starting Spawn .NET server...

Starting Open a solution...

Starting Open a solution with environment service...

Starting Clear environment...

Using local .NET runtime at "/Users/admin/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.11/dotnet"

Using runtime installed in SDK.

.NET server started and IPC established in 4457ms

Completed Spawn .NET server (5385ms)

.NET server STDERR: Unhandled exception.

.NET server STDERR: System.NullReferenceException: Object reference not set to an instance of an object.

   at Microsoft.ServiceHub.Controller.LocationService.OnHostExit(HostInfo host, Int32 exitCode)

   at Microsoft.ServiceHub.Controller.LocationService.<>c__DisplayClass61_0.<StartNewHostAsync>b__7(Object s, EventArgs e)

   at System.Diagnostics.Process.RaiseOnExited()

   at System.Diagnostics.Process.CompletionCallback(Object waitHandleContext, Boolean wasSignaled)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

--- End of stack trace from previous location ---

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Threading.PortableThreadPool.CompleteWait(RegisteredWaitHandle handle, Boolean timedOut)

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

   at System.Threading.Thread.StartCallback()

 

.NET server STDERR: [createdump] Invalid process id: task_for_pid(7698) FAILED (os/kern) failure (5)

[createdump] This failure may be because createdump or the application is not properly signed and entitled.

 

.NET server STDERR: [createdump] Failure took 2ms

 

.NET server STDOUT: [createdump] Target process is alive

 

Completed Clear environment (8447ms)

Completed Open a solution with environment service (8539ms)

Starting Restore solution...

Completed Open a solution (8860ms)

Starting NuGet restore for the solution.

Starting command: "dotnet" restore /Users/admin/Razor/Razor.sln --interactive...

.NET server STDERR: Unhandled exception.

.NET server STDERR: System.NullReferenceException: Object reference not set to an instance of an object.

   at Microsoft.ServiceHub.Controller.LocationService.OnHostExit(HostInfo host, Int32 exitCode)

   at Microsoft.ServiceHub.Controller.LocationService.<>c__DisplayClass61_0.<StartNewHostAsync>b__7(Object s, EventArgs e)

   at System.Diagnostics.Process.RaiseOnExited()

   at System.Diagnostics.Process.CompletionCallback(Object waitHandleContext, Boolean wasSignaled)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

--- End of stack trace from previous location ---

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Threading.PortableThreadPool.CompleteWait(RegisteredWaitHandle handle, Boolean timedOut)

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

   at System.Threading.Thread.StartCallback()

.NET server STDERR:

 

.NET server STDERR: [createdump] Invalid process id: task_for_pid(7703) FAILED (os/kern) failure (5)

[createdump] This failure may be because createdump or the application is not properly signed and entitled.

[createdump] Failure took 0ms

 

.NET server STDOUT: [createdump] Target process is alive

 

Completed command: "dotnet" restore /Users/admin/Razor/Razor.sln --interactive (8642ms)

Completed NuGet restore.

Completed Restore solution (8646ms)

Failed to listen to project initialization status: $(err?.toString())</details>

**Comment by lifengl** [comment]
@v-Judy : 

There are two issues which could block you to open the solution on Mac:

1, I noticed that you installed X64 (intel based) SDK on the Mac. Can you conform this is an intel based Mac machine? We noticed some are using intel based SDK on new ARM based Mac machines, while dotnet command works on the top of a simulation layer, the C# Dev Kit was pre-built to match the CPU of the machine, and dotnet SDK has done the same thing, so they won't work in a same process.  If your Mac is intel based, it would be a right version of SDK to use.

2, you are using RC2 version of the NET 8 SDK, which is not released. I wonder you installed a daily build which is not fully signed (ad-hoc signed). Earlier released CDK does not support ad-hoc signed SDK, as Mac security layer blocks it to use ad-hoc signed binaries. The next pre-release would carry a new setting, which allows you to turn on a compatible mode to work with ad-hoc signed SDK on Mac. Can you try this scenario when it is released?

**Comment by v-Judy** [comment]
> @v-Judy :
> 
> There are two issues which could block you to open the solution on Mac:
> 
> 1,  Can you conform this is an intel based Mac machine?

Yes, this is an intel based Mac machine and install the X64 (intel based) SDK on it.
> 2, Can you try this scenario when it is released?

I will verify it after the 8.0 RC2 SDK released and update the results here if has any update.

**Comment by lifengl** [comment]
you can also set vscode setting "dotnet.workingWithTestSignedSdk": true on the machine to see whether it addresses the issue for you.

**Comment by Kirill-Ovc** [comment]
I had the same error in VS Code (1.85.1) and C# Dev Kit (v1.1.16).
Windows 10, DotNet SDK 8.0.100

I have solved it by installing 'System.Collections.Immutable' package from Nuget into the Project.
