### ISSUE TITLE
[BUG] ENOENT

### ISSUE THREAD

**Issue by Shadowblitz16** [microsoft/vscode-dotnettools#762]
### Describe the Issue

The C# Dev kit plugin doesn't work at all.
No create project window,
No solution explorer
```
2023-11-27 19:40:45.784 [info] Deleted uninstalled extension from disk adrianwilczynski.add-reference /home/shadowblitz16/.vscode/extensions/adrianwilczynski.add-reference-1.0.2
2023-11-27 19:40:45.785 [info] Deleted uninstalled extension from disk fullstackspider.visual-nuget /home/shadowblitz16/.vscode/extensions/fullstackspider.visual-nuget-0.2.1
2023-11-27 19:40:45.785 [info] Deleted uninstalled extension from disk ms-vscode.hexeditor /home/shadowblitz16/.vscode/extensions/ms-vscode.hexeditor-1.9.12
2023-11-27 19:40:45.785 [info] Deleted uninstalled extension from disk ms-vscode.mono-debug /home/shadowblitz16/.vscode/extensions/ms-vscode.mono-debug-0.16.3
2023-11-27 19:40:45.786 [info] Deleted uninstalled extension from disk tabnine.tabnine-vscode /home/shadowblitz16/.vscode/extensions/tabnine.tabnine-vscode-3.36.0
2023-11-27 19:41:13.830 [info] Getting Manifest... ms-dotnettools.csdevkit
2023-11-27 19:41:13.838 [info] Installing extension: ms-dotnettools.csdevkit
2023-11-27 19:41:14.297 [info] Getting Manifest... ms-dotnettools.csharp
2023-11-27 19:41:14.381 [info] Getting Manifest... ms-dotnettools.vscode-dotnet-runtime
2023-11-27 19:41:14.389 [info] Getting Manifest... ms-dotnettools.vscodeintellicode-csharp
2023-11-27 19:41:14.465 [info] Installing extension: ms-dotnettools.csharp ms-dotnettools.csdevkit
2023-11-27 19:41:14.465 [info] Installing extension: ms-dotnettools.vscode-dotnet-runtime ms-dotnettools.csdevkit
2023-11-27 19:41:14.465 [info] Installing extension: ms-dotnettools.vscodeintellicode-csharp ms-dotnettools.csdevkit
2023-11-27 19:41:15.294 [info] Extension signature is verified: ms-dotnettools.vscode-dotnet-runtime
2023-11-27 19:41:15.354 [info] Extracted extension to file:///home/shadowblitz16/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.0.0: ms-dotnettools.vscode-dotnet-runtime
2023-11-27 19:41:15.360 [info] Renamed to /home/shadowblitz16/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.0.0
2023-11-27 19:41:15.361 [info] Extracting extension completed. ms-dotnettools.vscode-dotnet-runtime
2023-11-27 19:41:15.443 [error] [uncaught exception in sharedProcess]: Error: ENOENT: no such file or directory, stat '/home/shadowblitz16/.vscode/extensions/extensions.json.vsctmp': EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat '/home/shadowblitz16/.vscode/extensions/extensions.json.vsctmp'
    at r.create (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:51:30053)
    at a (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:51:30167)
    at s.fb (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:56:36175)
    at s.stat (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:56:28621)
    at async E.stat (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:56:15732)
    at async K.tb (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:109:9535)
2023-11-27 19:44:04.098 [info] Extension signature is verified: ms-dotnettools.csharp
2023-11-27 19:44:07.238 [info] Extracted extension to file:///home/shadowblitz16/.vscode/extensions/ms-dotnettools.csharp-2.10.28-linux-x64: ms-dotnettools.csharp
2023-11-27 19:44:07.247 [info] Renamed to /home/shadowblitz16/.vscode/extensions/ms-dotnettools.csharp-2.10.28-linux-x64
2023-11-27 19:44:07.252 [info] Extracting extension completed. ms-dotnettools.csharp
2023-11-27 19:44:07.334 [error] [uncaught exception in sharedProcess]: Error: ENOENT: no such file or directory, stat '/home/shadowblitz16/.vscode/extensions/extensions.json.vsctmp': EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat '/home/shadowblitz16/.vscode/extensions/extensions.json.vsctmp'
    at r.create (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:51:30053)
    at a (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:51:30167)
    at s.fb (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:56:36175)
    at s.stat (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:56:28621)
    at async E.stat (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:56:15732)
    at async K.tb (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:109:9535)
2023-11-27 19:45:01.967 [info] Extension signature is verified: ms-dotnettools.csdevkit
2023-11-27 19:45:03.059 [info] Extracted extension to file:///home/shadowblitz16/.vscode/extensions/ms-dotnettools.csdevkit-1.0.14-linux-x64: ms-dotnettools.csdevkit
2023-11-27 19:45:03.066 [info] Renamed to /home/shadowblitz16/.vscode/extensions/ms-dotnettools.csdevkit-1.0.14-linux-x64
2023-11-27 19:45:03.070 [info] Extracting extension completed. ms-dotnettools.csdevkit
2023-11-27 19:45:03.153 [error] [uncaught exception in sharedProcess]: Error: ENOENT: no such file or directory, stat '/home/shadowblitz16/.vscode/extensions/extensions.json.vsctmp': EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat '/home/shadowblitz16/.vscode/extensions/extensions.json.vsctmp'
    at r.create (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:51:30053)
    at a (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:51:30167)
    at s.fb (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:56:36175)
    at s.stat (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:56:28621)
    at async E.stat (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:56:15732)
    at async K.tb (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:109:9535)
2023-11-27 19:45:04.285 [info] Extension signature is verified: ms-dotnettools.vscodeintellicode-csharp
2023-11-27 19:45:06.122 [info] Extracted extension to file:///home/shadowblitz16/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-0.1.26-linux-x64: ms-dotnettools.vscodeintellicode-csharp
2023-11-27 19:45:06.129 [info] Renamed to /home/shadowblitz16/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-0.1.26-linux-x64
2023-11-27 19:45:06.130 [info] Extracting extension completed. ms-dotnettools.vscodeintellicode-csharp
2023-11-27 19:45:06.141 [info] Extension installed successfully: ms-dotnettools.vscode-dotnet-runtime
2023-11-27 19:45:06.141 [info] Extension installed successfully: ms-dotnettools.csharp
2023-11-27 19:45:06.141 [info] Extension installed successfully: ms-dotnettools.csdevkit
2023-11-27 19:45:06.141 [info] Extension installed successfully: ms-dotnettools.vscodeintellicode-csharp
2023-11-27 19:45:06.215 [error] [uncaught exception in sharedProcess]: Error: ENOENT: no such file or directory, stat '/home/shadowblitz16/.vscode/extensions/extensions.json.vsctmp': EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat '/home/shadowblitz16/.vscode/extensions/extensions.json.vsctmp'
    at r.create (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:51:30053)
    at a (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:51:30167)
    at s.fb (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:56:36175)
    at s.stat (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:56:28621)
    at async E.stat (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:56:15732)
    at async K.tb (/usr/share/code/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:109:9535)
```

### Steps To Reproduce

1. In Kubuntu 22.04
2. Install vscode from official website deb file
3. Update to latest
4. Install .net 7.0.114
5. UnInstall all plugins except Bash IDE and GitGraph
6. Install C# dev kit
7. Look in Output (Shared tab)

### Expected Behavior

I expected the plugin to work.

### Environment Information

Linux: Kubuntu 22.04
VSCode: 1.84.2
C# Dev kit: v1.0.14

**Comment by Michael-Eng** [comment]
@Shadowblitz16 we're going through our bugs. is this issue still reproduce for you?

**Comment by Shadowblitz16** [comment]
@Michael-Eng I haven't run into it again no
