### ISSUE TITLE
[BUG] Solution Explorer Does Not Load, No Intellisense

### ISSUE THREAD

**Issue by lukewis** [microsoft/vscode-dotnettools#816]
### Describe the Issue

When using the remote ssh extension to connect from MacOS to Ubuntu, the solution explorer fails to load and intellisense does not work correctly.

### Steps To Reproduce

1. Connect from MacOS to Ubuntu using VSCode
1. Open a terminal window (from within vscode) and type `dotnet new console -n dotnettools-sample`
1. Open the newly created project in VS Code (Open Folder)
1. Notice that the solution explorer view does not load
1. Notice that intellisense does not work in Program.cs

### Expected Behavior

- Solution explorer loads correctly
- Intellisense works

### Environment Information

```
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.6c33ef20

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /snap/dotnet-sdk/228/sdk/8.0.100/

.NET workloads installed:
 Workload version: 8.0.100-manifests.6c33ef20
There are no installed workloads to display.

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  8.0.100 [/snap/dotnet-sdk/228/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0 [/snap/dotnet-sdk/228/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.0 [/snap/dotnet-sdk/228/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found
```

C# Output
```
Using dotnet configured on PATH
Dotnet path: /snap/dotnet-sdk/228/dotnet
Activating C# + C# Dev Kit + C# IntelliCode...
waiting for named pipe information from server...
[stdout] {"pipeName":"/tmp/fcddf4cd.sock"}
received named pipe information from server
attempting to connect client to server...
client has connected to server
[Info  - 4:03:48 AM] [Program] Language server initialized
```

C# DevKit Output
```
Starting Open a solution...
Starting Open a solution with environment service...
Starting Clear environment...
Starting Spawn .NET server...
Using local .NET runtime at "/home/lawisnie/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.14~x64/dotnet"
Using runtime installed in SDK.
.NET server started and IPC established in 2046ms
Completed Spawn .NET server (3362ms)
Completed Clear environment (4064ms)
Completed Open a solution with environment service (4171ms)
Starting Restore solution...
Completed Open a solution (4187ms)
Starting NuGet restore for the solution.
Starting command: "dotnet" restore /home/lawisnie/src/dotnettools-sample/dotnettools-sample.sln --interactive...
.NET server STDERR: Unhandled exception. 
.NET server STDERR: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.ServiceHub.Controller.LocationService.OnHostExit(HostInfo host, Int32 exitCode)
   at Microsoft.ServiceHub.Controller.LocationService.<>c__DisplayClass61_0.<StartNewHostAsync>b__0(Object s, EventArgs e)
   at System.Diagnostics.Process.RaiseOnExited()
   at System.Diagnostics.Process.CompletionCallback(Object waitHandleContext, Boolean wasSignaled)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.PortableThreadPool.CompleteWait(RegisteredWaitHandle handle, Boolean timedOut)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

.NET server STDOUT: [createdump] Gathering state for process 1992668 Microsoft.Servi
[createdump] Crashing thread 1e67fb signal 6 (0006)

.NET server STDOUT: [createdump] Writing crash report to file /home/lawisnie/.cache/Microsoft/csdevkit/dumps/Microsoft.Servi.1992668.dmp.crashreport.json

.NET server STDOUT: [createdump] Crash report successfully written

Completed command: "dotnet" restore /home/lawisnie/src/dotnettools-sample/dotnettools-sample.sln --interactive (3054ms)
Completed NuGet restore.
Completed Restore solution (3063ms)
.NET server STDOUT: [createdump] Writing minidump with heap to file /home/lawisnie/.cache/Microsoft/csdevkit/dumps/Microsoft.Servi.1992668.dmp

.NET server STDOUT: [createdump] Written 236240896 bytes (57676 pages) to core file
[createdump] Target process is alive

.NET server STDOUT: [createdump] Dump successfully written in 20225ms

Failed to listen to project initialization status: Error: Activating the "Microsoft.VisualStudio.ProjectSystem.ProjectInitializationStatusService (0.1)" service failed.
```

Dump File: https://drive.google.com/file/d/1ce0RuJRNr88U6uCiLRu9kZLEG1HJpD4T/view?usp=sharing

**Comment by AArnott** [comment]
@ryantoth3: ServiceHub related.

**Comment by justinmchase** [comment]
I have this same issue except the output in the Dev Kit looks clean.

Here is my `C# Output`

```
Using dotnet configured on PATH
Dotnet path: /usr/local/share/dotnet/dotnet
Activating C# + C# Dev Kit + C# IntelliCode...
waiting for named pipe information from server...
[Error - 2:45:13 PM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
Error: Timeout. Named pipe information not received from server.
    at Function.<anonymous> (/Users/jchase24/.vscode/extensions/ms-dotnettools.csharp-2.15.30-darwin-x64/dist/extension.js:2:1290803)
    at Generator.next (<anonymous>)
    at s (/Users/jchase24/.vscode/extensions/ms-dotnettools.csharp-2.15.30-darwin-x64/dist/extension.js:2:1280740)
[stdout] {"pipeName":"/var/folders/_g/dy89fn8x4w145dxx_g0ptgm99xqs15/T/53dcf195.sock"}
received named pipe information from server
```

It looks like it is getting the info from the named pipe eventually but after the timeout happens which then causes it to fail.

If I just reload the developer window it will _tend to_ work. If I have more than one VSCode open at a time only one of them seems to work at a time.

What could cause the language server to respond so slowly?

**Comment by Michael-Eng** [comment]
Looking at some of our older bugs. We've tried this in recent builds on Linux and we cannot repro it so I'm closing this bug.
