### ISSUE TITLE
[BUG] Unable to run or discover tests after update `The method or operation is not implemented.` 

### ISSUE THREAD

**Issue by Xeevis** [microsoft/vscode-dotnettools#910]
### Describe the Issue

From Test Explorer:

<details>

<summary>Up to `1.3.4` - Tests run and debug flawlessly</summary>

```
Created Test Controller
Using vstest from dotnet sdk in [/usr/share/dotnet/sdk/8.0.101].
Initialized Test Explorer Server [60734]
Test Store Folder: /home/vscode/.vscode-server/data/User/workspaceStorage/dafa71c47a68a3ea2ecbd9790b0efbbe/ms-dotnettools.csdevkit
Test data store opened in 0.035 sec.
Initialized project system provider.
2 projects added, 0 changed, 0 removed.
Scheduling discovery: /workspace/tests/JadeX.AllegroAPI.Tests.Unit/bin/Debug/net8.0/JadeX.AllegroAPI.Tests.Unit.dll [1707636215708]
Scheduling discovery: /workspace/tests/JadeX.AllegroAPI.Tests.Integration/bin/Debug/net8.0/JadeX.AllegroAPI.Tests.Integration.dll [1707637027900]
========== Starting test discovery ==========
No test is available in /workspace/tests/JadeX.AllegroAPI.Tests.Unit/bin/Debug/net8.0/JadeX.AllegroAPI.Tests.Unit.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
========== Test discovery finished: 7 Tests found in 740.2 ms ==========
7 tests discovered from /workspace/tests/JadeX.AllegroAPI.Tests.Integration/bin/Debug/net8.0/JadeX.AllegroAPI.Tests.Integration.dll;/workspace/tests/JadeX.AllegroAPI.Tests.Unit/bin/Debug/net8.0/JadeX.AllegroAPI.Tests.Unit.dll in 740.1534 ms
========== Starting test discovery ==========
Tests changed, running test discovery: /workspace/tests/JadeX.AllegroAPI.Tests.Integration/bin/Debug/net8.0/JadeX.AllegroAPI.Tests.Integration.dll
========== Test discovery finished: 7 Tests found in 219.4 ms ==========
========== Starting test run ==========
Debugger attached
========== Test run finished: 1 Tests (1 Passed, 0 Failed, 0 Skipped) run in 1.4 sec ==========
```
</details>

---
From `1.3.6` up to `1.4.2` errors are thrown and debug is stuck in infinite loading, tests discovery also appears to be broken, I'm on linux devcontainer and it's searching for exe files.

```
Created Test Controller
Using vstest from dotnet sdk in [/usr/share/dotnet/sdk/8.0.101].
Initialized Test Explorer Server [69938]
Test Store Folder: /home/vscode/.vscode-server/data/User/workspaceStorage/dafa71c47a68a3ea2ecbd9790b0efbbe/ms-dotnettools.csdevkit
Test data store opened in 0.046 sec.
Initialized project system provider.
2 projects added, 0 changed, 0 removed.
Scheduling discovery: /workspace/tests/JadeX.AllegroAPI.Tests.Unit/bin/Debug/net8.0/JadeX.AllegroAPI.Tests.Unit.dll [1707636215708]
Scheduling discovery: /workspace/tests/JadeX.AllegroAPI.Tests.Integration/bin/Debug/net8.0/JadeX.AllegroAPI.Tests.Integration.dll [1707637345478]
========== Starting test discovery ==========
System.ComponentModel.Win32Exception (2): An error occurred trying to start process '/workspace/tests/JadeX.AllegroAPI.Tests.Integration/bin/Debug/net8.0/JadeX.AllegroAPI.Tests.Integration.exe' with working directory '/workspace/tests/JadeX.AllegroAPI.Tests.Integration/bin/Debug/net8.0'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at Microsoft.VisualStudio.TestWindow.Internal.RemoteAgent.TestingPlatform.TestingPlatformRunnerProcess.StartAsync()
   at Microsoft.VisualStudio.TestWindow.Internal.RemoteAgent.TestingPlatform.Providers.ClientServerProvider.StartProcessWithoutDebuggerAsync(TestingPlatformLaunchConfig config)
System.ComponentModel.Win32Exception (2): An error occurred trying to start process '/workspace/tests/JadeX.AllegroAPI.Tests.Unit/bin/Debug/net8.0/JadeX.AllegroAPI.Tests.Unit.exe' with working directory '/workspace/tests/JadeX.AllegroAPI.Tests.Unit/bin/Debug/net8.0'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at Microsoft.VisualStudio.TestWindow.Internal.RemoteAgent.TestingPlatform.TestingPlatformRunnerProcess.StartAsync()
   at Microsoft.VisualStudio.TestWindow.Internal.RemoteAgent.TestingPlatform.Providers.ClientServerProvider.StartProcessWithoutDebuggerAsync(TestingPlatformLaunchConfig config)
Unable to start testing platform runner process '/workspace/tests/JadeX.AllegroAPI.Tests.Integration/bin/Debug/net8.0/JadeX.AllegroAPI.Tests.Integration.exe'.
Unable to start testing platform runner process '/workspace/tests/JadeX.AllegroAPI.Tests.Unit/bin/Debug/net8.0/JadeX.AllegroAPI.Tests.Unit.exe'.
0 tests discovered from  in 103.0075 ms
========== Test discovery aborted: 0 Tests found in 103 ms ==========
========== Starting test discovery ==========
System.ComponentModel.Win32Exception (2): An error occurred trying to start process '/workspace/tests/JadeX.AllegroAPI.Tests.Integration/bin/Debug/net8.0/JadeX.AllegroAPI.Tests.Integration.exe' with working directory '/workspace/tests/JadeX.AllegroAPI.Tests.Integration/bin/Debug/net8.0'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at Microsoft.VisualStudio.TestWindow.Internal.RemoteAgent.TestingPlatform.TestingPlatformRunnerProcess.StartAsync()
   at Microsoft.VisualStudio.TestWindow.Internal.RemoteAgent.TestingPlatform.Providers.ClientServerProvider.StartProcessWithoutDebuggerAsync(TestingPlatformLaunchConfig config)
Unable to start testing platform runner process '/workspace/tests/JadeX.AllegroAPI.Tests.Integration/bin/Debug/net8.0/JadeX.AllegroAPI.Tests.Integration.exe'.
========== Test discovery aborted: 0 Tests found in 2 ms ==========
========== Starting test run ==========
System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.VisualStudio.TestWindow.VSCode.Service.TestWindowCallbackService.LaunchDebugTestHostAsync(LaunchTestHostRequest launchRequest, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestWindow.Logging.ILoggerExtensions.CallWithCatchAsync[T](IInternalLogger log, Func`1 func, T defaultValue)
Tests changed, running test discovery: /workspace/tests/JadeX.AllegroAPI.Tests.Integration/bin/Debug/net8.0/JadeX.AllegroAPI.Tests.Integration.dll
```

### Environment Information

- **VS Code Version:** 1.86.1 (user setup)
- **ms-dotnettools.csdevkit**: version 1.3.10 through 1.4.2
- **DevContainer:** mcr.microsoft.com/devcontainers/dotnet:1-8.0-bookworm
- **Docker for Windows:** 4.27.1 + WSL2 engine + Ubuntu

**Comment by mdesalvo** [comment]
I use Mageia Linux (VSCode 1.86.1 with .NET SDK 8.0.101). 
After the latest update of C# Dev Kit extension (from 1.2.7 to 1.3.10) it seems that the entire test system of VSCode gets stuck trying to deal with .EXE files. Why under Linux it makes this tremendous platform mistake? I have to revert this extension to 1.2.7, which is the last working.

**Comment by drognanar** [comment]
@Xeevis what is the test adapter that you're using for your project?

**Comment by Xeevis** [comment]
> @Xeevis what is the test adapter that you're using for your project?

```
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
<PackageReference Include="MSTest.TestAdapter" Version="3.2.0" />
<PackageReference Include="MSTest.TestFramework" Version="3.2.0" />
```

**Comment by drognanar** [comment]
thanks, I'll give this a try.

the workaround at the moment would be to create a .vscode/settings.json file and add the following setting there:

```json
{
  "dotnet.testWindow.useTestingPlatformProtocol": false
}
```

**Comment by drognanar** [comment]
I merged in a fix for this issue, so this should be fixed in the next release

**Comment by ShreyasJejurkar** [comment]
Just hit this after the .NET 8 upgrade. :(

**Comment by peterwald** [comment]
Fixed in the latest release.
