### ISSUE TITLE
[BUG] Debugger crashes, when enabling searchNuGetOrgSymbolServer

### ISSUE THREAD

**Issue by markusroessler** [microsoft/vscode-dotnettools#951]
### Describe the Issue

The debugger crashes on startup when enabling the setting "csharp.debug.symbolOptions.searchNuGetOrgSymbolServer" 
Message from debug console:
```
The debugger worker process (vsdbg) exited unexpectedly.

Internal error in the debugger.
Exception = System.IO.IOException
Message = Pipe is broken.
Code = 8007006D
   at System.IO.Pipes.PipeStream.WriteCore(ReadOnlySpan`1 buffer)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at VsDbg.Transports.StreamTransport.Send(String message)
   at VsDbg.Transports.ConsoleTransport.Send(String message)
Internal error in the debugger.
```

**Notes** 
- enabling "csharp.debug.symbolOptions.searchMicrosoftSymbolServer" does **not** crash the debugger
- only occurs on my Windows machine - works fine on my Mac OS machine

### Steps To Reproduce

1. create a new dotnet console project
2. enable setting "csharp.debug.symbolOptions.searchNuGetOrgSymbolServer"
3. start debugging
4. the debugger fails to start
5. disable setting "csharp.debug.symbolOptions.searchNuGetOrgSymbolServer"
6. the debugger starts successfully

### Expected Behavior

The debugger should not crash or at least output the exact reason for the crash.

### Environment Information

- OS: Windows 10
- VSCode: 1.86.2
- Devkit: 1.3.10

**Comment by WardenGnaw** [comment]
Thank you for reporing this issue with clear repro steps. However this is a duplicate of https://github.com/microsoft/vscode-dotnettools/issues/944 and is tracked at https://github.com/dotnet/vscode-csharp/issues/6918. 

Work around is to disable `searchNuGetOrgSymbolServer` for now or use vscode-csharp [v2.15.30](https://github.com/dotnet/vscode-csharp/releases/tag/v2.15.30)
